Repository GregTechCEu/GregTech, pull requests merged in 2022-01, with the labels that each got.

#393 Add the ability for custom chance functions per RecipeMap
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: low priority

#472 Add Tricorder and Debug Scanners
  src/main/java/gregtech/api/metatileentity/IDataInfoProvider.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/api/metatileentity/WorkableTieredMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/multiblock/FuelMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/common/items/behaviors/TricorderBehavior.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityBatteryBuffer.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMiner.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityElectricBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/common/metatileentities/steam/SteamMiner.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java
  src/main/java/gregtech/common/pipelike/cable/tile/TileEntityCable.java
  src/main/java/gregtech/common/pipelike/fluidpipe/tile/TileEntityFluidPipe.java
  src/main/java/gregtech/loaders/recipe/handlers/ToolRecipeHandler.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/metaitems/debug_scanner.json
  src/main/resources/assets/gregtech/models/item/metaitems/tricorder_scanner.json
  src/main/resources/assets/gregtech/textures/items/metaitems/debug_scanner.png
  src/main/resources/assets/gregtech/textures/items/metaitems/tricorder_scanner.png
Labels: rsr: minor, subsystem: metaitems, type: feature

#469 NC compat
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/common/items/armor/PowerlessJetpack.java
  src/main/java/gregtech/core/GregTechTransformer.java
  src/main/java/gregtech/core/visitors/NuclearCraftRecipeHelperVisitor.java
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
Labels: release priority

#507 Fix enet connection issues
  src/main/java/gregtech/api/pipenet/PipeNetWalker.java
  src/main/java/gregtech/common/pipelike/cable/net/EnergyNet.java
  src/main/java/gregtech/common/pipelike/cable/net/EnergyNetHandler.java
  src/main/java/gregtech/common/pipelike/cable/tile/TileEntityCable.java
Labels: release priority

#432 Handle materials ending in "_numbers" properly
  src/main/java/gregtech/api/items/metaitem/MetaOreDictItem.java
  src/main/java/gregtech/api/unification/OreDictUnifier.java
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/UnknownCompositionMaterials.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/blocks/BlockCompressed.java
  src/main/java/gregtech/common/blocks/BlockFrame.java
  src/main/java/gregtech/common/blocks/BlockSurfaceRock.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/blocks/properties/PropertyMaterial.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.helium_3.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.helium_3.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.mc_guffium_239.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.mc_guffium_239.png.mcmeta
Labels: release priority

#509 Pipe connection fixes & Item pipe fixes
  src/main/java/gregtech/api/block/machines/MachineItemBlock.java
  src/main/java/gregtech/api/cover/CoverBehavior.java
  src/main/java/gregtech/api/pipenet/PipeNetWalker.java
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/api/pipenet/block/ItemBlockPipe.java
  src/main/java/gregtech/api/pipenet/tile/AttachmentType.java
  src/main/java/gregtech/api/pipenet/tile/IPipeTile.java
  src/main/java/gregtech/api/pipenet/tile/PipeCoverableImplementation.java
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
  src/main/java/gregtech/api/util/FacingPos.java
  src/main/java/gregtech/client/renderer/handler/ToolOverlayRenderer.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverCraftingTable.java
  src/main/java/gregtech/common/covers/CoverFacade.java
  src/main/java/gregtech/common/covers/CoverScreen.java
  src/main/java/gregtech/common/covers/CoverShutter.java
  src/main/java/gregtech/common/metatileentities/multi/electric/centralmonitor/MetaTileEntityCentralMonitor.java
  src/main/java/gregtech/common/pipelike/cable/BlockCable.java
  src/main/java/gregtech/common/pipelike/cable/Insulation.java
  src/main/java/gregtech/common/pipelike/cable/net/EnergyNet.java
  src/main/java/gregtech/common/pipelike/fluidpipe/BlockFluidPipe.java
  src/main/java/gregtech/common/pipelike/fluidpipe/tile/TileEntityFluidPipe.java
  src/main/java/gregtech/common/pipelike/itempipe/net/ItemNetHandler.java
  src/main/java/gregtech/common/pipelike/itempipe/net/ItemPipeNet.java
  src/main/java/gregtech/common/pipelike/itempipe/tile/TileEntityItemPipe.java
Labels: release priority

#254 Make a Cape System that doesn't break the EULA
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/gui/widgets/ClickButtonWidget.java
  src/main/java/gregtech/api/net/NetworkHandler.java
  src/main/java/gregtech/api/net/packets/SPacketNotifyCapeChange.java
  src/main/java/gregtech/api/terminal/TerminalRegistry.java
  src/main/java/gregtech/api/util/CapesRegistry.java
  src/main/java/gregtech/client/ClientProxy.java
  src/main/java/gregtech/client/event/ClientEventHandler.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/EventHandlers.java
  src/main/java/gregtech/common/terminal/app/capeselector/CapeSelectorApp.java
  src/main/java/gregtech/common/terminal/app/capeselector/widget/CapeListWidget.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/capes/greencape.png
  src/main/resources/assets/gregtech/textures/capes/gregtechcape.png
  src/main/resources/assets/gregtech/textures/capes/redcape.png
  src/main/resources/assets/gregtech/textures/capes/yellowcape.png
  src/main/resources/gregtech_at.cfg
Labels: release priority

#547 Fluidpipes transfer rate fix
  src/main/java/gregtech/common/pipelike/fluidpipe/BlockFluidPipe.java
  src/main/java/gregtech/common/pipelike/fluidpipe/net/FluidPipeNet.java
  src/main/java/gregtech/common/pipelike/fluidpipe/tile/TileEntityFluidPipe.java
Labels: release priority

#566 Pipe connection fix
  src/main/java/gregtech/api/pipenet/PipeNet.java
  src/main/java/gregtech/api/pipenet/WorldPipeNet.java
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/api/pipenet/block/ItemBlockPipe.java
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
  src/main/java/gregtech/common/pipelike/cable/BlockCable.java
  src/main/java/gregtech/common/pipelike/cable/net/EnergyNet.java
  src/main/java/gregtech/common/pipelike/itempipe/BlockItemPipe.java
  src/main/java/gregtech/common/pipelike/itempipe/net/ItemPipeNet.java
Labels: release priority

#443 Add fluid drilling rigs
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/capability/impl/FluidDrillLogic.java
  src/main/java/gregtech/api/net/NetworkHandler.java
  src/main/java/gregtech/api/net/packets/CPacketFluidVeinList.java
  src/main/java/gregtech/api/terminal/TerminalRegistry.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/worldgen/bedrockFluids/BedrockFluidVeinHandler.java
  src/main/java/gregtech/api/worldgen/config/BedrockFluidDepositDefinition.java
  src/main/java/gregtech/api/worldgen/config/WorldGenRegistry.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/EventHandlers.java
  src/main/java/gregtech/common/items/behaviors/ProspectorScannerBehavior.java
  src/main/java/gregtech/common/items/behaviors/TricorderBehavior.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
  src/main/java/gregtech/common/terminal/app/prospector/widget/WidgetProspectingMap.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/multiblock/fluid_drilling_rig/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/fluid_drilling_rig/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/fluid_drilling_rig/overlay_front_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/fluid_drilling_rig/overlay_front_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/fluid_drilling_rig/overlay_front_paused.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/fluid_drilling_rig/overlay_front_paused_emissive.png
  src/main/resources/assets/gregtech/worldgen/fluid/nether/lava_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/nether/natural_gas_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/overworld/heavy_oil_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/overworld/light_oil_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/overworld/natural_gas_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/overworld/oil_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/overworld/raw_oil_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/overworld/salt_water_deposit.json
  src/main/resources/assets/gregtech/worldgen/worldgen_extracted.json
  src/main/resources/assets/gregtech/worldgen/worldgen_extracted.txt
Labels: release priority

#582 2.1 fixes
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/api/pattern/TraceabilityPredicate.java
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/api/pipenet/tile/PipeCoverableImplementation.java
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityRockBreaker.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityRotorHolder.java
  src/main/java/gregtech/common/pipelike/cable/BlockCable.java
  src/main/java/gregtech/common/pipelike/fluidpipe/tile/TileEntityFluidPipeTickable.java
Labels: release priority
