Repository GregTechCEu/GregTech, pull requests merged in 2022-08, with the labels that each got.

#1109 Enable UHV Energy Converters
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
Labels: type: feature

#1106 Fix NPE with Ender Fluid Link Cover
  src/main/java/gregtech/common/covers/CoverEnderFluidLink.java
Labels: type: bug

#1098 Fix RecipeMap Text Overlaps in JEI
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/integration/jei/recipe/RecipeMapCategory.java
Labels: type: bug

#1108 Log Errors in Material Related Logs Better
  src/main/java/gregtech/common/pipelike/cable/BlockCable.java
  src/main/java/gregtech/common/pipelike/fluidpipe/BlockFluidPipe.java
  src/main/java/gregtech/common/pipelike/itempipe/BlockItemPipe.java
Labels: type: feature

#1104 GitHub and CI Improvements, Autogenerated Releases
  .github/ISSUE_TEMPLATE/000-crash-report.yml
  .github/ISSUE_TEMPLATE/001-bug-report.yml
  .github/ISSUE_TEMPLATE/002-feature-request.yml
  .github/ISSUE_TEMPLATE/003-question.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/pull_request_template.md
  .github/release.yml
  .github/workflows/curseforge_release.yml
  .github/workflows/github_release.yml
  .github/workflows/pr_enforce_labels.yml
  build.gradle.kts
Labels: ignore changelog

#1118 Fix a NPE when clicking on unpowered Central Monitor
  src/main/java/gregtech/api/gui/UIFactory.java
Labels: type: bug

#1122 Fix zh_cn.lang pipe transfer rate unit
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#1103 Update ja_jp.lang
  src/main/resources/assets/gregtech/lang/ja_jp.lang
Labels: type: translation

#1083 Allow Batteries to charge FE items
  src/main/java/gregtech/api/items/metaitem/ElectricStats.java
Labels: type: feature

#1115 Apply Recycling voltage multiplier to magnetic materials if applicable
  src/main/java/gregtech/api/unification/material/properties/IngotProperty.java
  src/main/java/gregtech/loaders/recipe/RecyclingRecipes.java
Labels: type: bug

#1126 update ref to the itemstack copy
  src/main/java/gregtech/common/command/CommandRecipeCheck.java
Labels: type: bug

#1119 Fix Addon Recipe Removal and Addition Bug
  src/main/java/gregtech/api/recipes/ModHandler.java
Labels: type: bug

#1082 Add Machine Particles
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/capability/impl/RecipeLogicSteam.java
  src/main/java/gregtech/api/capability/impl/SteamMultiblockRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SteamMetaTileEntity.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMagicEnergyAbsorber.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityCokeOven.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/steam/SteamAlloySmelter.java
  src/main/java/gregtech/common/metatileentities/steam/SteamCompressor.java
  src/main/java/gregtech/common/metatileentities/steam/SteamExtractor.java
  src/main/java/gregtech/common/metatileentities/steam/SteamFurnace.java
  src/main/java/gregtech/common/metatileentities/steam/SteamHammer.java
  src/main/java/gregtech/common/metatileentities/steam/SteamMacerator.java
  src/main/java/gregtech/common/metatileentities/steam/SteamRockBreaker.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamLavaBoiler.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamSolarBoiler.java
Labels: type: feature

#1120 Fix parallel logic append EUt consumption
  src/main/java/gregtech/api/recipes/logic/ParallelLogic.java
Labels: type: bug

#1131 Attempt to fix the Wireless Digital Interface Cover
  src/main/java/gregtech/common/covers/CoverDigitalInterfaceWireless.java
Labels: type: bug

#1129 Fix property storage null + dimension property list issues
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/GasCollectorRecipeBuilder.java
Labels: type: bug

#1141 Add Passthrough Hatch MultiblockAbility for addons
  src/main/java/gregtech/api/metatileentity/multiblock/IPassthroughHatch.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockAbility.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityDiode.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityHull.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityPassthroughHatchFluid.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityPassthroughHatchItem.java
Labels: status: release blocker, type: feature

#1146 Prevent Chisel Concrete from Conflicting with GT Concrete
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/loaders/OreDictionaryLoader.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
Labels: type: bug

#1145 Remove Wrought Iron Round
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
Labels: type: refactor

#1127 extend ShapedOreRecipe along with implementing a fluid ingredient for crafting recipes
  src/main/java/gregtech/api/block/machines/MachineItemBlock.java
  src/main/java/gregtech/api/items/metaitem/stats/ItemFluidContainer.java
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/common/crafting/GTFluidCraftingIngredient.java
  src/main/java/gregtech/common/crafting/GTShapedNBTClearingOreRecipe.java
  src/main/java/gregtech/common/crafting/GTShapedOreRecipe.java
  src/main/java/gregtech/common/crafting/GTShapelessNBTClearingOreRecipe.java
  src/main/java/gregtech/common/crafting/GTShapelessOreRecipe.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
Labels: type: bug

#1021 Fix being able to dupe items via Machine Access Interface
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMachineHatch.java
Labels: type: bug

#1130 Fix some issues when crafting with Electric items
  src/main/java/gregtech/api/util/ShapedOreEnergyTransferRecipe.java
Labels: type: bug

#1091 Make fluid pipes drainable
  src/main/java/gregtech/common/pipelike/fluidpipe/net/PipeTankList.java
Labels: type: bug

#1139 Update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#1099 Add Processing Array compatibility for Rock Breaker
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityRockBreaker.java
Labels: type: feature

#1111 Expose combined inventory of Quantum Chest via capability
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
Labels: type: bug

#1128 Adding machine recipes for several Treated Wood items
  src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/AssemblerRecipeLoader.java
Labels: type: feature

#1151 Remove machine fluid filtering
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/WorkableTieredMetaTileEntity.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapFluidCanner.java
  src/main/java/gregtech/common/items/armor/PowerlessJetpack.java
Labels: type: bug

#1155 Check against the CT ingredient's internal object
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipeBuilder.java
Labels: type: bug

#1143 Update boiler production tooltip from /s to /t
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1161 fix #1140
  src/main/java/gregtech/loaders/recipe/BatteryRecipes.java
Labels: type: bug
