Repository GregTechCEu/GregTech, pull requests merged in 2022-10, with the labels that each got.

#1209 Fix #1089, Spray Can maceration material transmutation
  src/main/java/gregtech/common/items/MetaItem1.java
Labels: type: bug

#1214 Fix Muffler Hatch voiding items when broken
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
Labels: type: bug

#1215 Fix Diodes only outputting 8A on 16A mode
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityDiode.java
Labels: type: bug

#1213 Don't transfer charge from electric tools
  src/main/java/gregtech/api/util/ShapedOreEnergyTransferRecipe.java
Labels: type: bug

#1218 Fix crash with Item Filter
  src/main/java/gregtech/common/covers/CoverItemFilter.java
Labels: type: bug

#1221 Add causeMaintenanceProblems() to IMaintenance
  src/main/java/gregtech/api/metatileentity/multiblock/IMaintenance.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
Labels: type: refactor

#1223 Fix #1210
  src/main/java/gregtech/loaders/recipe/chemistry/LCRCombined.java
Labels: type: bug

#1228 Fix hydrogen duplication exploit
  src/main/java/gregtech/loaders/recipe/chemistry/LCRCombined.java
Labels: type: bug

#1227 Attempt to automatically fetch sources and javadocs
  build.gradle.kts
Labels: ignore changelog

#1206 Fix miners mining cobblestone when overlapping working areas
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
Labels: type: bug

#1191 Fix Strangeness with Machine Facings
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SteamMetaTileEntity.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityBlockBreaker.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityTankValve.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
  src/main/resources/assets/gregtech/textures/blocks/machines/arc_furnace/overlay_back.png
  src/main/resources/assets/gregtech/textures/blocks/machines/arc_furnace/overlay_back_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/arc_furnace/overlay_back_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/arc_furnace/overlay_back_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/autoclave/overlay_back.png
  src/main/resources/assets/gregtech/textures/blocks/machines/autoclave/overlay_back_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/autoclave/overlay_back_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/autoclave/overlay_back_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/centrifuge/overlay_back.png
  src/main/resources/assets/gregtech/textures/blocks/machines/centrifuge/overlay_back_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/centrifuge/overlay_back_active.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/machines/disassembler/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/machines/disassembler/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/disassembler/overlay_front_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/disassembler/overlay_front_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/disassembler/overlay_front_paused.png
  src/main/resources/assets/gregtech/textures/blocks/machines/disassembler/overlay_front_paused_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/disassembler/overlay_top.png
  src/main/resources/assets/gregtech/textures/blocks/machines/disassembler/overlay_top_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/disassembler/overlay_top_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/disassembler/overlay_top_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/electrolyzer/overlay_back.png
  src/main/resources/assets/gregtech/textures/blocks/machines/electrolyzer/overlay_back_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/electrolyzer/overlay_back_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/electrolyzer/overlay_back_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/mixer/overlay_back.png
  src/main/resources/assets/gregtech/textures/blocks/machines/mixer/overlay_back_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/mixer/overlay_back_active.png.mcmeta
Labels: type: bug

#1187 LCR TFE fix
  src/main/java/gregtech/loaders/recipe/chemistry/PolymerRecipes.java
Labels: type: bug

#1144 Require cooling fluid for some Vacuum Freezer recipes
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/loaders/recipe/chemistry/ChemistryRecipes.java
  src/main/java/gregtech/loaders/recipe/handlers/MaterialRecipeHandler.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1226 Implement new chanced output recipe logic
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipe.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/test/java/gregtech/api/recipes/logic/ChancedOutputTest.java
  src/test/java/gregtech/api/util/TierByVoltageTest.java
Labels: type: refactor

#1150 Fix clipboard buttons not updating upon page change
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/net/NetworkHandler.java
  src/main/java/gregtech/api/net/packets/CPacketClipboardNBTUpdate.java
  src/main/java/gregtech/common/gui/impl/FakeModularUIContainerClipboard.java
  src/main/java/gregtech/common/items/behaviors/ClipboardBehavior.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
Labels: type: bug

#1135 Automatically color Machines/Pipes/Cables when placed and holding a s…
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
Labels: type: feature

#1166 Fix dupes on recipes that have a fluid container item ingredient
  src/main/java/gregtech/api/items/metaitem/stats/ItemFluidContainer.java
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/api/util/GTStringUtils.java
  src/main/java/gregtech/common/crafting/GTFluidCraftingIngredient.java
  src/main/java/gregtech/common/crafting/GTShapedNBTClearingOreRecipe.java
  src/main/java/gregtech/common/crafting/GTShapedOreRecipe.java
  src/main/java/gregtech/common/crafting/GTShapelessNBTClearingOreRecipe.java
  src/main/java/gregtech/common/crafting/GTShapelessOreRecipe.java
  src/main/java/gregtech/common/metatileentities/storage/CraftingRecipeLogic.java
Labels: type: bug

#1195 More recipe lookup work, and micro optimizations
  build.gradle.kts
  etc/CraftTweaker2-1.12-4.1.20.670.jar
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/capability/impl/EnergyContainerList.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/builders/IntCircuitRecipeBuilder.java
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipeBuilder.java
  src/main/java/gregtech/api/recipes/ingredients/CraftTweakerItemInputWrapper.java
  src/main/java/gregtech/api/recipes/ingredients/GTRecipeFluidInput.java
  src/main/java/gregtech/api/recipes/ingredients/GTRecipeInput.java
  src/main/java/gregtech/api/recipes/ingredients/GTRecipeItemInput.java
  src/main/java/gregtech/api/recipes/ingredients/GTRecipeOreInput.java
  src/main/java/gregtech/api/recipes/ingredients/IntCircuitIngredient.java
  src/main/java/gregtech/api/recipes/map/MapFluidIngredient.java
  src/main/java/gregtech/api/recipes/map/MapItemStackIngredient.java
  src/main/java/gregtech/api/recipes/map/MapItemStackNBTIngredient.java
  src/main/java/gregtech/api/util/GTHashMaps.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/OverlayedFluidHandler.java
  src/main/java/gregtech/api/util/OverlayedItemHandler.java
Labels: type: bug

#1220 Fix Z-Fighting with Covers
  src/main/java/gregtech/api/cover/ICoverable.java
  src/main/java/gregtech/api/pipenet/tile/PipeCoverableImplementation.java
  src/main/java/gregtech/client/utils/RenderUtil.java
Labels: type: bug

#1180 Add a config option for block used for replacement in miners
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
  src/main/java/gregtech/common/ConfigHolder.java
Labels: type: feature

#1229 fix small issues with maintenance tool slot
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java
Labels: type: bug

#1224 Allow Coal Coke from other mods works in PBF
  src/main/java/gregtech/loaders/OreDictionaryLoader.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
Labels: type: bug

#1230 Scale hot ingot damage by blast temperature
  src/main/java/gregtech/api/items/armor/IArmorLogic.java
  src/main/java/gregtech/api/items/materialitem/MetaPrefixItem.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/common/items/armor/NanoMuscleSuite.java
  src/main/java/gregtech/common/items/armor/QuarkTechSuite.java
Labels: type: feature

#1123 Improve Flammable Ores
  src/main/java/gregtech/common/blocks/BlockOre.java
Labels: type: feature

#1168 Swap VariantActiveBlocks to use ExtendedBlockState for the active state
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/block/UnlistedBooleanProperty.java
  src/main/java/gregtech/api/block/VariantActiveBlock.java
  src/main/java/gregtech/api/block/VariantBlock.java
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/api/pattern/TraceabilityPredicate.java
  src/main/java/gregtech/client/model/modelfactories/ActiveVariantBlockBakedModel.java
  src/main/java/gregtech/client/model/modelfactories/BakedModelHandler.java
  src/main/java/gregtech/client/renderer/texture/custom/FireboxActiveRenderer.java
  src/main/java/gregtech/common/blocks/BlockFireboxCasing.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityCokeOven.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityLargeBoiler.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityElectricBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiblockPart.java
  src/main/java/gregtech/common/metatileentities/multi/steam/MetaTileEntitySteamOven.java
  src/main/resources/assets/gregtech/blockstates/boiler_firebox_casing.json
Labels: type: bug

#1035 Add GT Fluid Blocks and Materials
  src/main/java/gregtech/api/fluids/GTFluidMaterial.java
  src/main/java/gregtech/api/fluids/MaterialFluidBlock.java
  src/main/java/gregtech/api/fluids/MetaFluids.java
  src/main/java/gregtech/api/unification/material/info/MaterialFlags.java
  src/main/java/gregtech/api/unification/material/materials/UnknownCompositionMaterials.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/client/event/FluidVisualHandler.java
  src/main/resources/assets/gregtech/textures/blocks/fluids/submerged_fluid_overlay.png
  src/main/resources/gregtech_at.cfg
Labels: type: feature

#1222 Implement Advanced Energy Detector (Remake)
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/covers/CoverBehaviors.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorEnergyAdvanced.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/metaitems/cover.energy.detector.advanced.json
  src/main/resources/assets/gregtech/textures/blocks/cover/overlay_energy_detector_advanced.png
  src/main/resources/assets/gregtech/textures/items/metaitems/cover.energy.detector_advanced.png
Labels: type: feature

#1239 Fix hard dependency on GroovyScript
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: type: bug

#1240 Fix multiblocks automatically voiding with no output bus or hatch
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
Labels: type: bug

#1243 fix server crash with fluid event handling
  src/main/java/gregtech/client/event/FluidVisualHandler.java
Labels: status: release blocker, type: bug, status: high priority
