Repository GregTechCEu/GregTech, pull requests merged in 2022-11, with the labels that each got.

#1253 fix server crash with variant active blocks.
  src/main/java/gregtech/api/block/VariantActiveBlock.java
Labels: type: bug

#1251 fix voltage display in multiblocks
  src/main/java/gregtech/api/metatileentity/multiblock/FuelMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/integration/jei/utils/JEIHelpers.java
  src/main/java/gregtech/integration/theoneprobe/provider/RecipeLogicInfoProvider.java
Labels: type: bug

#1248 Render the solid active blocks on the solid layer
  src/main/java/gregtech/api/block/VariantActiveBlock.java
  src/main/java/gregtech/client/model/modelfactories/ActiveVariantBlockBakedModel.java
  src/main/resources/assets/gregtech/textures/blocks/casings/coils/machine_coil_cupronickel.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/casings/coils/machine_coil_hssg.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/casings/coils/machine_coil_kanthal.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/casings/coils/machine_coil_naquadah.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/casings/coils/machine_coil_nichrome.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/casings/coils/machine_coil_trinium.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/casings/coils/machine_coil_tritanium.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/casings/coils/machine_coil_tungstensteel.png.mcmeta
Labels: type: bug

#1255 Yet another Crafting station fix PR
  src/main/java/gregtech/common/metatileentities/storage/CachedRecipeData.java
Labels: status: release blocker, type: bug

#1261 Fix cover input from output side on placement
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
Labels: type: bug

#1254 Fix multiblock formation oddities with Cleanroom
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
Labels: status: release blocker, type: bug, status: high priority

#1256 fix ct ingredient size mismatch causing recipe lookup failure
  src/main/java/gregtech/api/recipes/ingredients/CraftTweakerItemInputWrapper.java
Labels: status: release blocker, type: bug

#1250 fix and improve overclocking logic
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/FuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/HeatingCoilRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/PrimitiveRecipeLogic.java
  src/main/java/gregtech/api/recipes/logic/OverclockingLogic.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/test/java/gregtech/api/recipes/logic/OverclockingTest.java
Labels: status: release blocker, type: bug, status: high priority

#1241 Fix GroovyScript compat
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/crafttweaker/MetaItemBracketHandler.java
  src/main/java/gregtech/api/recipes/crafttweaker/MetaTileEntityBracketHandler.java
  src/main/java/gregtech/integration/GroovyScriptCompat.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
Labels: status: release blocker, type: bug, status: high priority

#1262 Update ru_ru.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: type: translation

#1264 Fix energy draw on special multiblocks
  src/main/java/gregtech/api/metatileentity/multiblock/FuelMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
Labels: status: release blocker, type: bug

#1263 Fix invisible laminated glass
  src/main/java/gregtech/api/block/VariantActiveBlock.java
Labels: status: release blocker, type: bug

#1265 Fix #1132
  src/main/java/gregtech/client/renderer/handler/MultiblockPreviewRenderer.java
Labels: type: bug

#1277 Soft Mallet
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1281 Modularization pt 1: Networking
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/block/BlockCustomParticle.java
  src/main/java/gregtech/api/gui/UIFactory.java
  src/main/java/gregtech/api/gui/impl/ModularUIContainer.java
  src/main/java/gregtech/api/gui/impl/ModularUIGui.java
  src/main/java/gregtech/api/items/behavior/MonitorPluginBaseBehavior.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/api/net/IPacket.java
  src/main/java/gregtech/api/net/NetworkHandler.java
  src/main/java/gregtech/api/net/PacketHandler.java
  src/main/java/gregtech/api/network/IClientExecutor.java
  src/main/java/gregtech/api/network/INetworkHandler.java
  src/main/java/gregtech/api/network/IPacket.java
  src/main/java/gregtech/api/network/IServerExecutor.java
  src/main/java/gregtech/api/util/CapesRegistry.java
  src/main/java/gregtech/api/util/ClipboardUtil.java
  src/main/java/gregtech/api/util/input/KeyBind.java
  src/main/java/gregtech/api/worldgen/bedrockFluids/BedrockFluidVeinHandler.java
  src/main/java/gregtech/common/command/CommandShaders.java
  src/main/java/gregtech/common/gui/impl/FakeModularUIContainerClipboard.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
  src/main/java/gregtech/common/terminal/app/prospector/ProspectingTexture.java
  src/main/java/gregtech/common/terminal/app/prospector/ProspectorApp.java
  src/main/java/gregtech/common/terminal/app/prospector/widget/WidgetProspectingMap.java
  src/main/java/gregtech/core/network/NetworkUtils.java
  src/main/java/gregtech/core/network/internal/NetworkHandler.java
  src/main/java/gregtech/core/network/internal/PacketHandler.java
  src/main/java/gregtech/core/network/packets/PacketBlockParticle.java
  src/main/java/gregtech/core/network/packets/PacketClipboard.java
  src/main/java/gregtech/core/network/packets/PacketClipboardNBTUpdate.java
  src/main/java/gregtech/core/network/packets/PacketClipboardUIWidgetUpdate.java
  src/main/java/gregtech/core/network/packets/PacketFluidVeinList.java
  src/main/java/gregtech/core/network/packets/PacketKeysPressed.java
  src/main/java/gregtech/core/network/packets/PacketNotifyCapeChange.java
  src/main/java/gregtech/core/network/packets/PacketPluginSynced.java
  src/main/java/gregtech/core/network/packets/PacketProspecting.java
  src/main/java/gregtech/core/network/packets/PacketRecoverMTE.java
  src/main/java/gregtech/core/network/packets/PacketReloadShaders.java
  src/main/java/gregtech/core/network/packets/PacketUIClientAction.java
  src/main/java/gregtech/core/network/packets/PacketUIOpen.java
  src/main/java/gregtech/core/network/packets/PacketUIWidgetUpdate.java
Labels: type: refactor

#1282 Modularization pt 2: Hidden modules
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/modules/GregTechModule.java
  src/main/java/gregtech/api/modules/IGregTechModule.java
  src/main/java/gregtech/api/modules/IModuleContainer.java
  src/main/java/gregtech/api/modules/IModuleManager.java
  src/main/java/gregtech/api/modules/ModuleContainerRegistryEvent.java
  src/main/java/gregtech/api/modules/ModuleStage.java
  src/main/java/gregtech/api/util/GTControlledRegistry.java
  src/main/java/gregtech/common/MetaEntities.java
  src/main/java/gregtech/common/blocks/wood/BlockRubberLeaves.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/core/network/internal/NetworkHandler.java
  src/main/java/gregtech/modules/BaseGregTechModule.java
  src/main/java/gregtech/modules/GregTechModules.java
  src/main/java/gregtech/modules/ModuleManager.java
Labels: type: refactor

#1283 Modularization pt 3: Commands
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/command/ICommandManager.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/core/command/internal/CommandManager.java
  src/main/java/gregtech/core/command/internal/GregTechCommand.java
Labels: type: refactor

#1279 Fix Parallel Recipe / by Zero Crashes
  src/main/java/gregtech/api/recipes/logic/ParallelLogic.java
Labels: type: bug

#1284 Modularization pt 4: Advancements
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/advancement/IAdvancementCriterion.java
  src/main/java/gregtech/api/advancement/IAdvancementManager.java
  src/main/java/gregtech/api/advancement/IAdvancementTrigger.java
  src/main/java/gregtech/api/capability/impl/RecipeLogicSteam.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/pipenet/tile/PipeCoverableImplementation.java
  src/main/java/gregtech/api/util/EntityDamageUtil.java
  src/main/java/gregtech/api/util/advancement/GTInstance.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/advancement/GTTriggers.java
  src/main/java/gregtech/common/advancement/criterion/BasicTrigger.java
  src/main/java/gregtech/common/advancement/criterion/TriggerDeath.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityRotorHolder.java
  src/main/java/gregtech/common/pipelike/cable/BlockCable.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/core/advancement/AdvancementTriggers.java
  src/main/java/gregtech/core/advancement/criterion/AbstractCriterion.java
  src/main/java/gregtech/core/advancement/criterion/BasicCriterion.java
  src/main/java/gregtech/core/advancement/criterion/DeathCriterion.java
  src/main/java/gregtech/core/advancement/internal/AdvancementListeners.java
  src/main/java/gregtech/core/advancement/internal/AdvancementManager.java
  src/main/java/gregtech/core/advancement/internal/AdvancementTrigger.java
Labels: type: refactor

#1285 Modularization pt 5: Sounds
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/sound/GTSoundManager.java
  src/main/java/gregtech/api/sound/GTSounds.java
  src/main/java/gregtech/api/sound/ISoundManager.java
  src/main/java/gregtech/common/entities/PortalEntity.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaTool.java
  src/main/java/gregtech/common/items/behaviors/ColorSprayBehaviour.java
  src/main/java/gregtech/common/items/behaviors/TricorderBehavior.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMiner.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityLargeBoiler.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/core/sound/GTSoundEvents.java
  src/main/java/gregtech/core/sound/internal/SoundManager.java
Labels: type: refactor

#1286 Modularization pt 6: Enchantments
  src/main/java/gregtech/api/enchants/EnchantmentData.java
  src/main/java/gregtech/api/items/toolitem/IToolStats.java
  src/main/java/gregtech/api/items/toolitem/ToolMetaItem.java
  src/main/java/gregtech/api/unification/crafttweaker/MaterialExpansion.java
  src/main/java/gregtech/api/unification/material/properties/ToolProperty.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/EventHandlers.java
  src/main/java/gregtech/common/tools/ToolButcheryKnife.java
  src/main/java/gregtech/common/tools/ToolHardHammer.java
  src/main/java/gregtech/modules/GregTechModules.java
  src/main/java/gregtech/tools/ToolsModule.java
  src/main/java/gregtech/tools/enchants/EnchantmentEnderDamage.java
  src/main/java/gregtech/tools/enchants/EnchantmentHardHammer.java
Labels: type: refactor

#1065 Fix TFC foods not replenishing saturation/hunger
  src/main/java/gregtech/api/items/armor/ArmorUtils.java
Labels: type: bug

#1298 Increase output of Primitive Pump when it is raining
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveWaterPump.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1301 Fix output overlay rendering under other overlays
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SteamMetaTileEntity.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityBlockBreaker.java
Labels: type: bug

#1296 Make muffler hatch break a snow layer
  src/main/java/gregtech/api/capability/impl/RecipeLogicSteam.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
Labels: type: feature

#1302 Energy Converter fixes
  src/main/java/gregtech/api/capability/FeCompat.java
  src/main/java/gregtech/common/metatileentities/converter/ConverterTrait.java
  src/main/java/gregtech/integration/theoneprobe/provider/ConverterInfoProvider.java
Labels: type: bug

#1288 Implement Creative Energy Emitter IO/sec Label
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeEnergy.java
Labels: type: bug

#633 Move polymer names away from lang
  src/main/java/gregtech/api/unification/crafttweaker/CTMaterialBuilder.java
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/materials/OrganicChemistryMaterials.java
  src/main/java/gregtech/api/unification/material/properties/PolymerProperty.java
  src/main/java/gregtech/api/unification/material/properties/PropertyKey.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/api/util/GTControlledRegistry.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/test/java/gregtech/Bootstrap.java
Labels: type: feature

#1297 Fix crash with Console Terminal App
  src/main/java/gregtech/api/terminal/gui/widgets/MachineSceneWidget.java
Labels: type: bug

#1307 Fix some log warnings after polymer PR
  src/main/java/gregtech/api/unification/material/properties/PolymerProperty.java
Labels: ignore changelog

#1308 Update ru_ru.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: type: translation

#1274 Early game circuit recipe tweaks (Steam - LV - MV)
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/loaders/recipe/CircuitRecipes.java
Labels: type: feature
