Repository GregTechCEu/GregTech, pull requests merged in 2022-09, with the labels that each got.

#1174 Add description to teleporter app
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: bug

#1176 Fix an oversight in cleanroom progression
  src/main/java/gregtech/loaders/recipe/CircuitRecipes.java
Labels: type: bug

#1164 Fixes valid recipes disappearing from JEI
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: status: release blocker, type: bug

#1182 Fix Recipe Logic not Validating Cached Recipe Voltage Before Running
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
Labels: type: bug

#1185 Configurable maintenance fix
  src/main/java/gregtech/api/capability/impl/HeatingCoilRecipeLogic.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
Labels: type: bug

#1198 Speed Up CI and Jar Builds
  .github/workflows/curseforge_release.yml
  .github/workflows/github_release.yml
  .github/workflows/pr.yml
  .github/workflows/pr_enforce_labels.yml
  build.gradle.kts
Labels: ignore changelog

#1192 Nothirium compat
  src/main/java/gregtech/client/utils/BloomEffectUtil.java
Labels: type: bug

#1162 Fix obstructed Boiler does not decrease heat
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityLargeBoiler.java
Labels: type: bug

#1165 Use the chestWood OreDict for Recipe Inputs
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
Labels: type: feature

#1183 Relax itemstack matching on the crafting result for recipes that add NBT data to their outputs
  src/main/java/gregtech/common/gui/widget/craftingstation/CraftingSlotWidget.java
  src/main/java/gregtech/common/metatileentities/storage/CachedRecipeData.java
  src/main/java/gregtech/common/metatileentities/storage/CraftingRecipeLogic.java
Labels: type: bug

#1197 Make Covers return modified NBT after writing
  src/main/java/gregtech/api/cover/CoverBehavior.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverCraftingTable.java
  src/main/java/gregtech/common/covers/CoverDigitalInterface.java
  src/main/java/gregtech/common/covers/CoverDigitalInterfaceWireless.java
  src/main/java/gregtech/common/covers/CoverEnderFluidLink.java
  src/main/java/gregtech/common/covers/CoverFacade.java
  src/main/java/gregtech/common/covers/CoverFluidFilter.java
  src/main/java/gregtech/common/covers/CoverFluidRegulator.java
  src/main/java/gregtech/common/covers/CoverFluidVoidingAdvanced.java
  src/main/java/gregtech/common/covers/CoverItemFilter.java
  src/main/java/gregtech/common/covers/CoverItemVoidingAdvanced.java
  src/main/java/gregtech/common/covers/CoverMachineController.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/covers/CoverRoboticArm.java
  src/main/java/gregtech/common/covers/CoverShutter.java
  src/main/java/gregtech/common/covers/detector/CoverActivityDetector.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorEnergy.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorFluid.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorItem.java
Labels: type: refactor

#1152 Useable Circuit Slot For Recipes
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
Labels: type: feature

#1207 Only show ores whose stone types should be dropped on Prospector map
  src/main/java/gregtech/common/terminal/app/prospector/widget/WidgetProspectingMap.java
Labels: type: feature
