Repository GregTechCEu/GregTech, pull requests merged in 2022-12, with the labels that each got.

#1294 FIx ActiveVariantBlockBakedModel and VariantActiveBlock NPE crashes
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/client/model/modelfactories/ActiveVariantBlockBakedModel.java
Labels: type: bug

#1312 Make Assembly Line Recipes Less Confusing
  src/main/java/gregtech/loaders/recipe/AssemblyLineLoader.java
Labels: type: feature

#1314 add animated overlay for the lathe
  src/main/resources/assets/gregtech/textures/blocks/machines/lathe/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/lathe/overlay_front_active.png.mcmeta
Labels: type: feature

#1321 fix strange fluid temperatures
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/OrganicChemistryMaterials.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
Labels: type: bug

#1325 remove unneeded (and unfunctional) AE2 rendering compat
  src/main/java/gregtech/api/util/ModCompatibility.java
Labels: type: refactor

#1322 Improve Logging
  src/main/java/gregtech/api/cover/ICoverable.java
  src/main/java/gregtech/api/gui/widgets/PhantomFluidWidget.java
  src/main/java/gregtech/api/items/armor/ArmorUtils.java
  src/main/java/gregtech/api/items/gui/PlayerInventoryUIFactory.java
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/api/terminal/os/TerminalDialogWidget.java
  src/main/java/gregtech/api/terminal/os/TerminalOSWidget.java
  src/main/java/gregtech/api/unification/crafttweaker/CTMaterialHelpers.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/StreamUtils.java
  src/main/java/gregtech/asm/util/ObfMapping.java
  src/main/java/gregtech/client/model/customtexture/CustomTextureBakedModel.java
  src/main/java/gregtech/client/model/customtexture/CustomTextureModel.java
  src/main/java/gregtech/common/covers/CoverDigitalInterface.java
  src/main/java/gregtech/common/gui/widget/monitor/WidgetCoverList.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
  src/main/java/gregtech/common/metatileentities/multi/electric/centralmonitor/MetaTileEntityMonitorScreen.java
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
  src/main/java/gregtech/modules/ModuleManager.java
Labels: type: refactor

#1319 Wooden Crate Recipe in Assembler broken
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
Labels: type: bug

#1318 Update some GUI asset names for texture packs
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/resources/assets/gregtech/textures/gui/widget/button_fluid_output_overlay.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_item_output_overlay.png
Labels: type: bug

#1327 add tooltip to circuit slot saying it is valid for recipe inputs
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1269 fix same recipes instances being added to JEI more than once
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: type: bug

#1320 add docs and annotations for many recipe logic classes
  src/main/java/gregtech/api/capability/IControllable.java
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/FuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/PrimitiveRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/SteamMultiWorkable.java
  src/main/java/gregtech/api/capability/impl/SteamMultiblockRecipeLogic.java
  src/main/java/gregtech/api/recipes/logic/IParallelableRecipeLogic.java
  src/main/java/gregtech/api/recipes/logic/ParallelLogic.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiSmelter.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
Labels: type: refactor

#1305 Fix Miners forming the list of blocks to mine incorrectly
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMiner.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
Labels: type: bug

#1275 Set Energy Hatch limit to 2 (from 3) in Multiblocks
  src/main/java/gregtech/api/metatileentity/multiblock/MultiMapMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDistillationTower.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/common/metatileentities/multi/electric/centralmonitor/MetaTileEntityCentralMonitor.java
Labels: type: feature

#1276 Split harder iron recipes into 2 configs
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/loaders/recipe/VanillaOverrideRecipes.java
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
Labels: type: feature

#1328 Update ja_jp.lang
  src/main/resources/assets/gregtech/lang/ja_jp.lang
Labels: type: translation

#1332 Decouple parallel voltage from overclock and recipe search voltage
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
Labels: type: refactor

#1249 Give frames a sound when placed vertically
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/common/blocks/BlockFrame.java
Labels: type: bug

#1299 Allow pipes in frames in multiblock structures
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveWaterPump.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
Labels: type: feature

#1311 Fix name mold recipes in forming press not working
  src/main/java/gregtech/api/recipes/machines/RecipeMapFormingPress.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: bug

#1331 Update JUnit and use Hamcrest assertions
  build.gradle.kts
  src/test/java/gregtech/Bootstrap.java
  src/test/java/gregtech/api/capability/impl/AbstractRecipeLogicTest.java
  src/test/java/gregtech/api/capability/impl/MultiblockRecipeLogicTest.java
  src/test/java/gregtech/api/recipes/RecipeMapTest.java
  src/test/java/gregtech/api/recipes/logic/ChancedOutputTest.java
  src/test/java/gregtech/api/recipes/logic/IParallelableRecipeLogicTest.java
  src/test/java/gregtech/api/recipes/logic/OverclockingTest.java
  src/test/java/gregtech/api/recipes/logic/ParallelLogicTest.java
  src/test/java/gregtech/api/recipes/recipeproperties/RecipePropertyStorageTest.java
  src/test/java/gregtech/api/util/InventoryUtilsTest.java
  src/test/java/gregtech/api/util/TierByVoltageTest.java
  src/test/java/gregtech/client/I18nTest.java
  src/test/java/gregtech/common/covers/CoverFluidRegulatorTest.java
  src/test/java/gregtech/common/metatileentities/converter/ConverterTraitTest.java
Labels: ignore changelog

#1317 Fix chanced output boost not being applied to multiblocks
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
Labels: type: bug

#1345 Fix CI releases™™™™™™™™™™™
  .github/workflows/curseforge_release.yml
  .github/workflows/github_release.yml
Labels: ignore changelog

#1347 isolate RotorStats from ToolStats
  src/main/java/gregtech/api/unification/crafttweaker/CTMaterialBuilder.java
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/HigherDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/properties/PropertyKey.java
  src/main/java/gregtech/api/unification/material/properties/RotorProperty.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/common/items/behaviors/TurbineRotorBehavior.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityRotorHolder.java
Labels: type: feature
