Repository GregTechCEu/GregTech, pull requests merged in 2022-02, with the labels that each got.

#616 Fix ore dict filter crash on server
  src/main/java/gregtech/api/gui/widgets/OreDictFilterTestSlot.java
Labels: release priority

#606 Fix Steam recipe duration
  src/main/java/gregtech/api/capability/impl/RecipeLogicSteam.java
Labels: release priority

#578 Creative Chest/Tank fix
  src/main/java/gregtech/api/gui/widgets/PhantomSlotWidget.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeTank.java
Labels: high priority

#502 Crafting station fixes
  src/main/java/gregtech/api/gui/widgets/CraftingStationInputWidgetGroup.java
  src/main/java/gregtech/api/gui/widgets/PhantomSlotWidget.java
  src/main/java/gregtech/api/storage/ICraftingStorage.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/SlotUtil.java
  src/main/java/gregtech/common/covers/CoverCraftingTable.java
  src/main/java/gregtech/common/gui/widget/craftingstation/CraftingSlotWidget.java
  src/main/java/gregtech/common/gui/widget/craftingstation/ItemListGridWidget.java
  src/main/java/gregtech/common/gui/widget/craftingstation/ItemListSlotWidget.java
  src/main/java/gregtech/common/gui/widget/craftingstation/MemorizedRecipeWidget.java
  src/main/java/gregtech/common/inventory/IItemList.java
  src/main/java/gregtech/common/inventory/itemsource/ItemSource.java
  src/main/java/gregtech/common/inventory/itemsource/ItemSourceList.java
  src/main/java/gregtech/common/inventory/itemsource/ItemSources.java
  src/main/java/gregtech/common/inventory/itemsource/NetworkItemInfo.java
  src/main/java/gregtech/common/inventory/itemsource/sources/InventoryItemSource.java
  src/main/java/gregtech/common/inventory/itemsource/sources/TileItemSource.java
  src/main/java/gregtech/common/metatileentities/storage/CachedRecipeData.java
  src/main/java/gregtech/common/metatileentities/storage/CraftingRecipeLogic.java
  src/main/java/gregtech/common/metatileentities/storage/CraftingRecipeMemory.java
  src/main/java/gregtech/common/metatileentities/storage/CraftingRecipeResolver.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
Labels: high priority

#610 Fix a bunch of recipe conflicts
  src/main/java/gregtech/loaders/recipe/chemistry/AcidRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/FuelRecipeChains.java
  src/main/java/gregtech/loaders/recipe/chemistry/PolymerRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/ReactorRecipes.java
  src/main/java/gregtech/loaders/recipe/handlers/OreRecipeHandler.java
Labels: high priority

#650 Update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: high priority

#329 allow recipes to have non consumables with stack size bigger than 1
  src/main/java/gregtech/api/metatileentity/WorkableTieredMetaTileEntity.java
  src/main/java/gregtech/api/recipes/CountableIngredient.java
  src/main/java/gregtech/api/recipes/FluidKey.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/builders/IntCircuitRecipeBuilder.java
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipeBuilder.java
  src/main/java/gregtech/api/recipes/logic/ParallelLogic.java
  src/main/java/gregtech/api/util/IngredientHashStrategy.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/integration/jei/recipe/RecipeMapCategory.java
  src/test/java/gregtech/api/recipes/RecipeMapTest.java
Labels: high priority

#663 Fix delay with GUI taking too long to open
  src/main/java/gregtech/api/gui/impl/ModularUIGui.java
Labels: high priority

#621 Grab default meta when meta exceeds allowed values for meta blocks
  src/main/java/gregtech/common/blocks/BlockCompressed.java
  src/main/java/gregtech/common/blocks/BlockFrame.java
  src/main/java/gregtech/common/blocks/BlockOre.java
Labels: high priority

#542 Rework Metafluids
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/fluids/MaterialFluid.java
  src/main/java/gregtech/api/fluids/MetaFluids.java
  src/main/java/gregtech/api/fluids/fluidType/FluidType.java
  src/main/java/gregtech/api/fluids/fluidType/FluidTypeAcid.java
  src/main/java/gregtech/api/fluids/fluidType/FluidTypeGas.java
  src/main/java/gregtech/api/fluids/fluidType/FluidTypeLiquid.java
  src/main/java/gregtech/api/fluids/fluidType/FluidTypePlasma.java
  src/main/java/gregtech/api/fluids/fluidType/FluidTypes.java
  src/main/java/gregtech/api/gui/widgets/TankWidget.java
  src/main/java/gregtech/api/unification/crafttweaker/CTMaterialBuilder.java
  src/main/java/gregtech/api/unification/crafttweaker/CTMaterialHelpers.java
  src/main/java/gregtech/api/unification/crafttweaker/MaterialPropertyExpansion.java
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/OrganicChemistryMaterials.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/UnknownCompositionMaterials.java
  src/main/java/gregtech/api/unification/material/properties/FluidProperty.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/api/util/FluidTooltipUtil.java
  src/main/java/gregtech/api/util/LocalizationUtils.java
  src/main/java/gregtech/api/worldgen/populator/SurfaceRockPopulator.java
  src/main/java/gregtech/client/ClientProxy.java
  src/main/java/gregtech/common/MetaFluids.java
  src/main/java/gregtech/core/hooks/JEIHooks.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/test/java/gregtech/Bootstrap.java
Labels: high priority

#675 fix problems with chanced outputs in jei
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/integration/jei/recipe/RecipeMapCategory.java
Labels: status: release blocker, high priority

#604 Energy Conversion
  src/main/java/gregtech/api/capability/FeCompat.java
  src/main/java/gregtech/api/capability/GregtechCapabilities.java
  src/main/java/gregtech/api/capability/SimpleCapabilityManager.java
  src/main/java/gregtech/api/capability/impl/CapabilityCompatProvider.java
  src/main/java/gregtech/api/capability/impl/EUToFEProvider.java
  src/main/java/gregtech/api/capability/impl/EnergyContainerBatteryBuffer.java
  src/main/java/gregtech/api/capability/impl/EnergyContainerBatteryCharger.java
  src/main/java/gregtech/api/capability/impl/EnergyContainerHandler.java
  src/main/java/gregtech/api/capability/impl/GTEnergyWrapper.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/covers/CoverDigitalInterface.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/converter/ConverterTrait.java
  src/main/java/gregtech/common/metatileentities/converter/MetaTileEntityConverter.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeCompatibility.java
  src/main/java/gregtech/integration/theoneprobe/provider/ConverterInfoProvider.java
  src/main/java/gregtech/loaders/recipe/CraftingComponent.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/overlay/converter/converter_fe_in.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/converter/converter_fe_out.png
  src/test/java/gregtech/common/metatileentities/converter/ConverterTraitTest.java
Labels: high priority

#559 Voiding Logic Rework
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/SteamMultiWorkable.java
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/java/gregtech/api/gui/widgets/ImageCycleButtonWidget.java
  src/main/java/gregtech/api/metatileentity/IVoidable.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SimpleGeneratorMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipe.java
  src/main/java/gregtech/api/recipes/logic/IParallelableRecipeLogic.java
  src/main/java/gregtech/api/recipes/logic/ParallelLogic.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMacerator.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDistillationTower.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/LargeTurbineWorkableHandler.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
  src/main/java/gregtech/common/metatileentities/multi/steam/MetaTileEntitySteamGrinder.java
  src/main/java/gregtech/common/metatileentities/multi/steam/MetaTileEntitySteamOven.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/gui/widget/button_void_multiblock.png
  src/test/java/gregtech/api/recipes/logic/IParallelableRecipeLogicTest.java
Labels: high priority
