Repository GregTechCEu/GregTech, pull requests merged in 2023-07, with the labels that each got.

#1893 Fix incorrect packet reading
  src/main/java/gregtech/api/metatileentity/SyncedTileEntityBase.java
Labels: ignore changelog

#1897 Localize sound subtitles
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/sounds.json
Labels: ignore changelog

#1902 Mark buildscript update branches with automerge
  .github/workflows/update_buildscript.yml
Labels: ignore changelog

#1903 Update build script version to 1688526754
  build.gradle
Labels: ignore changelog

#1904 Revert "Improve TE Networking Performance (#1883)"
  src/main/java/gregtech/api/metatileentity/SyncedTileEntityBase.java
Labels: ignore changelog

#1323 Long Distance pipes
  src/main/java/gregtech/api/pipenet/longdist/BlockLongDistancePipe.java
  src/main/java/gregtech/api/pipenet/longdist/ILDEndpoint.java
  src/main/java/gregtech/api/pipenet/longdist/LongDistanceNetwork.java
  src/main/java/gregtech/api/pipenet/longdist/LongDistancePipeType.java
  src/main/java/gregtech/api/pipenet/longdist/NetworkBuilder.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/client/renderer/texture/cube/AlignedOrientedOverlayRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/OrientedOverlayRenderer.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/EventHandlers.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityLongDistanceEndpoint.java
  src/main/java/gregtech/common/pipelike/fluidpipe/longdistance/LDFluidPipeType.java
  src/main/java/gregtech/common/pipelike/fluidpipe/longdistance/MetaTileEntityLDFluidEndpoint.java
  src/main/java/gregtech/common/pipelike/itempipe/longdistance/LDItemPipeType.java
  src/main/java/gregtech/common/pipelike/itempipe/longdistance/MetaTileEntityLDItemEndpoint.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeModule.java
  src/main/java/gregtech/integration/theoneprobe/provider/LDPipeProvider.java
  src/main/java/gregtech/loaders/MaterialInfoLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
  src/main/resources/assets/gregtech/blockstates/ld_fluid_pipe.json
  src/main/resources/assets/gregtech/blockstates/ld_item_pipe.json
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_fluid_pipe/block.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_fluid_pipe/overlay_bottom.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_fluid_pipe/overlay_bottom_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_fluid_pipe/overlay_side.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_fluid_pipe/overlay_side_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_fluid_pipe/overlay_top.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_fluid_pipe/overlay_top_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_item_pipe/block.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_item_pipe/overlay_bottom.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_item_pipe/overlay_bottom_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_item_pipe/overlay_side.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_item_pipe/overlay_side_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_item_pipe/overlay_top.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/ld_item_pipe/overlay_top_emissive.png
Labels: type: feature, status: high priority

#1907 Update build script version to 1688620665
  build.gradle
Labels: ignore changelog

#1909 Fix Turbines crashing with Quad/Nonuple Hatches
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/LargeTurbineWorkableHandler.java
Labels: type: refactor

#1720 ME Hatch/Bus
  dependencies.gradle
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/java/gregtech/api/gui/widgets/PhantomFluidWidget.java
  src/main/java/gregtech/api/gui/widgets/PhantomTankWidget.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/gui/widget/appeng/AEConfigWidget.java
  src/main/java/gregtech/common/gui/widget/appeng/AEFluidConfigWidget.java
  src/main/java/gregtech/common/gui/widget/appeng/AEFluidGridWidget.java
  src/main/java/gregtech/common/gui/widget/appeng/AEItemConfigWidget.java
  src/main/java/gregtech/common/gui/widget/appeng/AEItemGridWidget.java
  src/main/java/gregtech/common/gui/widget/appeng/AEListGridWidget.java
  src/main/java/gregtech/common/gui/widget/appeng/slot/AEConfigSlot.java
  src/main/java/gregtech/common/gui/widget/appeng/slot/AEFluidConfigSlot.java
  src/main/java/gregtech/common/gui/widget/appeng/slot/AEFluidDisplayWidget.java
  src/main/java/gregtech/common/gui/widget/appeng/slot/AEItemConfigSlot.java
  src/main/java/gregtech/common/gui/widget/appeng/slot/AEItemDisplayWidget.java
  src/main/java/gregtech/common/gui/widget/appeng/slot/AmountSetSlot.java
  src/main/java/gregtech/common/inventory/appeng/SerializableFluidList.java
  src/main/java/gregtech/common/inventory/appeng/SerializableItemList.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiblockNotifiablePart.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/ExportOnlyAESlot.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/IConfigurableSlot.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityAEHostablePart.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEOutputBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEOutputHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/stack/WrappedFluidStack.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/stack/WrappedItemStack.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/overlay/appeng/me_input_bus.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/appeng/me_input_hatch.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/appeng/me_output_bus.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/appeng/me_output_hatch.png
  src/main/resources/assets/gregtech/textures/gui/widget/config_arrow.png
  src/main/resources/assets/gregtech/textures/gui/widget/config_arrow_dark.png
  src/main/resources/assets/gregtech/textures/gui/widget/number_background.png
  src/main/resources/assets/gregtech/textures/gui/widget/select_box.png
Labels: type: feature

#1905 Add a config for special events
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/common/ConfigHolder.java
Labels: type: feature

#1910 My changes to sb-multiblock-ux
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/multiblock/FuelMultiblockController.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: ignore changelog

#1906 New Multiblock UI
  src/main/java/gregtech/api/capability/IDistinctBusController.java
  src/main/java/gregtech/api/capability/IMultipleRecipeMaps.java
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/miner/MultiblockMinerLogic.java
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/java/gregtech/api/gui/resources/SteamTexture.java
  src/main/java/gregtech/api/gui/widgets/ImageCycleButtonWidget.java
  src/main/java/gregtech/api/gui/widgets/IndicatorImageWidget.java
  src/main/java/gregtech/api/metatileentity/multiblock/FuelMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiMapMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapSteamMultiblockController.java
  src/main/java/gregtech/client/event/ClientEventHandler.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityLargeBoiler.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPowerSubstation.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeCombustionEngine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/gui/base/display.png
  src/main/resources/assets/gregtech/textures/gui/icon/gregtech_logo_blinking_red.png
  src/main/resources/assets/gregtech/textures/gui/icon/gregtech_logo_blinking_yellow.png
  src/main/resources/assets/gregtech/textures/gui/icon/gregtech_logo_dark.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_chunk_mode.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_distinct_buses.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_miner_modes.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_multi_map.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_no_distinct_buses.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_no_flex.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_power.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_power_detail.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_silk_touch_mode.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_throttle_minus.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_throttle_plus.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_void.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_void_none.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_void_partial.png
Labels: type: feature

#1800 Fix Quantum Chest item voiding
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
Labels: type: bug

#1911 Format duration in JEI better
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1895 fix MetaItemBracketHandler
  src/main/java/gregtech/integration/crafttweaker/CraftTweakerModule.java
  src/main/java/gregtech/integration/crafttweaker/recipe/MetaItemBracketHandler.java
Labels: ignore changelog

#1843 Allow Miner Logic to be Reset by Machine Controller or Soft Mallet
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
Labels: type: feature

#1646 Add ghost circuit slots to item input buses
  src/main/java/gregtech/api/capability/IGhostSlotConfigurable.java
  src/main/java/gregtech/api/capability/impl/ItemHandlerList.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/common/items/behaviors/IntCircuitBehaviour.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/steam/multiblockpart/MetaTileEntitySteamItemBus.java
  src/test/java/gregtech/api/capability/impl/MultiblockRecipeLogicTest.java
Labels: type: feature

#1879 Baubles compat, rewrite Item Magnet logic
  dependencies.gradle
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/items/metaitem/ElectricStats.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/behaviors/ItemMagnetBehavior.java
  src/main/java/gregtech/integration/baubles/BaubleBehavior.java
  src/main/java/gregtech/integration/baubles/BaublesModule.java
  src/main/java/gregtech/integration/baubles/BaublesWrappedInventory.java
  src/main/java/gregtech/modules/GregTechModules.java
  src/main/resources/gregtech_at.cfg
Labels: type: feature

#1912 Fix Converter Capabilty returning Null in certain situations
  src/main/java/gregtech/common/metatileentities/converter/MetaTileEntityConverter.java
Labels: type: bug

#1899 Add Filtering to Pump Machines
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityPump.java
Labels: type: feature

#1913 Fix Multi Input Hatches leaving FluidStacks of 0L
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiFluidHatch.java
Labels: ignore changelog

#1752 Allow filtering output hatches
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityFluidHatch.java
Labels: type: feature

#1915 Fix fluid name on tank GUI depending on server locale
  src/main/java/gregtech/api/gui/widgets/PhantomTankWidget.java
  src/main/java/gregtech/api/gui/widgets/TankWidget.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityPump.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityFluidHatch.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: type: bug

#1914 Add Needs Maintenance Cover
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/covers/CoverBehaviors.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorMaintenance.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/metaitems/cover.maintenance.detector.json
  src/main/resources/assets/gregtech/textures/blocks/cover/overlay_maintenance_detector.png
  src/main/resources/assets/gregtech/textures/items/metaitems/cover.maintenance.detector.png
Labels: type: feature

#1900 Lasers & Active Transformer
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/capability/GregtechTileCapabilities.java
  src/main/java/gregtech/api/capability/ILaserContainer.java
  src/main/java/gregtech/api/capability/SimpleCapabilityManager.java
  src/main/java/gregtech/api/capability/impl/ActiveTransformerWrapper.java
  src/main/java/gregtech/api/capability/impl/EnergyContainerList.java
  src/main/java/gregtech/api/capability/impl/LaserContainerList.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockAbility.java
  src/main/java/gregtech/api/pipenet/PipeNetWalker.java
  src/main/java/gregtech/client/ClientProxy.java
  src/main/java/gregtech/client/renderer/pipe/LaserPipeRenderer.java
  src/main/java/gregtech/client/renderer/pipe/OpticalPipeRenderer.java
  src/main/java/gregtech/client/renderer/pipe/PipeRenderer.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityActiveTransformer.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityLaserHatch.java
  src/main/java/gregtech/common/pipelike/laser/BlockLaserPipe.java
  src/main/java/gregtech/common/pipelike/laser/ItemBlockLaserPipe.java
  src/main/java/gregtech/common/pipelike/laser/LaserPipeProperties.java
  src/main/java/gregtech/common/pipelike/laser/LaserPipeType.java
  src/main/java/gregtech/common/pipelike/laser/net/LaserNetHandler.java
  src/main/java/gregtech/common/pipelike/laser/net/LaserNetWalker.java
  src/main/java/gregtech/common/pipelike/laser/net/LaserPipeNet.java
  src/main/java/gregtech/common/pipelike/laser/net/WorldLaserPipeNet.java
  src/main/java/gregtech/common/pipelike/laser/tile/TileEntityLaserPipe.java
  src/main/resources/assets/gregtech/blockstates/laser_pipe_normal.json
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_laser_source.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_laser_target.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/pipe_laser_in.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/pipe_laser_side.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/pipe_laser_side_overlay.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/pipe_laser_side_overlay_emissive.png
Labels: type: feature

#1919 Fix NBTMatcher checks not checking boolean keys
  src/main/java/gregtech/api/recipes/ingredients/nbtmatch/NBTMatcher.java
Labels: type: bug

#1922 Show items as blocked from removal in machine hatch when running
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMachineHatch.java
Labels: type: feature

#1851 Add method to register a set of custom MetaTileEntities
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
Labels: type: refactor

#1894 Rebalance maintenance
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDataBank.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityHPCA.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPowerSubstation.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: bug

#1925 fix GRS metaitem bracket handler
  src/main/java/gregtech/integration/groovy/GroovyScriptModule.java
Labels: ignore changelog

#1924 fix tool repair item tooltip
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
Labels: type: bug

#1921 Recipes for 2.7
  src/main/java/gregtech/api/recipes/builders/AssemblyLineRecipeBuilder.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/util/AssemblyLineManager.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityLaserHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityOpticalDataHatch.java
  src/main/java/gregtech/loaders/recipe/AssemblyLineLoader.java
  src/main/java/gregtech/loaders/recipe/BatteryRecipes.java
  src/main/java/gregtech/loaders/recipe/CircuitRecipes.java
  src/main/java/gregtech/loaders/recipe/ComponentRecipes.java
  src/main/java/gregtech/loaders/recipe/ComputerRecipes.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/ReactorRecipes.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: ignore changelog

#1927 Fix fuel logic EUt
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/FuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/api/recipes/builders/FuelRecipeBuilder.java
Labels: type: bug

#1932 Laser fix
  src/main/java/gregtech/api/capability/ILaserContainer.java
  src/main/java/gregtech/api/capability/impl/ActiveTransformerWrapper.java
  src/main/java/gregtech/api/capability/impl/LaserContainerList.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityLaserHatch.java
  src/main/java/gregtech/common/pipelike/laser/net/LaserNetHandler.java
  src/main/java/gregtech/common/pipelike/laser/tile/TileEntityLaserPipe.java
Labels: type: bug, ignore changelog

#1936 Update build script version to 1689212657
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ignore changelog

#1935 Fix various issues in 2.7
  src/main/java/gregtech/api/pipenet/block/material/BlockMaterialPipe.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityActiveTransformer.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDataBank.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityDataAccessHatch.java
  src/main/java/gregtech/common/pipelike/cable/BlockCable.java
  src/main/java/gregtech/common/pipelike/fluidpipe/BlockFluidPipe.java
  src/main/java/gregtech/common/pipelike/itempipe/BlockItemPipe.java
  src/main/java/gregtech/loaders/recipe/ComputerRecipes.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: bug

#1928 fix info provider inaccuracy with boosted EUt
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/FuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/WorkableTieredMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/multiblock/FuelMultiblockController.java
  src/main/java/gregtech/integration/hwyla/provider/RecipeLogicDataProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/RecipeLogicInfoProvider.java
Labels: type: bug

#1929 Fix fluid veins being lost when switching OS
  src/main/java/gregtech/api/util/FileUtility.java
  src/main/java/gregtech/api/worldgen/bedrockFluids/BedrockFluidVeinHandler.java
  src/main/java/gregtech/api/worldgen/config/BedrockFluidDepositDefinition.java
  src/main/java/gregtech/api/worldgen/config/IWorldgenDefinition.java
  src/main/java/gregtech/api/worldgen/config/OreDepositDefinition.java
  src/main/java/gregtech/api/worldgen/config/WorldGenRegistry.java
Labels: type: bug

#1940 Fix Drum Recipes
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
Labels: type: bug

#1946 Fix issue saving the scanned prospector map
  src/main/java/gregtech/common/terminal/app/prospector/ProspectorApp.java
Labels: type: bug

#1941 fix server crash with groovyscript multiblocks
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
Labels: type: bug

#1938 Allow recipe properties access to IRecipeWrapper#getTooltipStrings
  src/main/java/gregtech/api/recipes/recipeproperties/RecipeProperty.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
Labels: type: feature

#1942 Autogenerate Wood Pipe recipes
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/AssemblerRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/handlers/PipeRecipeHandler.java
Labels: type: bug

#1947 Minor tooltip fixes
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: bug

#1948 Fix Arc Furnace recycling for some materials
  src/main/java/gregtech/loaders/recipe/RecyclingRecipes.java
Labels: type: bug

#1949 fix multi smelter using too much energy
  src/main/java/gregtech/api/recipes/machines/RecipeMapFurnace.java
  src/main/java/gregtech/common/blocks/BlockWireCoil.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiSmelter.java
Labels: type: bug

#1951 Fix format duration time in JEI in multilanguages
  src/main/resources/assets/gregtech/lang/ja_jp.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#1956 Fix transformers limiting amperage
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityTransformer.java
Labels: type: bug

#1952 Fix Magnetic Tools ignoring Void Satchels
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: type: bug

#1953 LD Pipe Fix
  src/main/java/gregtech/api/pipenet/longdist/LongDistanceNetwork.java
  src/main/java/gregtech/api/pipenet/longdist/LongDistancePipeType.java
  src/main/java/gregtech/integration/theoneprobe/provider/LDPipeProvider.java
Labels: type: bug

#1954 Improve ghost circuit slot
  src/main/java/gregtech/api/gui/widgets/GhostCircuitSlotWidget.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1958 fix machine explosions sometimes dropping the block
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/hpca/MetaTileEntityHPCAComponent.java
Labels: type: bug

#1964 Fix issue with CraftTweaker materials
  src/main/java/gregtech/integration/crafttweaker/material/CTMaterialHelpers.java
Labels: type: bug

#1961 Fix Miner Logic not resetting when finished
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
Labels: type: bug, ignore changelog

#1966 Fix tools tab missing search bar
  src/main/java/gregtech/api/GregTechAPI.java
Labels: type: bug

#1960 Fix issue with baubles wrapped inventory
  src/main/java/gregtech/integration/baubles/BaublesWrappedInventory.java
Labels: type: bug

#1965 Fix tool durability issues
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
Labels: type: bug

#1969 Adjust Wood Pipe Recipes
  src/main/java/gregtech/loaders/recipe/handlers/PipeRecipeHandler.java
Labels: ignore changelog

#1975 Fix bedrock fluid vein sizes
  src/main/java/gregtech/api/worldgen/bedrockFluids/BedrockFluidVeinHandler.java
  src/main/java/gregtech/api/worldgen/bedrockFluids/BedrockFluidVeinSaveData.java
  src/main/java/gregtech/core/CoreModule.java
Labels: type: bug

#1972 Update build script version to 1689976122
  build.gradle
Labels: ignore changelog

#1978 Fix fluid pipes from vanilla materials
  src/main/java/gregtech/loaders/recipe/handlers/PipeRecipeHandler.java
Labels: type: bug

#1979 Add a tooltip for discharge mode
  src/main/java/gregtech/api/items/metaitem/ElectricStats.java
Labels: type: feature

#1974 Allow material blocks to be burned
  src/main/java/gregtech/api/unification/material/materials/UnknownCompositionMaterials.java
  src/main/java/gregtech/api/unification/material/properties/WoodProperty.java
  src/main/java/gregtech/common/blocks/BlockMaterialBase.java
Labels: type: feature

#1973 Fix Super/Qauntum Tanks losing Locked status
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: type: bug

#1982 Fix TextFieldWidget server-side classloading issue
  src/main/java/gregtech/api/gui/widgets/TextFieldWidget.java
  src/main/java/gregtech/api/util/MCGuiUtil.java
Labels: type: bug

#1980 Make recipe check command also check for recipes with empty inputs
  src/main/java/gregtech/common/command/CommandRecipeCheck.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1986 fix groovyscript metaitem handler
  src/main/java/gregtech/integration/groovy/GroovyScriptModule.java
Labels: type: bug, integration: GrS

#1987 Add a proper harvest tool and level to power substation batteries
  src/main/java/gregtech/common/blocks/BlockBatteryPart.java
Labels: type: bug

#1984 Fix perfect OC getting stuck at 2 or 3 ticks
  src/main/java/gregtech/api/recipes/logic/OverclockingLogic.java
Labels: type: bug

#1957 Further Improve Ghost Circuit Slot
  src/main/java/gregtech/api/gui/widgets/GhostCircuitSlotWidget.java
  src/main/java/gregtech/api/gui/widgets/SlotWidget.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/common/items/behaviors/IntCircuitBehaviour.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1990 Fix Silk Touch Ore Drops
  src/main/java/gregtech/common/blocks/BlockOre.java
Labels: type: bug

#1989 Add missing FML stages to modules
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/modules/IGregTechModule.java
  src/main/java/gregtech/api/modules/ModuleStage.java
  src/main/java/gregtech/modules/ModuleManager.java
Labels: type: refactor

#1988 Fix Ultimate Battery CWU/t
  src/main/java/gregtech/loaders/recipe/BatteryRecipes.java
Labels: ignore changelog

#1995 fix iron door recipes and recycling
  src/main/java/gregtech/loaders/MaterialInfoLoader.java
  src/main/java/gregtech/loaders/recipe/VanillaOverrideRecipes.java
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
Labels: type: bug

#1998 Fix Super/Quantum Tanks voiding incorrect fluid
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: type: bug

#2002 use GTValues.LV etc. in all usages of GTValues.V*
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/HigherDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/common/blocks/BlockMachineCasing.java
  src/main/java/gregtech/common/covers/CoverBehaviors.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeEnergy.java
Labels: ignore changelog

#1996 top addons fluid compat
  src/api/java/io/github/drmanganese/topaddons/reference/Colors.java
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/fluids/MetaFluids.java
  src/main/java/gregtech/api/util/GTUtility.java
Labels: type: feature

#2001 Fix Large Boiler and Steam Machines giving incorrect info in TheOneProbe/HWYLA
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/integration/hwyla/provider/RecipeLogicDataProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/RecipeLogicInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: bug

#2004 Add CLipboard NBT clearing recipe
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
Labels: type: feature

#1992 Fix Buses not Auto Collapsing
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
Labels: type: bug

#2014 fix missing battery baubles
  src/main/java/gregtech/integration/baubles/BaublesModule.java
Labels: type: bug

#2011 Update build script version to 1690591996
  build.gradle
  gradle.properties
Labels: ignore changelog

#2015 Update build script version to 1690655342
  build.gradle
Labels: ignore changelog

#2018 minor muffler hatch optimization
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
Labels: ignore changelog

#2017 Improve super tank fluid sync
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: type: refactor

#2008 Add MTE tick time tracker debug TOP provider
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeModule.java
  src/main/java/gregtech/integration/theoneprobe/provider/debug/DebugPipeNetInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/debug/DebugTickTimeProvider.java
Labels: ignore changelog

#2021 Fix recipe removal issue
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: type: bug

#2023 Update build script version to 1690845237
  build.gradle
Labels: ignore changelog

#2024 Redo buildscript updater to use gradle task
  .github/workflows/update_buildscript.yml
Labels: ignore changelog
