Repository GregTechCEu/GregTech, pull requests merged in 2023-04, with the labels that each got.

#1667 Fix LT visitor incompatibility with recent ASM version
  src/api/java/com/creativemd/creativecore/client/mods/optifine/OptifineHelper.java
Labels: type: bug

#1661 Fix issue with GTTransferUtils#insertItem
  src/main/java/gregtech/api/util/GTTransferUtils.java
Labels: type: refactor

#1664 Make stone types always show in TOP
  src/main/java/gregtech/common/blocks/BlockOre.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeCompatibility.java
  src/main/java/gregtech/integration/theoneprobe/provider/BlockOreProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1666 Add event for MaterialInfo modification
  src/main/java/gregtech/api/event/MaterialInfoEvent.java
  src/main/java/gregtech/loaders/recipe/GTRecipeManager.java
  src/main/java/gregtech/loaders/recipe/RecyclingRecipes.java
Labels: type: feature

#1649 Implement High Tier API
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/GregTechAPIInternal.java
  src/main/java/gregtech/api/event/HighTierEvent.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/blocks/BlockMachineCasing.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/loaders/recipe/CraftingComponent.java
Labels: type: feature

#1668 Fix a Rendering Exception with Quantum Tanks
  src/main/java/gregtech/client/renderer/texture/custom/QuantumStorageRenderer.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: ignore changelog

#1671 Fix stone types dropping the wrong variant
  src/main/java/gregtech/api/unification/ore/StoneType.java
  src/main/java/gregtech/api/worldgen/config/OreConfigUtils.java
  src/main/java/gregtech/common/blocks/BlockOre.java
Labels: type: bug

#1673 Take the Ceiling of the entire EU value
  src/main/java/gregtech/api/capability/impl/SteamMultiWorkable.java
Labels: type: bug

#1672 Allow ICoverable to determine if the machine grid should render
  src/main/java/gregtech/api/cover/ICoverable.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/common/ToolEventHandlers.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityLockedSafe.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
Labels: type: feature

#1662 Fix some issues with tape and maintenance hatches
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java
Labels: type: bug

#1677 Remove 1 distilled water recipe
  src/main/java/gregtech/loaders/recipe/chemistry/DistillationRecipes.java
Labels: type: feature

#1561 New ore filter implementation
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/java/gregtech/api/gui/widgets/OreDictFilterTestSlot.java
  src/main/java/gregtech/api/gui/widgets/TextFieldWidget2.java
  src/main/java/gregtech/api/util/OreDictExprFilter.java
  src/main/java/gregtech/api/util/oreglob/OreGlob.java
  src/main/java/gregtech/api/util/oreglob/OreGlobCompileResult.java
  src/main/java/gregtech/api/util/oreglob/OreGlobFormattedStringVisualizer.java
  src/main/java/gregtech/api/util/oreglob/OreGlobStringVisualizer.java
  src/main/java/gregtech/common/covers/filter/OreDictionaryItemFilter.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/ImpossibleOreGlob.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/NodeInterpreter.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/NodeOreGlob.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/NodeVisualizer.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/OreGlobParser.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/AnyCharNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/BranchNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/ErrorNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/GroupNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/MatchDescription.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/MatchNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/NodeVisitor.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/OreGlobNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/OreGlobNodes.java
  src/main/java/gregtech/common/gui/widget/HighlightedTextField.java
  src/main/java/gregtech/common/gui/widget/orefilter/ItemOreFilterTestSlot.java
  src/main/java/gregtech/common/gui/widget/orefilter/OreFilterTestSlot.java
  src/main/java/gregtech/common/gui/widget/orefilter/OreGlobCompileStatusWidget.java
  src/main/java/gregtech/integration/theoneprobe/provider/CoverProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/gui/widget/ore_filter/error.png
  src/main/resources/assets/gregtech/textures/gui/widget/ore_filter/info.png
  src/main/resources/assets/gregtech/textures/gui/widget/ore_filter/match.png
  src/main/resources/assets/gregtech/textures/gui/widget/ore_filter/no_match.png
  src/main/resources/assets/gregtech/textures/gui/widget/ore_filter/success.png
  src/main/resources/assets/gregtech/textures/gui/widget/ore_filter/waiting.png
  src/main/resources/assets/gregtech/textures/gui/widget/ore_filter/warn.png
  src/test/java/gregtech/api/util/OreGlobTest.java
Labels: type: refactor

#1679 Lighting fix for glass casings
  src/main/java/gregtech/common/blocks/BlockGlassCasing.java
Labels: type: bug

#1663 Remove ItemStackKey
  src/main/java/gregtech/api/items/armor/ArmorUtils.java
  src/main/java/gregtech/api/recipes/KeySharedStack.java
  src/main/java/gregtech/api/recipes/logic/ParallelLogic.java
  src/main/java/gregtech/api/util/GTHashMaps.java
  src/main/java/gregtech/api/util/GTTransferUtils.java
  src/main/java/gregtech/api/util/ItemStackKey.java
  src/main/java/gregtech/api/util/OverlayedItemHandler.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverItemVoidingAdvanced.java
  src/main/java/gregtech/common/covers/CoverRoboticArm.java
  src/main/java/gregtech/common/gui/widget/craftingstation/CraftingSlotWidget.java
  src/main/java/gregtech/common/gui/widget/craftingstation/ItemListGridWidget.java
  src/main/java/gregtech/common/gui/widget/craftingstation/ItemListSlotWidget.java
  src/main/java/gregtech/common/inventory/IItemInfo.java
  src/main/java/gregtech/common/inventory/IItemList.java
  src/main/java/gregtech/common/inventory/SimpleItemInfo.java
  src/main/java/gregtech/common/inventory/itemsource/ItemSource.java
  src/main/java/gregtech/common/inventory/itemsource/ItemSources.java
  src/main/java/gregtech/common/inventory/itemsource/NetworkItemInfo.java
  src/main/java/gregtech/common/inventory/itemsource/sources/InventoryItemSource.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/storage/CachedRecipeData.java
  src/main/java/gregtech/common/metatileentities/storage/CraftingRecipeLogic.java
  src/main/java/gregtech/common/pipelike/itempipe/net/ItemNetHandler.java
  src/main/java/gregtech/integration/jei/multiblock/MultiblockInfoRecipeWrapper.java
Labels: type: refactor

#1658 Fix TOP displaying two fluid bars for Multiblock tank
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityMultiblockTank.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityTankValve.java
Labels: type: bug

#1689 Fix null itemInventory in Maintenance Hatch
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java
Labels: type: bug

#1690 Fix mte traits being treated as duplicate
  src/main/java/gregtech/api/metatileentity/MTETrait.java
Labels: status: release blocker, type: bug

#1694 OverlayedFluidHandler refactor
  src/main/java/gregtech/api/util/OverlayedFluidHandler.java
Labels: type: refactor

#1710 Fix missing null checks for some Nullables
  src/main/java/gregtech/api/recipes/GTRecipeHandler.java
  src/main/java/gregtech/api/recipes/ingredients/nbtmatch/NBTCondition.java
  src/main/java/gregtech/api/recipes/ingredients/nbtmatch/NBTMatcher.java
Labels: type: bug

#1691 Remove Lombok
  build.gradle
  gradle.properties
  src/main/java/gregtech/api/network/IPacket.java
  src/main/java/gregtech/core/network/packets/PacketBlockParticle.java
  src/main/java/gregtech/core/network/packets/PacketClipboard.java
  src/main/java/gregtech/core/network/packets/PacketClipboardNBTUpdate.java
  src/main/java/gregtech/core/network/packets/PacketClipboardUIWidgetUpdate.java
  src/main/java/gregtech/core/network/packets/PacketFluidVeinList.java
  src/main/java/gregtech/core/network/packets/PacketKeysPressed.java
  src/main/java/gregtech/core/network/packets/PacketNotifyCapeChange.java
  src/main/java/gregtech/core/network/packets/PacketPluginSynced.java
  src/main/java/gregtech/core/network/packets/PacketProspecting.java
  src/main/java/gregtech/core/network/packets/PacketRecoverMTE.java
  src/main/java/gregtech/core/network/packets/PacketReloadShaders.java
  src/main/java/gregtech/core/network/packets/PacketUIClientAction.java
  src/main/java/gregtech/core/network/packets/PacketUIOpen.java
  src/main/java/gregtech/core/network/packets/PacketUIWidgetUpdate.java
Labels: ignore changelog

#1705 Slightly improve MTETrait's network ID lookup
  src/main/java/gregtech/api/metatileentity/MTETrait.java
Labels: type: refactor

#1707 Pass cleanroom reference from PA to inner machines
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
Labels: type: bug

#1717 Add harvest tools to GT blocks
  src/main/java/gregtech/common/blocks/BlockGlassCasing.java
  src/main/java/gregtech/common/blocks/BlockGregStairs.java
  src/main/java/gregtech/common/blocks/wood/BlockGregFence.java
  src/main/java/gregtech/common/blocks/wood/BlockGregFenceGate.java
  src/main/java/gregtech/common/blocks/wood/BlockRubberDoor.java
  src/main/java/gregtech/common/blocks/wood/BlockRubberLog.java
  src/main/java/gregtech/common/blocks/wood/BlockWoodenDoor.java
Labels: type: bug

#1701 Support for recipes with empty output
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
Labels: type: feature

#1718 Small refactor for drawing recipe properties on JEI
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapCokeOven.java
  src/main/java/gregtech/api/recipes/recipeproperties/RecipeProperty.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/integration/jei/recipe/RecipeMapCategory.java
Labels: type: refactor

#1726 Pass mouseX and mouseY to recipe property draw
  src/main/java/gregtech/api/recipes/recipeproperties/RecipeProperty.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
Labels: type: refactor

#1727 Add hashCode and equals for RecipeMap
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: ignore changelog

#1716 Add RECURSIVE_EQUAL_TO to NBTMatcher
  src/main/java/gregtech/api/recipes/ingredients/nbtmatch/NBTMatcher.java
Labels: type: feature

#1730 Fix Chests not opening under GT stair or slab
  src/main/java/gregtech/common/blocks/BlockGregStairs.java
  src/main/java/gregtech/common/blocks/wood/BlockGregWoodSlab.java
Labels: type: bug

#1580 zh_cn localization follow up
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#1729 Minor lang cleanups
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#1702 Fix material model breaking with resource reload
  src/main/java/gregtech/api/gui/resources/ResourceHelper.java
  src/main/java/gregtech/api/unification/material/info/MaterialIconType.java
  src/main/java/gregtech/asm/GregTechTransformer.java
  src/main/java/gregtech/asm/visitors/ModelLoaderRegistryVisitor.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
Labels: type: bug

#1700 Better cache strategy for ore dictionary / ore dictionary filter
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/api/unification/OreDictUnifier.java
  src/main/java/gregtech/api/unification/stack/EmptyVariantMap.java
  src/main/java/gregtech/api/unification/stack/ItemAndMetadata.java
  src/main/java/gregtech/api/unification/stack/ItemVariantMap.java
  src/main/java/gregtech/api/unification/stack/MultiItemVariantMap.java
  src/main/java/gregtech/api/unification/stack/SingleItemVariantMap.java
  src/main/java/gregtech/api/unification/stack/UnmodifiableSetViewVariantMap.java
  src/main/java/gregtech/common/blocks/BlockLamp.java
  src/main/java/gregtech/common/blocks/foam/BlockFoam.java
  src/main/java/gregtech/common/covers/filter/OreDictionaryItemFilter.java
  src/main/java/gregtech/common/items/tool/TorchPlaceBehavior.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityFisher.java
Labels: type: refactor

#1728 Move to RFG from FG
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/GregTechVersion.java
Labels: ignore changelog

#1622 Switch to RegistryNamespaced
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/util/GTControlledRegistry.java
Labels: type: refactor, ignore changelog

#1731 Add new vacuum tube textures
  src/main/resources/assets/gregtech/textures/items/metaitems/circuit.vacuum_tube.png
  src/main/resources/assets/gregtech/textures/items/metaitems/component.glass.tube.png
Labels: type: feature

#1706 Add Multiplier for Keep/Supply Exact on Robot Arms with Smart Filters
  src/main/java/gregtech/common/covers/CoverRoboticArm.java
  src/main/java/gregtech/common/covers/filter/SmartItemFilter.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1698 Improve default enchantment API
  src/main/java/gregtech/api/items/toolitem/EnchantmentLevel.java
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/items/toolitem/IGTToolDefinition.java
  src/main/java/gregtech/api/items/toolitem/ToolDefinitionBuilder.java
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
  src/main/java/gregtech/api/unification/crafttweaker/MaterialExpansion.java
  src/main/java/gregtech/api/unification/material/properties/ToolProperty.java
Labels: type: bug
