Repository GregTechCEu/GregTech, pull requests merged in 2023-03, with the labels that each got.

#1551 Allow any charge lapotron battery to be used in recipes
  src/main/java/gregtech/loaders/recipe/BatteryRecipes.java
Labels: type: bug

#1517 Update ForgeGradle versions and buildscript
  build.gradle
  build.gradle.kts
  etc/CTM-MC1.12.2-1.0.2.31.jar
  etc/CodeChickenLib-1.12.2-3.2.3.358-deobf.jar
  etc/CodeChickenLib-1.12.2-3.2.3.358-universal.jar
  etc/theoneprobe-1.12-1.4.28.jar
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/GregTechVersion.java
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/client/ClientProxy.java
  src/main/java/gregtech/client/model/modelfactories/CompressedBlockBakedModel.java
  src/main/java/gregtech/client/model/modelfactories/FrameBakedModel.java
  src/main/java/gregtech/client/model/modelfactories/OreBakedModel.java
  src/main/resources/META-INF/gregtech_at.cfg
  src/main/resources/gregtech_at.cfg
  src/test/java/gregtech/common/metatileentities/converter/ConverterTraitTest.java
Labels: ignore changelog

#1510 Make possible for addons to add machine items in other creative tabs
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/block/machines/MachineItemBlock.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
Labels: type: feature

#1556 Make overclockResults protected instead of private
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
Labels: type: refactor

#1550 Handle invalid metaitems gracefully
  src/main/java/gregtech/api/items/materialitem/MetaPrefixItem.java
  src/main/java/gregtech/api/items/metaitem/MetaItem.java
  src/main/java/gregtech/api/util/CTRecipeHelper.java
  src/main/java/gregtech/client/event/ClientEventHandler.java
  src/main/java/gregtech/common/EventHandlers.java
  src/main/java/gregtech/common/metatileentities/primitive/MetaTileEntityCharcoalPileIgniter.java
  src/main/java/gregtech/common/terminal/app/guide/ItemGuideApp.java
Labels: type: feature

#1522 Re-implement ActiveVariantBlockBakedModel
  src/main/java/gregtech/api/block/VariantActiveBlock.java
  src/main/java/gregtech/client/model/modelfactories/ActiveVariantBlockBakedModel.java
  src/main/java/gregtech/client/model/modelfactories/BakedModelHandler.java
  src/main/java/gregtech/client/renderer/texture/custom/FireboxActiveRenderer.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/blocks/BlockGlassCasing.java
  src/main/java/gregtech/common/blocks/BlockWireCoil.java
  src/main/resources/META-INF/gregtech_at.cfg
  src/main/resources/assets/gregtech/blockstates/boiler_firebox_casing.json
  src/main/resources/assets/gregtech/models/block/active_firebox.json
  src/main/resources/assets/minecraft/optifine/emissive.properties
Labels: type: refactor

#1519 Attempt to fix CT issues with item NBT tags
  src/main/java/gregtech/api/recipes/map/MapItemStackIngredient.java
  src/main/java/gregtech/api/recipes/map/MapItemStackNBTIngredient.java
Labels: integration: CT, type: bug

#1558 Fix issues with electric tools
  src/main/java/gregtech/common/ToolEventHandlers.java
  src/main/java/gregtech/common/crafting/ShapedOreEnergyTransferRecipe.java
Labels: type: bug

#1559 Allow Advanced Quarktech to use any charge input
  src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
Labels: type: feature

#1562 Fix jar configuration not applying to deobfJar
  build.gradle
  gradle.properties
Labels: ignore changelog

#1564 Only draw armor hud for chestplates
  src/main/java/gregtech/api/items/armor/ArmorLogicSuite.java
  src/main/java/gregtech/common/items/armor/NightvisionGoggles.java
Labels: type: bug

#1527 More flexible Creative Tab API for MetaItems
  src/main/java/gregtech/api/items/materialitem/MetaPrefixItem.java
  src/main/java/gregtech/api/items/metaitem/MetaItem.java
  src/main/java/gregtech/common/items/MetaItem1.java
Labels: type: feature

#1570 Hide MetaItem on search tab if it's hidden
  src/main/java/gregtech/api/items/metaitem/MetaItem.java
Labels: type: bug

#1568 Synchronize access to VariantActiveBlock#ACTIVE_BLOCKS
  src/main/java/gregtech/api/block/VariantActiveBlock.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
Labels: type: bug, status: high priority

#1579 Merge stacks of UHPICs in mk2 fusion recipe
  src/main/java/gregtech/loaders/recipe/AssemblyLineLoader.java
Labels: type: feature

#1577 Correct ResourceLocation cache in recurseIconsetPath
  src/main/java/gregtech/api/gui/resources/ResourceHelper.java
  src/main/java/gregtech/api/unification/material/info/MaterialIconType.java
Labels: type: bug, status: high priority

#1575 Fix Fluid Pipes not working with Fluid Filters
  src/main/java/gregtech/common/pipelike/fluidpipe/tile/TileEntityFluidPipeTickable.java
Labels: type: bug, status: high priority

#1574 Fix recipe lookup failure for some recipes
  src/main/java/gregtech/api/recipes/map/MapItemStackIngredient.java
  src/main/java/gregtech/api/recipes/map/MapItemStackNBTIngredient.java
  src/test/java/gregtech/api/recipes/RecipeMapTest.java
Labels: type: bug, status: high priority

#1567 Allow tools to have default enchantments
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/items/toolitem/IGTToolDefinition.java
  src/main/java/gregtech/api/items/toolitem/ToolDefinitionBuilder.java
  src/main/java/gregtech/common/items/ToolItems.java
Labels: type: feature

#1573 Fix more duplicate recipes
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/builders/AssemblerRecipeBuilder.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
Labels: type: bug

#1553 Implement small cover for storage
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/covers/CoverBehaviors.java
  src/main/java/gregtech/common/covers/CoverStorage.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/metaitems/cover.storage.json
  src/main/resources/assets/gregtech/textures/blocks/cover/overlay_storage.png
  src/main/resources/assets/gregtech/textures/items/metaitems/cover.storage.png
Labels: type: feature

#1552 Fix doubled TOP item display in maintenance hatches
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java
Labels: type: bug

#1309 Overhauling & updating zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#1590 Add more GroovyScript helper methods
  src/main/java/gregtech/integration/groovy/GroovyMaterialBuilderExpansion.java
  src/main/java/gregtech/integration/groovy/GroovyRecipeBuilderExpansion.java
  src/main/java/gregtech/integration/groovy/GroovyScriptCompat.java
Labels: type: feature, integration: GrS

#1582 Refactor WoodMachineRecipes
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/loaders/WoodTypeEntry.java
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/GTRecipeManager.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/VanillaOverrideRecipes.java
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
  src/main/java/gregtech/loaders/recipe/WoodMachineRecipes.java
  src/main/java/gregtech/loaders/recipe/WoodRecipeLoader.java
Labels: type: bug, type: refactor

#1606 Improve rock breaker tooltip
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1609 Extra creative tabs for machines, cables, pipes and tools
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/block/machines/MachineItemBlock.java
  src/main/java/gregtech/api/gui/UIFactory.java
  src/main/java/gregtech/api/items/armor/ArmorMetaItem.java
  src/main/java/gregtech/api/items/toolitem/ItemGTAxe.java
  src/main/java/gregtech/api/items/toolitem/ItemGTHoe.java
  src/main/java/gregtech/api/items/toolitem/ItemGTSword.java
  src/main/java/gregtech/api/items/toolitem/ItemGTTool.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/pipelike/cable/BlockCable.java
  src/main/java/gregtech/common/pipelike/fluidpipe/BlockFluidPipe.java
  src/main/java/gregtech/common/pipelike/itempipe/BlockItemPipe.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1605 Fix the weird seam visible in button widgets
  src/main/java/gregtech/api/gui/resources/SizedTextureArea.java
Labels: type: bug

#1603 Add gears to Materials, for a Lathe Buzzsaw Blade recipe
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/HigherDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
Labels: type: feature

#1597 Fix classloading crash with ASM
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/asm/GregTechTransformer.java
Labels: type: bug

#1586 Fix pipes not updating their redstone signals
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
Labels: type: bug

#1593 Re-add Concrete movement speed bonuses
  src/main/java/gregtech/api/block/IWalkingSpeedBonus.java
  src/main/java/gregtech/api/block/VariantBlock.java
  src/main/java/gregtech/common/blocks/BlockAsphalt.java
  src/main/java/gregtech/common/blocks/BlockStoneBricks.java
  src/main/java/gregtech/common/blocks/BlockStoneBricksCracked.java
  src/main/java/gregtech/common/blocks/BlockStoneBricksMossy.java
  src/main/java/gregtech/common/blocks/BlockStoneBricksSmall.java
  src/main/java/gregtech/common/blocks/BlockStoneBricksSquare.java
  src/main/java/gregtech/common/blocks/BlockStoneChiseled.java
  src/main/java/gregtech/common/blocks/BlockStoneCobble.java
  src/main/java/gregtech/common/blocks/BlockStoneCobbleMossy.java
  src/main/java/gregtech/common/blocks/BlockStonePolished.java
  src/main/java/gregtech/common/blocks/BlockStoneSmooth.java
  src/main/java/gregtech/common/blocks/BlockStoneTiled.java
  src/main/java/gregtech/common/blocks/BlockStoneTiledSmall.java
  src/main/java/gregtech/common/blocks/BlockStoneWindmillA.java
  src/main/java/gregtech/common/blocks/BlockStoneWindmillB.java
Labels: type: bug

#1587 Fix issues with breaking ice
  src/main/java/gregtech/api/util/function/Task.java
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: type: bug

#1620 Get all elements
  src/main/java/gregtech/api/unification/Elements.java
Labels: integration: CT, type: feature

#1613 Replace main tab icon with GregTech logo
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/resources/assets/gregtech/models/item/metaitems/logo.json
  src/main/resources/assets/gregtech/models/item/metaitems/logo_xmas.json
  src/main/resources/assets/gregtech/textures/items/metaitems/gregtech_logo.png
  src/main/resources/assets/gregtech/textures/items/metaitems/gregtech_logo_xmas.png
Labels: type: feature

#1443 Add method for recycling recipes to use nbt conditions
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/api/recipes/ingredients/nbtmatch/NBTMatcher.java
  src/main/java/gregtech/loaders/recipe/RecyclingRecipes.java
Labels: type: bug

#1617 TaskScheduler cleanup
  src/main/java/gregtech/api/util/TaskScheduler.java
Labels: type: refactor

#1598 Make sure to call the Cover Behavior Right click
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
Labels: type: bug

#1599 Allow Crafting Table covers to be opened with screwdriver or hand
  src/main/java/gregtech/common/covers/CoverCraftingTable.java
Labels: type: feature

#1539 Change Bender Recipe
  src/main/java/gregtech/loaders/recipe/CraftingComponent.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
Labels: type: feature

#1588 Remove Cover Network ID Registration
  src/main/java/gregtech/api/cover/CoverDefinition.java
  src/main/java/gregtech/api/cover/CoverIO.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/pipenet/tile/PipeCoverableImplementation.java
  src/main/java/gregtech/common/covers/CoverBehaviors.java
Labels: type: refactor

#1621 document and cleanup RecipeMap
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/map/Branch.java
  src/main/java/gregtech/api/recipes/map/MapItemStackIngredient.java
  src/main/java/gregtech/api/recipes/map/MapItemStackNBTIngredient.java
Labels: type: refactor

#1618 Remove the CT Ingredient Wrapper
  src/main/java/gregtech/api/recipes/crafttweaker/CTNBTMatcher.java
  src/main/java/gregtech/api/recipes/crafttweaker/CTNBTMultiItemMatcher.java
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipeBuilder.java
  src/main/java/gregtech/api/recipes/ingredients/CraftTweakerItemInputWrapper.java
  src/main/java/gregtech/api/recipes/ingredients/GTRecipeItemInput.java
  src/main/java/gregtech/api/recipes/ingredients/nbtmatch/NBTMatcher.java
  src/main/resources/META-INF/gregtech_at.cfg
Labels: type: refactor

#1607 Replace vanilla slab/sapling in recipes with ore dictionary entry
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
  src/main/java/gregtech/loaders/recipe/VanillaOverrideRecipes.java
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
Labels: type: feature

#1610 Re-implement Quantum Tank with excess voiding option
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/gui/widgets/PhantomTankWidget.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1458 Ghost Circuits
  src/main/java/gregtech/api/gui/widgets/FakeCircuitSlotWidget.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/common/items/behaviors/IntCircuitBehaviour.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1629 Fix recipe conflict
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
Labels: type: bug

#1632 Fix breaking assembly line on servers causing crash
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
Labels: type: bug

#1633 Fix all CT item inputs being considered NBT inputs
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipeBuilder.java
Labels: type: bug, ignore changelog

#1625 Expose RecipeMap#removeAll to CT
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipeUtils.java
Labels: integration: CT, type: feature

#1628 Fixes for the large miner
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
  src/main/java/gregtech/api/capability/impl/miner/MultiblockMinerLogic.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMiner.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/common/metatileentities/steam/SteamMiner.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/lang/ja_jp.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: bug

#1639 Fix recycling edge case
  src/main/java/gregtech/loaders/recipe/RecyclingRecipes.java
Labels: type: bug

#1638 Fix Crash in Recipe Chart App with invalid Itemstacks
  src/main/java/gregtech/common/terminal/app/recipechart/widget/RGNode.java
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
Labels: type: bug

#1631 Give back int circuits when loading legacy save
  src/main/java/gregtech/api/capability/impl/GhostCircuitItemStackHandler.java
  src/main/java/gregtech/api/gui/widgets/FakeCircuitSlotWidget.java
  src/main/java/gregtech/api/gui/widgets/GhostCircuitSlotWidget.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/common/items/behaviors/IntCircuitBehaviour.java
Labels: type: feature

#1637 Make EBF voltage tier heat bonuses predictable
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityElectricBlastFurnace.java
Labels: type: bug

#1591 New model system for material block / frame / ores
  src/main/java/gregtech/api/block/VariantActiveBlock.java
  src/main/java/gregtech/api/unification/material/info/MaterialIconType.java
  src/main/java/gregtech/client/ClientProxy.java
  src/main/java/gregtech/client/model/ActiveVariantBlockBakedModel.java
  src/main/java/gregtech/client/model/EmissiveOreBakedModel.java
  src/main/java/gregtech/client/model/IModelSupplier.java
  src/main/java/gregtech/client/model/MaterialStateMapper.java
  src/main/java/gregtech/client/model/ModelFactory.java
  src/main/java/gregtech/client/model/OreBakedModel.java
  src/main/java/gregtech/client/model/modelfactories/BakedModelHandler.java
  src/main/java/gregtech/client/model/modelfactories/CompressedBlockBakedModel.java
  src/main/java/gregtech/client/model/modelfactories/FrameBakedModel.java
  src/main/java/gregtech/client/model/modelfactories/MaterialBlockModelLoader.java
  src/main/java/gregtech/client/model/modelfactories/OreBakedModel.java
  src/main/java/gregtech/client/utils/RenderUtil.java
  src/main/java/gregtech/common/blocks/BlockCompressed.java
  src/main/java/gregtech/common/blocks/BlockFrame.java
  src/main/java/gregtech/common/blocks/BlockOre.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/resources/assets/gregtech/models/block/material_sets/dull/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/dull/frame_gt.json
  src/main/resources/assets/gregtech/models/block/material_sets/emerald/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/fine/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/glass/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/lapis/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/lignite/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/netherstar/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/opal/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/powder/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/quartz/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/rough/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/sand/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/shiny/block.json
  src/main/resources/assets/gregtech/models/block/material_sets/wood/block.json
  src/main/resources/assets/gregtech/models/block/ore_overlay.json
  src/main/resources/assets/gregtech/models/item/material_sets/dull/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/dull/frame_gt.json
  src/main/resources/assets/gregtech/models/item/material_sets/emerald/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/fine/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/glass/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/lapis/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/lignite/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/netherstar/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/opal/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/powder/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/quartz/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/rough/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/sand/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/shiny/block.json
  src/main/resources/assets/gregtech/models/item/material_sets/wood/block.json
  src/main/resources/assets/gregtech/textures/blocks/material_sets/paper/frame_gt.png
  src/main/resources/assets/gregtech/textures/blocks/material_sets/powder/frame_gt.png
Labels: type: refactor

#1636 Add Interact event handler for item frames to ignore tools that return a broken version (power unit)
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: type: bug

#1619 New CI/CD Pipeline
  .github/workflows/curseforge_release.yml
  .github/workflows/github_release.yml
  .github/workflows/pr.yml
  .github/workflows/pr_artifact.yml
  .github/workflows/pr_enforce_labels.yml
  .github/workflows/pr_labels.yml
  .github/workflows/pr_testing.yml
  .github/workflows/publish.yml
  .github/workflows/update_gradle_cache.yml
  .github/workflows/validate_gradle_wrapper.yml
  build.gradle
  gradle.properties
Labels: ignore changelog

#1627 Refactor MTETrait
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/EnergyContainerBatteryBuffer.java
  src/main/java/gregtech/api/capability/impl/EnergyContainerHandler.java
  src/main/java/gregtech/api/capability/impl/RecipeLogicSteam.java
  src/main/java/gregtech/api/metatileentity/MTETrait.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/metatileentities/converter/ConverterTrait.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
  src/test/java/gregtech/api/recipes/logic/IParallelableRecipeLogicTest.java
Labels: type: refactor

#1643 New constructor
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapAssemblyLine.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapCokeOven.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapCrackerUnit.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapDistillationTower.java
Labels: ignore changelog

#1642 Add missing fluid for ruridit
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
Labels: type: bug

#1624 Remove RecipeMap Minimums and add setters for Maximums
  src/main/java/gregtech/api/metatileentity/multiblock/MultiMapMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapSteamMultiblockController.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapAssemblyLine.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapCokeOven.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapCrackerUnit.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapDistillationTower.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapFluidCanner.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapFormingPress.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
Labels: type: feature

#1540 Improve EnergyNetHandler#acceptEnergyFromNetwork performance
  src/main/java/gregtech/common/pipelike/cable/net/EnergyNetHandler.java
Labels: type: refactor

#1543 Improve performance of OverlayedFluidHandler
  src/main/java/gregtech/api/util/IFluidTankPropertiesHashStrategy.java
  src/main/java/gregtech/api/util/OverlayedFluidHandler.java
Labels: type: refactor

#1645 Produce any wire type in the wiremill
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/loaders/recipe/handlers/PartsRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/WireRecipeHandler.java
Labels: type: feature

#1650 Cleanup `RecipeMap#findRecipe`
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
  src/main/java/gregtech/api/recipes/GTRecipeHandler.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/logic/ParallelLogic.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapFluidCanner.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapFormingPress.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapFurnace.java
  src/main/java/gregtech/common/covers/filter/SmartItemFilter.java
  src/main/java/gregtech/integration/groovy/VirtualizedRecipeMap.java
  src/test/java/gregtech/api/recipes/RecipeMapTest.java
Labels: type: refactor

#1644 Update World Prospector App
  src/main/java/gregtech/common/items/behaviors/TerminalBehaviour.java
  src/main/java/gregtech/common/terminal/app/worldprospector/WorldProspectorARApp.java
Labels: type: bug

#1653 Change editorconfig
  .editorconfig
Labels: type: refactor, ignore changelog

#1654 Decoration tab, stone variant refactor & changes etc.
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/block/IWalkingSpeedBonus.java
  src/main/java/gregtech/api/unification/ore/StoneTypes.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/blocks/BlockAsphalt.java
  src/main/java/gregtech/common/blocks/BlockGregStairs.java
  src/main/java/gregtech/common/blocks/BlockStoneBricks.java
  src/main/java/gregtech/common/blocks/BlockStoneBricksCracked.java
  src/main/java/gregtech/common/blocks/BlockStoneBricksMossy.java
  src/main/java/gregtech/common/blocks/BlockStoneBricksSmall.java
  src/main/java/gregtech/common/blocks/BlockStoneBricksSquare.java
  src/main/java/gregtech/common/blocks/BlockStoneChiseled.java
  src/main/java/gregtech/common/blocks/BlockStoneCobble.java
  src/main/java/gregtech/common/blocks/BlockStoneCobbleMossy.java
  src/main/java/gregtech/common/blocks/BlockStonePolished.java
  src/main/java/gregtech/common/blocks/BlockStoneSmooth.java
  src/main/java/gregtech/common/blocks/BlockStoneTiled.java
  src/main/java/gregtech/common/blocks/BlockStoneTiledSmall.java
  src/main/java/gregtech/common/blocks/BlockStoneWindmillA.java
  src/main/java/gregtech/common/blocks/BlockStoneWindmillB.java
  src/main/java/gregtech/common/blocks/BlockWarningSign.java
  src/main/java/gregtech/common/blocks/BlockWarningSign1.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/blocks/StoneVariantBlock.java
  src/main/java/gregtech/common/blocks/foam/BlockFoam.java
  src/main/java/gregtech/common/blocks/foam/BlockPetrifiedFoam.java
  src/main/java/gregtech/common/blocks/wood/BlockGregFence.java
  src/main/java/gregtech/common/blocks/wood/BlockGregFenceGate.java
  src/main/java/gregtech/common/blocks/wood/BlockGregWoodSlab.java
  src/main/java/gregtech/common/blocks/wood/BlockRubberLog.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/loaders/OreDictionaryLoader.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/ChemicalBathRecipes.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature, type: refactor

#1641 Remodeling of quantum chests/tanks
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/client/renderer/texture/custom/QuantumStorageRenderer.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeTank.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_screen_glass.png
Labels: type: feature

#1656 Fix lighting bug on quantum storages
  src/main/java/gregtech/client/renderer/texture/custom/QuantumStorageRenderer.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeTank.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: ignore changelog

#1652 Update ja_jp.lang for 2.5.5-bata
  src/main/resources/assets/gregtech/lang/ja_jp.lang
Labels: type: translation

#1660 Replace usage of WildcardAwareHashMap with plain maps
  src/main/java/gregtech/api/unification/OreDictUnifier.java
  src/main/java/gregtech/api/unification/stack/ItemAndMetadata.java
  src/main/java/gregtech/api/unification/stack/WildcardAwareHashMap.java
Labels: type: refactor
