Repository GregTechCEu/GregTech, pull requests merged in 2023-02, with the labels that each got.

#1473 Use grid's slotX amount instead of hardcoded 9.
  src/main/java/gregtech/common/gui/widget/craftingstation/ItemListGridWidget.java
Labels: type: bug

#1471 Update ja_jp.lang
  src/main/resources/assets/gregtech/lang/ja_jp.lang
Labels: type: translation

#1459 Fix crash with cleanroom and terminal
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
Labels: type: bug

#1449 Allow resourcepacks to add additional overlay textures
  src/main/java/gregtech/api/gui/resources/ResourceHelper.java
  src/main/java/gregtech/client/renderer/ICubeRenderer.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/client/renderer/texture/cube/OrientedOverlayRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/SidedCubeRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/SimpleOrientedCubeRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/SimpleSidedCubeRenderer.java
  src/main/java/gregtech/client/renderer/texture/custom/FireboxActiveRenderer.java
Labels: type: feature

#1477 Add isElement() and getElement() methods
  src/main/java/gregtech/api/unification/material/Material.java
Labels: type: feature

#1428 stricter equals
  src/main/java/gregtech/api/recipes/map/MapItemStackIngredient.java
  src/main/java/gregtech/api/recipes/map/MapItemStackNBTIngredient.java
Labels: type: bug

#1479 Set detector/activator rails to use circuit 5 instead of 4
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
Labels: type: bug

#1446 Some defensive JEI integration code
  src/main/java/gregtech/api/gui/widgets/RecipeProgressWidget.java
Labels: type: bug

#1450 Add config for blocking TileEntities from world acceleration
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityWorldAccelerator.java
Labels: type: feature

#1426 Add a config option to disable blinking tooltips
  src/main/java/gregtech/client/utils/TooltipHelper.java
  src/main/java/gregtech/common/ConfigHolder.java
Labels: type: feature

#1481 Simplify regex pattern for allowed chars in OreDictionaryItemFilter
  src/main/java/gregtech/common/covers/detector/CoverDetectorEnergyAdvanced.java
  src/main/java/gregtech/common/covers/filter/OreDictionaryItemFilter.java
Labels: type: bug

#1485 Fix emissive textures not being found
  src/main/java/gregtech/client/renderer/ICubeRenderer.java
Labels: status: high priority, ignore changelog

#1483 Add Autoclave recipe for Clay (balls) from Clay Dust and Distilled Water
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
Labels: type: feature

#1478 Allow customization of multiblock preview background and font color
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/integration/jei/multiblock/MultiblockInfoRecipeWrapper.java
Labels: type: feature

#684 Implement Item bus auto collapsing
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/steam/multiblockpart/MetaTileEntitySteamItemBus.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1414 Rework Voiding Covers
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/covers/CoverFluidVoiding.java
  src/main/java/gregtech/common/covers/CoverFluidVoidingAdvanced.java
  src/main/java/gregtech/common/covers/CoverItemVoiding.java
  src/main/java/gregtech/common/covers/CoverItemVoidingAdvanced.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#993 Add the Charcoal Pit
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/blocks/BlockBrittleCharcoal.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/items/behaviors/LighterBehaviour.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/primitive/MetaTileEntityCharcoalPileIgniter.java
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
  src/main/resources/assets/gregtech/blockstates/brittle_charcoal.json
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/misc/brittle_charcoal.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/charcoal_pile_igniter/overlay_top.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/charcoal_pile_igniter/overlay_top_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/charcoal_pile_igniter/overlay_top_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/charcoal_pile_igniter/overlay_top_active_emissive.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/multiblock/charcoal_pile_igniter/overlay_top_emissive.png
Labels: type: feature

#1451 Update ru_ru lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: type: translation

#1454 Increase tool durability based on maximum aoe area
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/items/toolitem/IGTToolDefinition.java
  src/main/java/gregtech/api/items/toolitem/ToolDefinitionBuilder.java
  src/main/java/gregtech/api/unification/crafttweaker/MaterialPropertyExpansion.java
  src/main/java/gregtech/api/unification/material/properties/ToolProperty.java
  src/main/java/gregtech/common/items/ToolItems.java
Labels: type: feature

#1448 Implement Advanced Fluid/Item Detectors
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/covers/CoverBehaviors.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorFluid.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorFluidAdvanced.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorItem.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorItemAdvanced.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/metaitems/cover.fluid.detector.advanced.json
  src/main/resources/assets/gregtech/models/item/metaitems/cover.item.detector.advanced.json
  src/main/resources/assets/gregtech/textures/blocks/cover/overlay_fluid_detector_advanced.png
  src/main/resources/assets/gregtech/textures/blocks/cover/overlay_item_detector_advanced.png
  src/main/resources/assets/gregtech/textures/items/metaitems/cover.fluid.detector.advanced.png
  src/main/resources/assets/gregtech/textures/items/metaitems/cover.item.detector.advanced.png
Labels: type: feature

#1114 Create a Fluid Vein JEI page
  build.gradle.kts
  etc/jei_1.12.2-4.16.1.301.jar
  src/main/java/gregtech/api/unification/ore/StoneType.java
  src/main/java/gregtech/api/util/FileUtility.java
  src/main/java/gregtech/api/util/GTJEIUtility.java
  src/main/java/gregtech/api/util/GTStringUtils.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
  src/main/java/gregtech/integration/jei/GTOreCategory.java
  src/main/java/gregtech/integration/jei/basic/BasicRecipeCategory.java
  src/main/java/gregtech/integration/jei/basic/GTFluidVeinCategory.java
  src/main/java/gregtech/integration/jei/basic/GTFluidVeinInfo.java
  src/main/java/gregtech/integration/jei/basic/GTOreCategory.java
  src/main/java/gregtech/integration/jei/basic/GTOreInfo.java
  src/main/java/gregtech/integration/jei/basic/MaterialTree.java
  src/main/java/gregtech/integration/jei/basic/MaterialTreeCategory.java
  src/main/java/gregtech/integration/jei/basic/OreByProduct.java
  src/main/java/gregtech/integration/jei/basic/OreByProductCategory.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1419 Fixes #1416 with new lathe recipes for stone rods
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
Labels: type: feature

#1492 Update Advanced Item/Fluid Tooltip
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: ignore changelog

#1490 Fix tools losing their oredicts after being damaged
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
Labels: type: bug, status: high priority

#1407 Add more tool oredicts
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/items/toolitem/ItemGTAxe.java
  src/main/java/gregtech/api/items/toolitem/ItemGTHoe.java
  src/main/java/gregtech/api/items/toolitem/ItemGTSword.java
  src/main/java/gregtech/api/items/toolitem/ItemGTTool.java
  src/main/java/gregtech/api/items/toolitem/ToolBuilder.java
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
  src/main/java/gregtech/api/items/toolitem/ToolOreDict.java
  src/main/java/gregtech/api/items/toolitem/ToolOreDicts.java
  src/main/java/gregtech/common/items/ToolItems.java
  src/main/resources/assets/gregtech/advancements/medium_voltage/32_electric_drill.json
  src/main/resources/assets/gregtech/advancements/steam/1_first_tools.json
  src/main/resources/assets/gregtech/advancements/steam/2_more_tools.json
Labels: type: feature

#1493 Fix NPE comparing NBT ingredients
  src/main/java/gregtech/api/recipes/map/MapItemStackNBTIngredient.java
Labels: type: bug

#1498 Fix Vanilla ores spawning, fixes #1495
  src/main/java/gregtech/api/worldgen/config/WorldGenRegistry.java
Labels: type: bug

#1504 Fix Electric Wrenches not having the toolWrench oreDict
  src/main/java/gregtech/common/items/ToolItems.java
Labels: type: bug

#1509 Update ja_jp.lang
  src/main/resources/assets/gregtech/lang/ja_jp.lang
Labels: type: translation

#1496 Fix and improve dynamic resource discovery
  src/main/java/gregtech/api/gui/resources/ResourceHelper.java
  src/main/java/gregtech/api/unification/material/info/MaterialIconType.java
  src/main/java/gregtech/client/renderer/ICubeRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/SimpleOrientedCubeRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/SimpleOverlayRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/SimpleSidedCubeRenderer.java
Labels: type: bug

#1502 Fix Missing Text when holding item on mouse
  src/main/java/gregtech/api/gui/impl/ModularUIGui.java
Labels: type: bug

#1508 Fix Missing Dust-> Ingot smelting recipes
  src/main/java/gregtech/loaders/recipe/handlers/MaterialRecipeHandler.java
Labels: type: bug

#1512 Fix Fluid Pipes not respecting Fluid Regulators or Pumps
  src/main/java/gregtech/common/pipelike/fluidpipe/tile/TileEntityFluidPipeTickable.java
Labels: type: bug

#1513 Fix visual bug with BlockGlassCasing
  src/main/java/gregtech/common/blocks/BlockGlassCasing.java
Labels: type: bug

#1507 Null Check RayTraceResult
  src/main/java/gregtech/common/items/behaviors/CoverPlaceBehavior.java
Labels: type: bug

#1518 Add harvest level parameter to setToolStats() for CT
  src/main/java/gregtech/api/unification/crafttweaker/MaterialExpansion.java
Labels: integration: CT, type: feature

#1520 Fix incorrect event handler registration
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/loaders/dungeon/ChestGenHooks.java
Labels: type: bug

#1521 Replace model lookup in VariantActiveBlock with manual layer checking
  src/main/java/gregtech/api/block/VariantActiveBlock.java
  src/main/java/gregtech/common/blocks/BlockWireCoil.java
Labels: type: feature

#1523 Correct planks material
  src/main/java/gregtech/common/blocks/wood/BlockGregPlanks.java
Labels: type: bug

#1528 Add tooltip for drum auto output
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityDrum.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1526 Fix different variants of BlockGlassCasing getting connected together
  src/main/java/gregtech/common/blocks/BlockGlassCasing.java
Labels: type: feature

#1530 Add line about holding spraycans in offhand to color
  src/main/java/gregtech/common/items/behaviors/ColorSprayBehaviour.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1538 Fix the recipe removal button not showing without CT installed
  src/main/java/gregtech/api/util/CTRecipeHelper.java
  src/main/java/gregtech/integration/RecipeCompatUtil.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
Labels: integration: CT, type: bug, integration: GrS

#1511 Fixes for Advanced Energy Detector
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorEnergy.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorEnergyAdvanced.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1546 Move circuitMeta() to RecipeBuilder
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/builders/AssemblerRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/IntCircuitRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/UniversalDistillationRecipeBuilder.java
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipeBuilder.java
  src/main/java/gregtech/api/recipes/ingredients/IntCircuitIngredient.java
  src/main/java/gregtech/loaders/recipe/BatteryRecipes.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/AcidRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/AssemblerRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/ChemistryRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/FuelRecipeChains.java
  src/main/java/gregtech/loaders/recipe/chemistry/GrowthMediumRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/LCRCombined.java
  src/main/java/gregtech/loaders/recipe/chemistry/MixerRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/PetrochemRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/PolymerRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/ReactorRecipes.java
  src/main/java/gregtech/loaders/recipe/handlers/MaterialRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/OreRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/PipeRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/WireCombiningHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/WireRecipeHandler.java
Labels: type: refactor

#1545 Improve performance of MetaItem#getItem
  src/main/java/gregtech/api/items/metaitem/MetaItem.java
Labels: type: refactor

#1534 Relocate SlotUtil
  src/main/java/gregtech/api/gui/widgets/PhantomSlotUtil.java
  src/main/java/gregtech/api/gui/widgets/PhantomSlotWidget.java
Labels: type: refactor

#1533 Move ShapedOreEnergyTransferRecipe to common.crafting
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/common/crafting/ShapedOreEnergyTransferRecipe.java
  src/main/java/gregtech/common/metatileentities/storage/CachedRecipeData.java
Labels: type: refactor
