Repository GregTechCEu/GregTech, pull requests merged in 2023-05, with the labels that each got.

#1733 Show name of locked fluid in Quantum Tank
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: type: feature

#1735 Fix wildcard ingredients in the recipe search tree
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/test/java/gregtech/api/recipes/RecipeMapTest.java
Labels: type: bug

#1724 Progression tweaks
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/loaders/recipe/CircuitRecipes.java
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/ChemicalBathRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/GemSlurryRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/PetrochemRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/SeparationRecipes.java
  src/main/java/gregtech/loaders/recipe/handlers/PartsRecipeHandler.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1739 Add tooltip to display fluid in units of 144
  src/main/java/gregtech/api/gui/widgets/TankWidget.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1740 Apply coil EUt discount when not overclocking
  src/main/java/gregtech/api/capability/impl/HeatingCoilRecipeLogic.java
  src/main/java/gregtech/api/recipes/logic/OverclockingLogic.java
Labels: type: bug

#1722 Fix some fluid textures
  src/main/java/gregtech/api/fluids/MetaFluids.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.liquid_air.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.liquid_air.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.toluene.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.toluene.png.mcmeta
Labels: type: bug

#1737 Allow matching any or no nbt tag in CT
  src/main/java/gregtech/api/recipes/crafttweaker/CTNBTMultiItemMatcher.java
  src/main/java/gregtech/api/recipes/crafttweaker/CTRecipeBuilder.java
Labels: integration: CT, type: bug, deployment: artifact

#1743 Use translation keys for tool classes
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: bug, type: translation

#1755 Fix missing Neutronium Screwdriver Tip
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
Labels: type: bug

#1756 Fix Butchery Knife being marked as crafting tool
  src/main/java/gregtech/common/items/ToolItems.java
Labels: type: bug

#1758 Fix Groovyscript PID
  build.gradle
  gradle.properties
Labels: ignore changelog

#1757 Fix Chainsaw not playing sound when breaking ice
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: type: bug

#1759 Fix item repair name in tool tooltips
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
Labels: type: bug

#1760 Rename the Internal Tags class to clarity with addons
  build.gradle
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/GregTechVersion.java
  src/main/java/gregtech/api/GTValues.java
Labels: type: refactor

#1762 Add a full dep string
  build.gradle
Labels: ignore changelog

#1715 Material Block Cleanup + Block Registration Cleanup + @
  src/main/java/gregtech/api/block/DelayedStateBlock.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/api/recipes/crafttweaker/MetaItemBracketHandler.java
  src/main/java/gregtech/api/util/CTRecipeHelper.java
  src/main/java/gregtech/api/util/GTStringUtils.java
  src/main/java/gregtech/client/ClientProxy.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/blocks/BlockCompressed.java
  src/main/java/gregtech/common/blocks/BlockFrame.java
  src/main/java/gregtech/common/blocks/BlockMachineCasing.java
  src/main/java/gregtech/common/blocks/BlockMaterialBase.java
  src/main/java/gregtech/common/blocks/BlockOre.java
  src/main/java/gregtech/common/blocks/BlockSurfaceRock.java
  src/main/java/gregtech/common/blocks/CompressedItemBlock.java
  src/main/java/gregtech/common/blocks/FrameItemBlock.java
  src/main/java/gregtech/common/blocks/MaterialItemBlock.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/blocks/OreItemBlock.java
  src/main/java/gregtech/common/command/CommandRecipeCheck.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityLargeBoiler.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityMultiblockTank.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/common/metatileentities/multi/steam/MetaTileEntitySteamOven.java
Labels: type: refactor

#1770 Create codeowners
  CODEOWNERS
Labels: ignore changelog

#1772 Update README.md
  README.md
Labels: ignore changelog

#1766 Update RFG
  gradle.properties
Labels: ignore changelog

#1773 Use HTTPS in LICENSE
  LICENSE
Labels: ignore changelog

#1778 Update Dev Cape Registry
  src/main/java/gregtech/api/util/CapesRegistry.java
Labels: ignore changelog

#1753 Multiblock Builder item
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/common/items/behaviors/MultiblockBuilderBehavior.java
  src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/metaitems/tool.multiblock_builder.auto.json
  src/main/resources/assets/gregtech/models/item/metaitems/tool.multiblock_builder.default.json
  src/main/resources/assets/gregtech/models/item/metaitems/tool.multiblock_builder.json
  src/main/resources/assets/gregtech/textures/items/metaitems/tool.multiblock_builder.auto.png
  src/main/resources/assets/gregtech/textures/items/metaitems/tool.multiblock_builder.auto.png.mcmeta
  src/main/resources/assets/gregtech/textures/items/metaitems/tool.multiblock_builder.png
Labels: type: feature

#1783 Remove the deprecated onAttached
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
Labels: type: refactor

#1784 Add method to un-ignore materials for OrePrefixes
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
Labels: type: feature

#1785 Fix food being consumed in creative mode
  src/main/java/gregtech/api/items/metaitem/FoodUseManager.java
Labels: type: bug

#1732 Hide repair tooltip on tools if Unbreakable
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
Labels: type: bug

#1764 Add fertilizer compat with EnderIO and Immersive Engineering
  src/api/java/blusunrize/immersiveengineering/api/tool/BelljarHandler.java
  src/api/java/crazypants/enderio/api/farm/IFertilizer.java
  src/api/java/crazypants/enderio/base/farming/fertilizer/Bonemeal.java
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/integration/IntegrationModule.java
  src/main/java/gregtech/modules/GregTechModules.java
Labels: type: feature

#1790 Move to new JEI maven
  build.gradle
Labels: ignore changelog

#1789 Fix Robot Arm not respecting certain Filters
  src/main/java/gregtech/common/covers/CoverRoboticArm.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: bug

#1787 Add jabel for Java17 syntax
  .github/workflows/pr_artifact.yml
  .github/workflows/pr_testing.yml
  .github/workflows/publish.yml
  .github/workflows/update_gradle_cache.yml
  build.gradle
  gradle.properties
  src/test/java/jabel/TestModernJavaSyntax.java
Labels: ignore changelog

#1786 Fix toSmallDigits converting isotopes into small numbers
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/stack/MaterialStack.java
  src/main/java/gregtech/api/util/SmallDigits.java
  src/test/java/gregtech/api/util/SmallDigitsTest.java
Labels: type: bug

#1793 Moves current mod integrations to modules
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/gui/widgets/RecipeProgressWidget.java
  src/main/java/gregtech/api/modules/GregTechModule.java
  src/main/java/gregtech/api/modules/IGregTechModule.java
  src/main/java/gregtech/api/modules/ModuleStage.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/terminal/TerminalRegistry.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/command/CommandHand.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/common/terminal/app/recipechart/widget/RGNode.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/integration/IntegrationModule.java
  src/main/java/gregtech/integration/IntegrationSubmodule.java
  src/main/java/gregtech/integration/RecipeCompatUtil.java
  src/main/java/gregtech/integration/crafttweaker/CTRecipeHelper.java
  src/main/java/gregtech/integration/crafttweaker/CraftTweakerModule.java
  src/main/java/gregtech/integration/crafttweaker/block/CTHeatingCoilBlockStats.java
  src/main/java/gregtech/integration/crafttweaker/item/CTItemRegistry.java
  src/main/java/gregtech/integration/crafttweaker/material/CTMaterialBuilder.java
  src/main/java/gregtech/integration/crafttweaker/material/CTMaterialHelpers.java
  src/main/java/gregtech/integration/crafttweaker/material/MaterialBracketHandler.java
  src/main/java/gregtech/integration/crafttweaker/material/MaterialExpansion.java
  src/main/java/gregtech/integration/crafttweaker/material/MaterialPropertyExpansion.java
  src/main/java/gregtech/integration/crafttweaker/recipe/CTNBTMatcher.java
  src/main/java/gregtech/integration/crafttweaker/recipe/CTNBTMultiItemMatcher.java
  src/main/java/gregtech/integration/crafttweaker/recipe/CTRecipe.java
  src/main/java/gregtech/integration/crafttweaker/recipe/CTRecipeBuilder.java
  src/main/java/gregtech/integration/crafttweaker/recipe/CTRecipeUtils.java
  src/main/java/gregtech/integration/crafttweaker/recipe/CTUtilities.java
  src/main/java/gregtech/integration/crafttweaker/recipe/ChancedEntry.java
  src/main/java/gregtech/integration/crafttweaker/recipe/InputIngredient.java
  src/main/java/gregtech/integration/crafttweaker/recipe/MetaItemBracketHandler.java
  src/main/java/gregtech/integration/crafttweaker/recipe/MetaTileEntityBracketHandler.java
  src/main/java/gregtech/integration/crafttweaker/recipe/RecipeMapBracketHandler.java
  src/main/java/gregtech/integration/crafttweaker/terminal/CTTerminalRegistry.java
  src/main/java/gregtech/integration/groovy/GrSRecipeHelper.java
  src/main/java/gregtech/integration/groovy/GroovyHandCommand.java
  src/main/java/gregtech/integration/groovy/GroovyMaterialBuilderExpansion.java
  src/main/java/gregtech/integration/groovy/GroovyScriptModule.java
  src/main/java/gregtech/integration/groovy/VirtualizedRecipeMap.java
  src/main/java/gregtech/integration/jei/JEIOptional.java
  src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/integration/jei/recipe/IntCircuitCategory.java
  src/main/java/gregtech/integration/jei/recipe/RecipeMapCategory.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeModule.java
  src/main/java/gregtech/modules/GregTechModules.java
  src/main/java/gregtech/modules/ModuleManager.java
  src/test/java/gregtech/Bootstrap.java
Labels: type: refactor

#1794 OpenComputers module
  README.md
  build.gradle
  gradle.properties
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/integration/IntegrationUtil.java
  src/main/java/gregtech/integration/opencomputers/InputValidator.java
  src/main/java/gregtech/integration/opencomputers/OpenComputersModule.java
  src/main/java/gregtech/integration/opencomputers/drivers/DriverAbstractRecipeLogic.java
  src/main/java/gregtech/integration/opencomputers/drivers/DriverEnergyContainer.java
  src/main/java/gregtech/integration/opencomputers/drivers/DriverICoverable.java
  src/main/java/gregtech/integration/opencomputers/drivers/DriverRecipeMapMultiblockController.java
  src/main/java/gregtech/integration/opencomputers/drivers/DriverSimpleMachine.java
  src/main/java/gregtech/integration/opencomputers/drivers/DriverWorkable.java
  src/main/java/gregtech/integration/opencomputers/drivers/EnvironmentMetaTileEntity.java
  src/main/java/gregtech/integration/opencomputers/drivers/specific/DriverConverter.java
  src/main/java/gregtech/integration/opencomputers/drivers/specific/DriverFusionReactor.java
  src/main/java/gregtech/integration/opencomputers/drivers/specific/DriverWorldAccelerator.java
  src/main/java/gregtech/integration/opencomputers/values/ValueCoverBehavior.java
  src/main/java/gregtech/integration/opencomputers/values/ValueCoverConveyor.java
  src/main/java/gregtech/integration/opencomputers/values/ValueCoverEnderFluidLink.java
  src/main/java/gregtech/integration/opencomputers/values/ValueCoverFluidFilter.java
  src/main/java/gregtech/integration/opencomputers/values/ValueCoverFluidRegulator.java
  src/main/java/gregtech/integration/opencomputers/values/ValueCoverItemFilter.java
  src/main/java/gregtech/integration/opencomputers/values/ValueCoverPump.java
  src/main/java/gregtech/integration/opencomputers/values/ValueCoverRoboticArm.java
  src/main/java/gregtech/modules/GregTechModules.java
Labels: type: feature

#1791 Fusion Reactors lose heat when paused
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
Labels: type: bug

#1799 Give GTFO 500 more material IDs
  src/main/java/gregtech/api/unification/material/Materials.java
Labels: ignore changelog

#1742 Apply recipe modifications in dedicated stages
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/FuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/HeatingCoilRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/PrimitiveRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/RecipeLogicSteam.java
  src/main/java/gregtech/api/recipes/logic/OverclockingLogic.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCrackingUnit.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPyrolyseOven.java
  src/test/java/gregtech/api/capability/impl/MultiblockRecipeLogicTest.java
  src/test/java/gregtech/api/recipes/logic/OverclockingTest.java
Labels: type: refactor

#1798 Support for increasing cracking unit item inputs
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapCrackerUnit.java
Labels: type: feature

#1792 Wood property
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/api/unification/material/materials/UnknownCompositionMaterials.java
  src/main/java/gregtech/api/unification/material/properties/BlastProperty.java
  src/main/java/gregtech/api/unification/material/properties/DustProperty.java
  src/main/java/gregtech/api/unification/material/properties/FluidPipeProperties.java
  src/main/java/gregtech/api/unification/material/properties/FluidProperty.java
  src/main/java/gregtech/api/unification/material/properties/GemProperty.java
  src/main/java/gregtech/api/unification/material/properties/IMaterialProperty.java
  src/main/java/gregtech/api/unification/material/properties/IngotProperty.java
  src/main/java/gregtech/api/unification/material/properties/ItemPipeProperties.java
  src/main/java/gregtech/api/unification/material/properties/MaterialProperties.java
  src/main/java/gregtech/api/unification/material/properties/OreProperty.java
  src/main/java/gregtech/api/unification/material/properties/PlasmaProperty.java
  src/main/java/gregtech/api/unification/material/properties/PolymerProperty.java
  src/main/java/gregtech/api/unification/material/properties/PropertyKey.java
  src/main/java/gregtech/api/unification/material/properties/RotorProperty.java
  src/main/java/gregtech/api/unification/material/properties/ToolProperty.java
  src/main/java/gregtech/api/unification/material/properties/WireProperties.java
  src/main/java/gregtech/api/unification/material/properties/WoodProperty.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/client/renderer/pipe/FluidPipeRenderer.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityDrum.java
  src/main/java/gregtech/loaders/recipe/handlers/PipeRecipeHandler.java
Labels: type: refactor

#1765 Add flag for double plates
  src/main/java/gregtech/api/unification/material/info/MaterialFlags.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/loaders/recipe/handlers/PartsRecipeHandler.java
Labels: type: feature

#1803 simplify codeowners
  CODEOWNERS
Labels: ignore changelog

#1804 clean up MetaPrefixItem internals
  src/main/java/gregtech/api/items/materialitem/MetaPrefixItem.java
  src/main/java/gregtech/api/util/GTStringUtils.java
  src/main/java/gregtech/common/command/CommandRecipeCheck.java
Labels: type: refactor

#1194 Rework Prospector Map
  build.gradle
  gradle.properties
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/gui/widgets/LabelWidget.java
  src/main/java/gregtech/api/terminal/TerminalRegistry.java
  src/main/java/gregtech/api/worldgen/bedrockFluids/ChunkPosDimension.java
  src/main/java/gregtech/common/items/behaviors/ProspectorScannerBehavior.java
  src/main/java/gregtech/common/terminal/app/prospector/ProspectingTexture.java
  src/main/java/gregtech/common/terminal/app/prospector/ProspectorApp.java
  src/main/java/gregtech/common/terminal/app/prospector/ProspectorMode.java
  src/main/java/gregtech/common/terminal/app/prospector/widget/WidgetOreList.java
  src/main/java/gregtech/common/terminal/app/prospector/widget/WidgetProspectingMap.java
  src/main/java/gregtech/core/network/packets/PacketProspecting.java
  src/main/java/gregtech/integration/xaero/ColorUtility.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1806 Migrate to GregTechCEu/Buildscripts
  build.gradle
  dependencies.gradle
Labels: ignore changelog

#1808 Update to latest buildscript
  build.gradle
  dependencies.gradle
  gradle.properties
  settings.gradle
Labels: ignore changelog

#1807 Track repetitions for each aisle in multiblocks
  src/main/java/gregtech/api/pattern/BlockPattern.java
Labels: type: feature

#1810 fix multi smelter energy consumption
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiSmelter.java
Labels: type: bug

#1809 Add CI job to auto-update buildscript
  .github/workflows/update_buildscript.yml
  build.gradle
  gradle.properties
  settings.gradle
Labels: ignore changelog

#1796 Stop using GNU Trove collections
  dependencies.gradle
  src/main/java/gregtech/api/capability/impl/ItemHandlerList.java
  src/main/java/gregtech/api/items/metaitem/MetaOreDictItem.java
  src/main/java/gregtech/api/pipenet/PipeNet.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/worldgen/generator/CachedGridEntry.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMagicEnergyAbsorber.java
Labels: type: refactor

#1741 Multiblock Energy Input Changes
  src/main/java/gregtech/api/capability/impl/EnergyContainerHandler.java
  src/main/java/gregtech/api/capability/impl/EnergyContainerList.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/test/java/gregtech/api/capability/impl/EnergyContainerListTest.java
Labels: type: bug

#1813 Update to latest
  build.gradle
  dependencies.gradle
  gradle.properties
Labels: ignore changelog
