Repository GregTechCEu/GregTech, pull requests merged in 2023-01, with the labels that each got.

#1339 Fix server-side sound registration problems from #1285
  src/main/java/gregtech/core/sound/internal/SoundManager.java
Labels: type: bug, ignore changelog

#1351 fix missing SideOnly annotations from tools PR
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: ignore changelog

#1349 fix tools applying incompatible enchantments
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/items/toolitem/ItemGTSword.java
  src/main/java/gregtech/api/items/toolitem/ItemGTTool.java
  src/main/java/gregtech/common/items/ToolItems.java
Labels: ignore changelog

#1360 Fix harder vanilla tool recipes conflicts
  src/main/java/gregtech/loaders/recipe/VanillaOverrideRecipes.java
Labels: ignore changelog

#1359 Fix tool crafting repair
  src/main/java/gregtech/asm/GregTechTransformer.java
  src/main/java/gregtech/asm/hooks/RecipeRepairItemHooks.java
  src/main/java/gregtech/asm/visitors/RecipeRepairItemVisitor.java
Labels: ignore changelog

#1348 Fix recycling recipe durations
  src/main/java/gregtech/loaders/recipe/RecyclingRecipes.java
Labels: type: bug

#1340 Fix FuelableInfoProvider calling client only method on server
  src/main/java/gregtech/api/util/GTStringUtils.java
  src/main/java/gregtech/integration/theoneprobe/provider/FuelableInfoProvider.java
Labels: type: bug

#1334 Change EBF preview to use LV energy hatches
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityElectricBlastFurnace.java
Labels: type: feature

#1346 improve logging for recipe conflicts
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/ingredients/GTRecipeOreInput.java
Labels: integration: CT, type: feature

#1361 fix anvil repairing
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: ignore changelog

#1356 Tool Stats and other fixes
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/items/toolitem/IGTToolDefinition.java
  src/main/java/gregtech/api/items/toolitem/ItemGTSword.java
  src/main/java/gregtech/api/items/toolitem/ItemGTTool.java
  src/main/java/gregtech/api/items/toolitem/ToolBuilder.java
  src/main/java/gregtech/api/items/toolitem/ToolDefinitionBuilder.java
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
  src/main/java/gregtech/api/unification/crafttweaker/MaterialPropertyExpansion.java
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/HigherDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/MaterialFlagAddition.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/properties/ToolProperty.java
  src/main/java/gregtech/client/utils/ToolChargeBarRenderer.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/ToolEventHandlers.java
  src/main/java/gregtech/common/items/ToolItems.java
  src/main/java/gregtech/loaders/recipe/chemistry/MixerRecipes.java
  src/main/java/gregtech/loaders/recipe/handlers/ToolRecipeHandler.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: ignore changelog

#1362 Fix full durability tool enchantment merging
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
Labels: ignore changelog

#1352 add custom death messages for each tool
  src/main/java/gregtech/api/damagesources/DamageSourceTool.java
  src/main/java/gregtech/api/damagesources/DamageSources.java
  src/main/java/gregtech/asm/GregTechTransformer.java
  src/main/java/gregtech/asm/visitors/DamageSourceVisitor.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: ignore changelog

#1367 add plunger, fix several behaviors
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/items/toolitem/ToolClasses.java
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
  src/main/java/gregtech/api/items/toolitem/behavior/IToolBehavior.java
  src/main/java/gregtech/common/items/ToolItems.java
  src/main/java/gregtech/common/items/tool/BlockRotatingBehavior.java
  src/main/java/gregtech/common/items/tool/PlungerBehavior.java
  src/main/java/gregtech/common/items/tool/RotateRailBehavior.java
  src/main/java/gregtech/loaders/recipe/handlers/ToolRecipeHandler.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/tools/plunger.json
  src/main/resources/assets/gregtech/textures/items/tools/handle_plunger.png
  src/main/resources/assets/gregtech/textures/items/tools/plunger.png
  src/main/resources/assets/gregtech/textures/items/tools/plunger_base.png
Labels: ignore changelog

#1369 Add CT support for full material fluidPipeProperties
  src/main/java/gregtech/api/unification/crafttweaker/CTMaterialBuilder.java
  src/main/java/gregtech/api/unification/material/Material.java
Labels: integration: CT, type: feature

#906 port some of GCP quests into Multiblocks Guide App
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/advanced_fluid_drilling_plant.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/advanced_processing_array.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/assembly_line.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/basic_fluid_drilling_rig.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/basic_ore_drilling_plant.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/electric_blast_furnace.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/fusion_reactor_1.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/fusion_reactor_2.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/fusion_reactor_3.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/implosion_compressor.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/large_chemical_reactor.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/large_miner.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/multi_smelter.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/oil_cracking_unit.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/processing_array.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/pyrolyse_oven.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/vacuum_freezer.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/extreme_combustion_engine.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/large_boiler.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/large_bronze_boiler.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/large_combustion_engine.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/large_gas_turbine.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/large_plasma_turbine.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/large_steam_turbine.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/large_steel_boiler.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/hatches/advanced_maintenance.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/hatches/energy_hatch.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/hatches/maintenance_hatch.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/hatches/muffler_hatch.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/hatches/multiblock_input_output.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/primitive/coke_oven.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/primitive/multiblock_steel_tank.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/primitive/multiblock_wooden_tank.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/primitive/primitive_water_pump.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/primitive/steam_grinder.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/primitive/steam_oven.json
  src/main/resources/assets/gregtech/terminal/guide/tutorials/en_us/multiblocks/forming_multiblocks.json
  src/main/resources/assets/gregtech/terminal/guide/tutorials/en_us/multiblocks/large_turbine_mechanics.json
  src/main/resources/assets/gregtech/terminal/guide/tutorials/en_us/multiblocks/multibock_troubleshooting.json
Labels: type: feature

#1372 Few Cleanups
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/advanced_fluid_drilling_plant.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/assembly_line.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/basic_ore_drilling_plant.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/distillation_tower.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/electric_blast_furnace.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/large_chemical_reactor.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/multi_smelter.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/processing_array.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/electric/pyrolyse_oven.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/large_bronze_boiler.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/large_combustion_engine.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/large_gas_turbine.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/large_steam_turbine.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/generator/large_steel_boiler.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/hatches/advanced_maintenance.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/hatches/energy_hatch.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/hatches/maintenance_hatch.json
  src/main/resources/assets/gregtech/terminal/guide/multiblocks/en_us/hatches/multiblock_input_output.json
  src/main/resources/assets/gregtech/terminal/guide/tutorials/en_us/multiblocks/large_turbine_mechanics.json
Labels: ignore changelog

#1338 Fix crash when distributing fluid through Shutter Cover
  src/main/java/gregtech/common/pipelike/fluidpipe/tile/TileEntityFluidPipeTickable.java
Labels: type: bug

#1358 Add a new paper recipe without stone slabs
  src/main/java/gregtech/integration/jei/GTJeiPlugin.java
  src/main/java/gregtech/integration/jei/utils/CustomItemReturnRecipeWrapper.java
  src/main/java/gregtech/loaders/recipe/CustomItemReturnShapedOreRecipeRecipe.java
  src/main/java/gregtech/loaders/recipe/VanillaOverrideRecipes.java
Labels: type: feature

#1368 enchantment work
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/asm/GregTechTransformer.java
  src/main/java/gregtech/asm/hooks/EnchantmentHooks.java
  src/main/java/gregtech/asm/visitors/EnchantmentCanApplyVisitor.java
  src/main/java/gregtech/tools/enchants/EnchantmentHardHammer.java
Labels: ignore changelog

#1290 Fix multiple miners in the same chunk conflicting
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
Labels: type: feature

#1289 TOP info improvements
  src/main/java/gregtech/integration/theoneprobe/provider/RecipeLogicInfoProvider.java
Labels: type: bug

#1375 fix Mending/Unbreaking being allowed on GT armor
  src/main/java/gregtech/api/items/armor/ArmorMetaItem.java
  src/main/java/gregtech/api/items/armor/IArmorLogic.java
Labels: type: bug

#1380 Change Energy Hatch in Cleanroom to LV in JEI Preview
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
Labels: type: bug

#1378 fix tool anvil repairing
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
Labels: ignore changelog

#1383 fix grid overlay not appearing in some cases
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: ignore changelog

#1387 GroovyScript compat fix
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/integration/GroovyScriptCompat.java
Labels: integration: CT, type: bug, integration: GrS

#1385 Isolate material tool harvest level from block level
  src/main/java/gregtech/api/items/materialitem/MetaPrefixItem.java
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/unification/crafttweaker/MaterialExpansion.java
  src/main/java/gregtech/api/unification/crafttweaker/MaterialPropertyExpansion.java
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/HigherDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/properties/ToolProperty.java
Labels: ignore changelog

#1357 Require one bucket for concrete crafting recipe
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/common/crafting/FluidReplaceRecipe.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
Labels: type: feature

#1388 Fix tool clicking on MTEs
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/cover/CoverBehavior.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/common/covers/CoverFluidVoiding.java
  src/main/java/gregtech/common/covers/CoverItemVoiding.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityHull.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityDrum.java
Labels: ignore changelog

#1389 Fix multi preview tooltips disappearing
  src/main/java/gregtech/integration/jei/multiblock/MultiblockInfoRecipeWrapper.java
Labels: ignore changelog

#1295 Small recipe tweaks
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/loaders/MaterialInfoLoader.java
  src/main/java/gregtech/loaders/recipe/CircuitRecipes.java
  src/main/java/gregtech/loaders/recipe/ComponentRecipes.java
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
  src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/VanillaOverrideRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/ReactorRecipes.java
  src/main/java/gregtech/loaders/recipe/handlers/PartsRecipeHandler.java
Labels: type: feature

#1370 fix crafting station "free neutronium tools bug"
  src/main/java/gregtech/common/metatileentities/storage/CachedRecipeData.java
Labels: type: bug

#1391 fix silk drop method handle
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
  src/main/java/gregtech/asm/util/ObfMapping.java
Labels: ignore changelog

#1382 Fix some issues with parallel logic
  src/main/java/gregtech/api/recipes/logic/ParallelLogic.java
  src/test/java/gregtech/api/recipes/logic/IParallelableRecipeLogicTest.java
Labels: type: bug

#1392 Only allow crafting tools in crafting station tool inventory
  src/main/java/gregtech/common/inventory/handlers/ToolItemStackHandler.java
Labels: type: feature

#1396 Save void mode and locked fluid for super tanks
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: type: feature

#1394 Fix BlockMachine ignoring MTE harvest tool/level
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
  src/main/java/gregtech/asm/GregTechTransformer.java
  src/main/java/gregtech/asm/hooks/TheOneProbeHooks.java
  src/main/java/gregtech/asm/visitors/TheOneProbeVisitor.java
  src/main/java/gregtech/common/items/behaviors/TricorderBehavior.java
Labels: type: bug

#1374 Some optimizations
  src/main/java/gregtech/api/capability/impl/FluidTankList.java
  src/main/java/gregtech/api/recipes/ingredients/CraftTweakerItemInputWrapper.java
  src/main/java/gregtech/api/util/GTHashMaps.java
  src/main/java/gregtech/api/util/GTTransferUtils.java
  src/main/java/gregtech/api/util/OverlayedFluidHandler.java
  src/main/java/gregtech/api/util/OverlayedItemHandler.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverFluidRegulator.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/covers/filter/FilterTypeRegistry.java
  src/main/java/gregtech/common/covers/filter/OreDictionaryItemFilter.java
  src/main/java/gregtech/common/covers/filter/SmartItemFilter.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeTank.java
Labels: type: refactor

#1377 Improve electric overlay colors
  src/main/java/gregtech/api/GTValues.java
Labels: type: feature

#1300 Fix a few issues with placing Pipes into Frames
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/common/blocks/BlockFrame.java
Labels: type: bug

#1397 Revert "set energy hatch limit to 2 (#1275)"
  src/main/java/gregtech/api/metatileentity/multiblock/MultiMapMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDistillationTower.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/common/metatileentities/multi/electric/centralmonitor/MetaTileEntityCentralMonitor.java
Labels: ignore changelog

#1398 Return instead of throwing if a non-neighbor calls neighborChanged
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
Labels: type: bug

#1395 bug(multiblocks):fixed large miners using 7 eu/t
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
Labels: type: bug

#1384 feat(multiblocks):rebalanced multiblock explosions to be based off voltage
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityEnergyHatch.java
Labels: type: feature

#1400 Fix crash when damaging tools with null players
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
Labels: ignore changelog

#1404 Fix buzzsaw crafting component
  src/main/java/gregtech/loaders/recipe/CraftingComponent.java
Labels: ignore changelog

#1401 Tool property builder, magnetic stat
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/unification/crafttweaker/CTMaterialBuilder.java
  src/main/java/gregtech/api/unification/crafttweaker/MaterialPropertyExpansion.java
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/HigherDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/MaterialFlagAddition.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/properties/ToolProperty.java
Labels: ignore changelog

#1402 Treefelling fixes
  src/main/java/gregtech/api/items/toolitem/TreeFellingListener.java
Labels: ignore changelog

#1399 Entity damage boost behavior
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/common/items/ToolItems.java
  src/main/java/gregtech/common/items/tool/EntityDamageBehavior.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: ignore changelog

#1405 Convert tool behaviors to singletons where possible
  src/main/java/gregtech/common/items/ToolItems.java
  src/main/java/gregtech/common/items/tool/BlockRotatingBehavior.java
  src/main/java/gregtech/common/items/tool/DisableShieldBehavior.java
  src/main/java/gregtech/common/items/tool/GrassPathBehavior.java
  src/main/java/gregtech/common/items/tool/HarvestCropsBehavior.java
  src/main/java/gregtech/common/items/tool/HarvestIceBehavior.java
  src/main/java/gregtech/common/items/tool/HoeGroundBehavior.java
  src/main/java/gregtech/common/items/tool/PlungerBehavior.java
  src/main/java/gregtech/common/items/tool/RotateRailBehavior.java
  src/main/java/gregtech/common/items/tool/TorchPlaceBehavior.java
  src/main/java/gregtech/common/items/tool/TreeFellingBehavior.java
Labels: ignore changelog

#1406 Prevent decomposition of acids for hydrogen production
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/OrganicChemistryMaterials.java
Labels: type: bug

#1403 Fix tool head replace recipe
  src/main/java/gregtech/common/crafting/ToolHeadReplaceRecipe.java
Labels: ignore changelog

#1410 fix default tool material when no material is specified
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
Labels: type: bug

#1408 Rotor tooltip fix
  src/main/java/gregtech/common/items/behaviors/AbstractMaterialPartBehavior.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/lang/ja_jp.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: bug

#1412 Allow Groovyscript to use multiplication for MaterialStacks
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/integration/jei/GTOreInfo.java
Labels: type: feature, integration: GrS

#1418 Sound subtitles
  src/main/resources/assets/gregtech/sounds.json
Labels: type: feature

#1413 Minor lang changes regarding the terminal
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: ignore changelog

#1336 Refactor and expand HUD drawing to items
  src/main/java/gregtech/api/items/armor/ArmorLogicSuite.java
  src/main/java/gregtech/api/items/metaitem/stats/IItemHUDProvider.java
  src/main/java/gregtech/client/event/ClientEventHandler.java
  src/main/java/gregtech/common/items/armor/AdvancedJetpack.java
  src/main/java/gregtech/common/items/armor/AdvancedNanoMuscleSuite.java
  src/main/java/gregtech/common/items/armor/AdvancedQuarkTechSuite.java
  src/main/java/gregtech/common/items/armor/Jetpack.java
  src/main/java/gregtech/common/items/armor/NanoMuscleSuite.java
  src/main/java/gregtech/common/items/armor/NightvisionGoggles.java
  src/main/java/gregtech/common/items/armor/PowerlessJetpack.java
  src/main/java/gregtech/common/items/armor/QuarkTechSuite.java
Labels: type: feature

#1423 Allow full modification of BlastProperties via CT
  src/main/java/gregtech/api/unification/crafttweaker/MaterialPropertyExpansion.java
  src/main/java/gregtech/api/unification/material/properties/BlastProperty.java
Labels: integration: CT, type: feature

#1425 Change Advanced Jetpack to use Energium Crystal
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
Labels: type: feature

#1429 Zero initial EUt of multiplied parallel logic
  src/main/java/gregtech/api/recipes/logic/ParallelLogic.java
  src/test/java/gregtech/api/recipes/logic/ParallelLogicTest.java
Labels: type: bug

#1427 Copy NBT for GroovyScript removal recipes
  src/main/java/gregtech/integration/GroovyScriptCompat.java
Labels: type: bug

#1333 Add some more info to the 2.0.0 changelog
  CHANGELOG-GTCEU.md
Labels: ignore changelog

#1453 Fix crash with getMobDamage()
  src/main/java/gregtech/api/damagesources/DamageSources.java
Labels: type: bug

#1444 Fix Behavior tag getting applied to non-tools
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: type: bug

#1424 Reimplement some Crowbar behavior
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/common/blocks/BlockFrame.java
Labels: type: bug

#1390 Refactor and cleanup ModHandler
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/ItemStackHashStrategy.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/loaders/recipe/VanillaOverrideRecipes.java
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
  src/main/java/gregtech/loaders/recipe/WoodMachineRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/SeparationRecipes.java
  src/main/java/gregtech/loaders/recipe/handlers/MaterialRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/OreRecipeHandler.java
  src/test/java/gregtech/Bootstrap.java
Labels: type: refactor

#1196 Add Assembly Line lasers
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
Labels: type: feature

#1455 Add tick check to terminal ar scanning
  src/main/java/gregtech/common/items/behaviors/TerminalBehaviour.java
Labels: type: bug

#1460 Do not allow inventory repair for two full durability tools
  src/main/java/gregtech/asm/hooks/RecipeRepairItemHooks.java
Labels: type: bug
