Repository GregTechCEu/GregTech, pull requests merged in 2023-09, with the labels that each got.

#2064 Fix TextFieldWidget2 not focusing the gui
  src/main/java/gregtech/api/gui/widgets/TextFieldWidget2.java
Labels: type: bug

#2061 fix item and fluid hatch working toggle
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityFluidHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
Labels: type: bug

#2059 Fix grs hard dep
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: type: bug, integration: GrS

#2044 Update ja_JP lang for 2.7.3
  src/main/resources/assets/gregtech/lang/ja_jp.lang
Labels: type: translation

#2065 fix pipe tool click with offhand shield
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/common/EventHandlers.java
Labels: type: bug

#2043 Rename getId() in IGTTool to restore SpongeForge Compability
  src/main/java/gregtech/api/damagesources/DamageSources.java
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/items/toolitem/ItemGTAxe.java
  src/main/java/gregtech/api/items/toolitem/ItemGTHoe.java
  src/main/java/gregtech/api/items/toolitem/ItemGTSword.java
  src/main/java/gregtech/api/items/toolitem/ItemGTTool.java
  src/main/java/gregtech/loaders/recipe/handlers/ToolRecipeHandler.java
Labels: type: bug

#1933 separate MarkerMaterial from OreDictUnifier
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/unification/OreDictUnifier.java
  src/main/java/gregtech/api/unification/material/MarkerMaterial.java
  src/main/java/gregtech/api/unification/material/MarkerMaterials.java
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/api/unification/material/registry/MarkerMaterialRegistry.java
  src/main/java/gregtech/core/CoreModule.java
  src/test/java/gregtech/Bootstrap.java
Labels: type: refactor

#1937 Remove scheduled deprecations
  src/main/java/gregtech/GregTechVersion.java
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/block/DelayedStateBlock.java
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/capability/IFuelInfo.java
  src/main/java/gregtech/api/capability/IThermalFluidHandlerItemStack.java
  src/main/java/gregtech/api/capability/impl/AbstractFuelInfo.java
  src/main/java/gregtech/api/capability/impl/FilteredFluidHandler.java
  src/main/java/gregtech/api/capability/impl/FluidFuelInfo.java
  src/main/java/gregtech/api/capability/impl/ItemFuelInfo.java
  src/main/java/gregtech/api/capability/impl/NotifiableFluidTankFromList.java
  src/main/java/gregtech/api/capability/impl/SimpleThermalFluidHandlerItemStack.java
  src/main/java/gregtech/api/capability/impl/ThermalFluidHandlerItemStack.java
  src/main/java/gregtech/api/items/metaitem/FilteredFluidStats.java
  src/main/java/gregtech/api/items/metaitem/ThermalFluidStats.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/unification/OreDictUnifier.java
  src/main/java/gregtech/api/unification/stack/WildcardAwareHashMap.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/OreDictExprFilter.java
  src/main/java/gregtech/client/renderer/handler/MetaTileEntityRenderer.java
  src/test/java/gregtech/api/capability/impl/MultiblockRecipeLogicTest.java
  src/test/java/gregtech/api/recipes/logic/IParallelableRecipeLogicTest.java
  src/test/java/gregtech/api/recipes/logic/ParallelLogicTest.java
Labels: type: refactor

#2055 Add method to modify material amount for OrePrefixes
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
Labels: integration: CT, type: feature

#1962 Rewrite FluidTooltipUtil
  src/main/java/gregtech/api/fluids/MaterialFluid.java
  src/main/java/gregtech/api/fluids/MetaFluids.java
  src/main/java/gregtech/api/fluids/fluidType/FluidType.java
  src/main/java/gregtech/api/fluids/fluidType/FluidTypeAcid.java
  src/main/java/gregtech/api/util/FluidTooltipUtil.java
  src/main/java/gregtech/client/ClientProxy.java
Labels: type: bug

#2047 Fix MultiRecipeMap localize on TOP
  src/main/java/gregtech/integration/theoneprobe/provider/MultiRecipeMapInfoProvider.java
Labels: integration: TOP, type: bug

#2083 Fix minor tooltip issue
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityLongDistanceEndpoint.java
Labels: type: bug

#2075 Cleanup and fix loot table injection
  src/main/java/gregtech/loaders/dungeon/ChestGenHooks.java
Labels: type: bug

#2019 Wrap Forge ItemStackHandler
  src/main/java/gregtech/api/capability/impl/FilteredItemHandler.java
  src/main/java/gregtech/api/capability/impl/GhostCircuitItemStackHandler.java
  src/main/java/gregtech/api/capability/impl/NotifiableItemStackHandler.java
  src/main/java/gregtech/api/gui/widgets/GhostCircuitSlotWidget.java
  src/main/java/gregtech/api/items/itemhandlers/GTItemStackHandler.java
  src/main/java/gregtech/api/items/itemhandlers/InaccessibleItemStackHandler.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/WorkableTieredMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapPrimitiveMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapSteamMultiblockController.java
  src/main/java/gregtech/common/inventory/handlers/TapeItemStackHandler.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityBatteryBuffer.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityBlockBreaker.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityCharger.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityFisher.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityItemCollector.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMacerator.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMiner.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityPump.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityCokeOvenHatch.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPumpHatch.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/common/metatileentities/multi/electric/centralmonitor/MetaTileEntityMonitorScreen.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityDataAccessHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityFluidHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMachineHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityObjectHolder.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityPassthroughHatchFluid.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityPassthroughHatchItem.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityRotorHolder.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputBus.java
  src/main/java/gregtech/common/metatileentities/steam/SteamAlloySmelter.java
  src/main/java/gregtech/common/metatileentities/steam/SteamCompressor.java
  src/main/java/gregtech/common/metatileentities/steam/SteamExtractor.java
  src/main/java/gregtech/common/metatileentities/steam/SteamFurnace.java
  src/main/java/gregtech/common/metatileentities/steam/SteamHammer.java
  src/main/java/gregtech/common/metatileentities/steam/SteamMacerator.java
  src/main/java/gregtech/common/metatileentities/steam/SteamMiner.java
  src/main/java/gregtech/common/metatileentities/steam/SteamRockBreaker.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamCoalBoiler.java
  src/main/java/gregtech/common/metatileentities/steam/multiblockpart/MetaTileEntitySteamHatch.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityBuffer.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCrate.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityLockedSafe.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
  src/main/java/gregtech/integration/jei/recipe/RecipeMapCategory.java
Labels: type: bug

#2072 More decorative blocks
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/blocks/BlockColored.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/loaders/recipe/DecorationRecipes.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/resources/assets/gregtech/blockstates/large_metal_sheet.json
  src/main/resources/assets/gregtech/blockstates/metal_sheet.json
  src/main/resources/assets/gregtech/blockstates/studs.json
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_black.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_blue.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_brown.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_cyan.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_gray.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_green.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_light_blue.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_light_gray.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_lime.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_magenta.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_orange.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_pink.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_purple.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_red.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_white.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/large_metalsheet_yellow.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_black.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_blue.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_brown.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_cyan.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_gray.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_green.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_light_blue.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_light_gray.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_lime.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_magenta.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_orange.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_pink.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_purple.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_red.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_white.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/metalsheet_yellow.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_black.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_blue.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_brown.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_cyan.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_gray.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_green.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_light_blue.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_light_gray.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_lime.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_magenta.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_orange.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_pink.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_purple.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_red.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_white.png
  src/main/resources/assets/gregtech/textures/blocks/decoration/studs_yellow.png
Labels: type: feature

#2084 CCQuad fix
  src/main/java/gregtech/client/renderer/handler/FacadeRenderer.java
Labels: type: bug

#2090 fix recurseIngredientTreeAdd returning true on conflicts
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: type: bug

#1713 Pipe fixes
  src/main/java/gregtech/api/pipenet/PipeGatherer.java
  src/main/java/gregtech/api/pipenet/PipeNetWalker.java
  src/main/java/gregtech/common/pipelike/cable/net/EnergyNetWalker.java
  src/main/java/gregtech/common/pipelike/cable/tile/AveragingPerTickCounter.java
  src/main/java/gregtech/common/pipelike/cable/tile/PerTickLongCounter.java
  src/main/java/gregtech/common/pipelike/cable/tile/TileEntityCable.java
  src/main/java/gregtech/common/pipelike/itempipe/net/ItemNetHandler.java
  src/main/java/gregtech/common/pipelike/itempipe/net/ItemNetWalker.java
  src/main/java/gregtech/common/pipelike/itempipe/tile/TileEntityItemPipe.java
  src/main/java/gregtech/common/pipelike/itempipe/tile/TileEntityItemPipeTickable.java
  src/main/java/gregtech/common/pipelike/laser/net/LaserNetWalker.java
  src/main/java/gregtech/common/pipelike/optical/net/OpticalNetWalker.java
Labels: type: bug, type: refactor

#2091 Tile entity sync fixes
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/metatileentity/SyncedTileEntityBase.java
  src/main/java/gregtech/api/network/PacketDataList.java
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverDigitalInterface.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/pipelike/cable/tile/TileEntityCable.java
Labels: type: bug, type: refactor

#2094 Allow recipe properties to individually hide default tooltips
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/recipeproperties/EmptyRecipePropertyStorage.java
  src/main/java/gregtech/api/recipes/recipeproperties/IRecipePropertyStorage.java
  src/main/java/gregtech/api/recipes/recipeproperties/PrimitiveProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/RecipeProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/RecipePropertyStorage.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
Labels: type: refactor
