Repository GregTechCEu/GregTech, pull requests merged in 2023-10, with the labels that each got.

#2095 fix network switch stack overflow
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityNetworkSwitch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityComputationHatch.java
  src/main/java/gregtech/common/pipelike/optical/net/OpticalNetHandler.java
Labels: type: bug

#2076 fix ARL being dependency of IParallelableRecipeLogic
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/FuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/recipes/logic/IParallelableRecipeLogic.java
  src/test/java/gregtech/api/recipes/logic/IParallelableRecipeLogicTest.java
Labels: type: refactor

#2086 Allow multiblock controllers to determine weather resistance of multiblock parts
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiblockPart.java
Labels: type: feature

#2082 Laser Overhaul
  src/main/java/gregtech/api/capability/ILaserContainer.java
  src/main/java/gregtech/api/capability/impl/ActiveTransformerWrapper.java
  src/main/java/gregtech/api/capability/impl/LaserContainerHandler.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityActiveTransformer.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPowerSubstation.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityLaserHatch.java
  src/main/java/gregtech/common/pipelike/laser/net/LaserNetHandler.java
  src/main/java/gregtech/common/pipelike/laser/tile/TileEntityLaserPipe.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeModule.java
  src/main/java/gregtech/integration/theoneprobe/provider/LaserContainerInfoProvider.java
  src/main/java/gregtech/loaders/recipe/ComputerRecipes.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: status: high priority, type: refactor

#2104 Fix a few circuit textures
  src/main/resources/assets/gregtech/textures/items/metaitems/circuit.nano_assembly.png
  src/main/resources/assets/gregtech/textures/items/metaitems/circuit.nano_computer.png
  src/main/resources/assets/gregtech/textures/items/metaitems/circuit.quantum_computer.png
  src/main/resources/assets/gregtech/textures/items/metaitems/circuit.wetware_assembly.png
  src/main/resources/assets/gregtech/textures/items/metaitems/circuit.wetware_computer.png
Labels: type: refactor

#2103 Stricter Optical/Laser cable connections
  src/main/java/gregtech/api/pipenet/tile/IPipeTile.java
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
  src/main/java/gregtech/common/pipelike/laser/tile/TileEntityLaserPipe.java
  src/main/java/gregtech/common/pipelike/optical/tile/TileEntityOpticalPipe.java
Labels: type: feature

#2097 Research station logic improvement
  src/main/java/gregtech/api/capability/impl/ComputationRecipeLogic.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/builders/AssemblyLineRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/ComputationRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/ResearchRecipeBuilder.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapCokeOven.java
  src/main/java/gregtech/api/recipes/recipeproperties/TotalComputationProperty.java
  src/main/java/gregtech/api/util/AssemblyLineManager.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityResearchStation.java
  src/main/java/gregtech/integration/hwyla/provider/WorkableDataProvider.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/integration/theoneprobe/provider/WorkableInfoProvider.java
  src/main/java/gregtech/loaders/recipe/AssemblyLineLoader.java
  src/main/java/gregtech/loaders/recipe/BatteryRecipes.java
  src/main/java/gregtech/loaders/recipe/CircuitRecipes.java
  src/main/java/gregtech/loaders/recipe/ComponentRecipes.java
  src/main/java/gregtech/loaders/recipe/ComputerRecipes.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2036 fix quantum chest storage overflow
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
Labels: type: bug

#2113 fix PropertyMaterial value parsing failure
  src/main/java/gregtech/common/blocks/properties/PropertyMaterial.java
Labels: type: bug

#2109 Limit PA/APA to at most 4 energy hatches
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
Labels: type: refactor

#2106 More tooltip cleanup
  src/main/java/gregtech/common/pipelike/cable/ItemBlockCable.java
  src/main/java/gregtech/common/pipelike/fluidpipe/ItemBlockFluidPipe.java
  src/main/java/gregtech/common/pipelike/itempipe/ItemBlockItemPipe.java
  src/main/java/gregtech/common/pipelike/laser/ItemBlockLaserPipe.java
  src/main/java/gregtech/common/pipelike/optical/ItemBlockOpticalPipe.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: refactor

#2107 2.7 clarity touchups
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDataBank.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityNetworkSwitch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityLaserHatch.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: refactor

#2108 Fix passthrough hatches allowing IO on wrong sides
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityPassthroughHatchFluid.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityPassthroughHatchItem.java
Labels: type: bug

#2105 Multi fluid hatch additions and recipe changes
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiFluidHatch.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1549 Recipe input thingamabob
  src/main/java/gregtech/api/recipes/FluidCellInput.java
  src/main/java/gregtech/api/recipes/GTRecipeInputCache.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/ImplosionRecipeBuilder.java
  src/main/java/gregtech/api/recipes/ingredients/GTRecipeFluidInput.java
  src/main/java/gregtech/api/recipes/ingredients/GTRecipeInput.java
  src/main/java/gregtech/api/recipes/ingredients/GTRecipeItemInput.java
  src/main/java/gregtech/api/recipes/ingredients/GTRecipeOreInput.java
  src/main/java/gregtech/api/recipes/ingredients/IntCircuitIngredient.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapFluidCanner.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapFormingPress.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityLockedSafe.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/integration/crafttweaker/recipe/CTRecipeBuilder.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
Labels: type: feature

#2120 fix some multiblocks requiring maintenance hatches regardless of config
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityHPCA.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityNetworkSwitch.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPowerSubstation.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityResearchStation.java
Labels: type: bug

#2100 Fixes Muffler Hatch mechanics
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
Labels: type: bug

#2114 Update ru_ru lang for 2.7.4
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: type: translation

#2123 Update ja_JP lang for 2.7.4
  src/main/resources/assets/gregtech/lang/ja_jp.lang
Labels: type: translation

#2125 Add PBF advancement
  src/main/resources/assets/gregtech/advancements/steam/13_steel.json
  src/main/resources/assets/gregtech/advancements/steam/91_primitive_blast_furnace.json
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2124 Allow right-click with bucket on Coke Oven
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityCokeOven.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityCokeOvenHatch.java
Labels: type: feature

#2085 Make naqline net zero on fluorine
  src/main/java/gregtech/loaders/recipe/chemistry/NaquadahRecipes.java
Labels: type: bug

#2130 Fix fusion not losing heat when not active
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
Labels: type: bug

#2129 Allow fusion glass to replace output buses/energy hatches
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
Labels: type: feature

#2127 Config for num multiblock casings per craft
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/loaders/MaterialInfoLoader.java
  src/main/java/gregtech/loaders/recipe/ComputerRecipes.java
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/AssemblerRecipeLoader.java
Labels: type: feature

#2137 Add a few midgame recipes
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/MixerRecipes.java
Labels: type: feature
