Repository GregTechCEu/GregTech, pull requests merged in 2023-12, with the labels that each got.

#2238 Reimplement alternative fluid names
  src/main/java/gregtech/api/fluids/FluidBuilder.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/OrganicChemistryMaterials.java
  src/main/java/gregtech/api/unification/material/materials/UnknownCompositionMaterials.java
Labels: type: bug

#2240 Add default fluid state for storage key
  src/main/java/gregtech/api/fluids/FluidBuilder.java
  src/main/java/gregtech/api/fluids/store/FluidStorageKey.java
  src/main/java/gregtech/api/fluids/store/FluidStorageKeys.java
Labels: type: refactor

#2237 Fix manual fluid generation issues
  src/main/java/gregtech/api/fluids/store/FluidStorage.java
Labels: type: bug

#2232 Fix a missed advancement with the new coil
  src/main/resources/assets/gregtech/advancements/insane_voltage/58_hss_g_coil.json
Labels: type: bug

#2233 Exclude scala modules from classpath
  .editorconfig
  dependencies.gradle
Labels: ignore changelog

#2225 update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#2224 Fix Fluid Drilling Rig sometimes drilling on the incorrect vein
  src/main/java/gregtech/api/capability/impl/FluidDrillLogic.java
Labels: type: bug

#2241 Fix warning with cinnabar
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
Labels: type: bug

#2228 Fix Processing Array of Canners not processing some fluid
  src/main/java/gregtech/api/recipes/machines/RecipeMapFluidCanner.java
Labels: type: bug

#2229 Fix Issues with Multiblock Generators
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/LargeTurbineWorkableHandler.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeCombustionEngine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiblockNotifiablePart.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityRotorHolder.java
Labels: type: bug

#2242 fix fluid colors in TOP with new fluid system
  src/main/java/gregtech/api/fluids/FluidBuilder.java
Labels: type: bug

#2239 Update build script version to 1701481996
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  settings.gradle
Labels: ignore changelog

#2227 Update ja_jp.lang for 2.8.1
  src/main/resources/assets/gregtech/lang/ja_jp.lang
Labels: type: translation

#2244 Add FluidStorageKey ctor for compat
  src/main/java/gregtech/api/fluids/store/FluidStorageKey.java
Labels: ignore changelog

#2253 fix using client only method for harder bed recipe names
  src/main/java/gregtech/loaders/recipe/VanillaOverrideRecipes.java
Labels: type: bug

#2256 Fix plasma temps all being the default temp
  src/main/java/gregtech/api/fluids/FluidBuilder.java
Labels: type: bug

#2251 Re-implement walking speed bonus
  src/main/java/gregtech/api/block/IWalkingSpeedBonus.java
  src/main/java/gregtech/api/block/VariantActiveBlock.java
  src/main/java/gregtech/api/block/VariantBlock.java
  src/main/java/gregtech/api/util/BlockUtility.java
  src/main/java/gregtech/common/EventHandlers.java
  src/main/java/gregtech/common/blocks/BlockAsphalt.java
  src/main/java/gregtech/common/blocks/BlockBatteryPart.java
  src/main/java/gregtech/common/blocks/BlockColored.java
  src/main/java/gregtech/common/blocks/BlockSteamCasing.java
  src/main/java/gregtech/common/blocks/BlockWireCoil.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/blocks/StoneVariantBlock.java
  src/main/java/gregtech/core/CoreModule.java
Labels: type: refactor

#2255 Rework Generators 2.0 ™️
  src/main/java/gregtech/api/capability/impl/FuelRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/SimpleGeneratorMetaTileEntity.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeCombustionEngine.java
Labels: type: bug

#2262 Fix issues with ore byproduct page
  src/main/java/gregtech/integration/jei/basic/OreByProduct.java
  src/main/java/gregtech/integration/jei/basic/OreByProductCategory.java
Labels: type: bug

#2264 ModularUI setup
  dependencies.gradle
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/cover/CoverUIFactory.java
  src/main/java/gregtech/api/cover/CoverWithUI.java
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/java/gregtech/api/gui/package-info.java
  src/main/java/gregtech/api/items/gui/ItemUIFactory.java
  src/main/java/gregtech/api/items/gui/PlayerInventoryUIFactory.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityUIFactory.java
  src/main/java/gregtech/api/mui/GTGuiTextures.java
  src/main/java/gregtech/api/mui/GTGuiTheme.java
  src/main/java/gregtech/api/mui/GTGuis.java
  src/main/java/gregtech/api/mui/GregTechGuiScreen.java
  src/main/java/gregtech/common/covers/CoverStorage.java
  src/main/java/gregtech/common/gui/package-info.java
  src/main/java/gregtech/common/items/behaviors/IntCircuitBehaviour.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCrate.java
  src/main/java/gregtech/core/CoreModule.java
Labels: type: refactor

#2263 editorconfig edit
  .editorconfig
Labels: ignore changelog

#2265 Add MUI and mixinbooter to CF mod deps
  gradle.properties
Labels: ignore changelog

#2268 Fix fluid output trim losing some fluids
  src/main/java/gregtech/api/recipes/Recipe.java
Labels: type: bug

#2266 MUI for multiblock I/O buses
  src/main/java/gregtech/api/mui/GTGuiTextures.java
  src/main/java/gregtech/api/mui/GTGuiTheme.java
  src/main/java/gregtech/api/mui/widget/GhostCircuitSlotWidget.java
  src/main/java/gregtech/common/items/behaviors/IntCircuitBehaviour.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/steam/multiblockpart/MetaTileEntitySteamItemBus.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/gui/widget/button.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_auto_collapse_overlay.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_x_overlay.png
Labels: type: feature

#2273 fix crash with fluid filters with null delegate containers
  src/main/java/gregtech/api/capability/impl/FluidHandlerDelegate.java
  src/main/java/gregtech/common/covers/CoverFluidFilter.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/pipelike/fluidpipe/longdistance/MetaTileEntityLDFluidEndpoint.java
Labels: type: bug

#2274 SideOnly for modular screen methods
  src/main/java/gregtech/api/cover/CoverWithUI.java
  src/main/java/gregtech/api/items/gui/ItemUIFactory.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/mui/GregTechGuiScreen.java
Labels: ignore changelog

#2275 update to groovyscript 0.7.1
  dependencies.gradle
Labels: ignore changelog

#2277 GuiTextures port (partial)
  src/main/java/gregtech/api/mui/GTGuiTextures.java
  src/main/java/gregtech/api/mui/GTGuiTheme.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
Labels: ignore changelog

#2276 Remove the GT Safe
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/client/renderer/texture/custom/SafeRenderer.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityLockedSafe.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/lang/ja_jp.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
  src/main/resources/assets/gregtech/loot_tables/chests/abandoned_safe_1.json
  src/main/resources/assets/gregtech/textures/blocks/storage/safe/base_bottom.png
  src/main/resources/assets/gregtech/textures/blocks/storage/safe/base_front.png
  src/main/resources/assets/gregtech/textures/blocks/storage/safe/base_side.png
  src/main/resources/assets/gregtech/textures/blocks/storage/safe/base_top.png
  src/main/resources/assets/gregtech/textures/blocks/storage/safe/door_back.png
  src/main/resources/assets/gregtech/textures/blocks/storage/safe/door_front.png
  src/main/resources/assets/gregtech/textures/blocks/storage/safe/door_side.png
  src/main/resources/assets/gregtech/textures/gui/progress_bar/progress_bar_unlock.png
Labels: type: feature, type: refactor

#2271 pull UI code out of RecipeMap
  src/main/java/gregtech/api/metatileentity/SimpleGeneratorMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/RecipeMapBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapAssemblyLine.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapCrackerUnit.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapFluidCanner.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapFormingPress.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapFurnace.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapResearchStation.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapScanner.java
  src/main/java/gregtech/api/recipes/ui/RecipeMapUI.java
  src/main/java/gregtech/api/recipes/ui/RecipeMapUIFunction.java
  src/main/java/gregtech/api/recipes/ui/impl/AssemblyLineUI.java
  src/main/java/gregtech/api/recipes/ui/impl/CokeOvenUI.java
  src/main/java/gregtech/api/recipes/ui/impl/CrackerUnitUI.java
  src/main/java/gregtech/api/recipes/ui/impl/DistillationTowerUI.java
  src/main/java/gregtech/api/recipes/ui/impl/FormingPressUI.java
  src/main/java/gregtech/api/recipes/ui/impl/ResearchStationUI.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java
  src/main/java/gregtech/integration/jei/recipe/RecipeMapCategory.java
Labels: type: refactor

#2279 fix data stick entry removal from AL
  src/main/java/gregtech/api/recipes/machines/RecipeMapAssemblyLine.java
Labels: type: bug

#2283 Fix Large Gas Turbine not displaying Max Voltage when fully spun up
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
Labels: type: bug

#2284 Remove forestry src/api class
  src/api/java/forestry/api/arboriculture/IToolGrafter.java
Labels: ignore changelog

#2282 Update build script version to 1702244235
  build.gradle
  gradle.properties
Labels: ignore changelog

#2287 Fix addFluid expansion method for GrS/CT
  src/main/java/gregtech/integration/crafttweaker/material/CTMaterialHelpers.java
  src/main/java/gregtech/integration/crafttweaker/material/MaterialPropertyExpansion.java
Labels: type: refactor

#2292 More tool compat
  src/api/java/mods/railcraft/api/items/IToolCrowbar.java
  src/api/java/mrtjp/projectred/api/IScrewdriver.java
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
Labels: type: feature

#2299 Fix silicon bee crash
  src/main/java/gregtech/integration/forestry/bees/GTBeeDefinition.java
Labels: type: bug

#2298 Fix using MV muffler in EBF JEI preview
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
Labels: type: bug, type: refactor

#2294 Allow specifying NBT matching on Research ItemStacks
  src/main/java/gregtech/api/recipes/builders/AssemblyLineRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/ResearchRecipeBuilder.java
  src/main/java/gregtech/api/util/AssemblyLineManager.java
Labels: type: bug

#2300 Attempt to clarify tooltip
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: ignore changelog

#2290 Chisel module
  dependencies.gradle
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/integration/chisel/ChiselModule.java
  src/main/java/gregtech/loaders/OreDictionaryLoader.java
  src/main/java/gregtech/modules/GregTechModules.java
Labels: type: feature

#2302 Fix pipe restrictor render on bottom face
  src/main/java/gregtech/client/renderer/pipe/PipeRenderer.java
Labels: type: bug

#2305 Fix battery slot charge flickering
  src/main/java/gregtech/api/capability/impl/EnergyContainerHandler.java
Labels: type: bug

#2286 Tweak muffler effect API
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/client/particle/VanillaParticleEffects.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
Labels: type: refactor

#2288 log incomplete packet reads in NetworkHandler
  src/main/java/gregtech/core/network/internal/NetworkHandler.java
Labels: type: feature

#2252 Fusion rebalancing
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/recipes/recipeproperties/FusionEUToStartProperty.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
  src/main/java/gregtech/loaders/recipe/FuelRecipes.java
  src/main/java/gregtech/loaders/recipe/FusionLoader.java
Labels: type: feature

#2306 Fix plasma temp NPE for plasma-only materials
  src/main/java/gregtech/api/fluids/FluidBuilder.java
  src/main/java/gregtech/api/fluids/store/FluidStorage.java
  src/main/java/gregtech/api/fluids/store/FluidStorageKey.java
  src/main/java/gregtech/api/fluids/store/FluidStorageKeys.java
  src/main/java/gregtech/loaders/recipe/RecyclingRecipes.java
Labels: type: bug

#2281 Port to MUI 2.4
  dependencies.gradle
  src/main/java/gregtech/api/cover/CoverWithUI.java
  src/main/java/gregtech/api/items/gui/ItemUIFactory.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/mui/GTGuiTextures.java
  src/main/java/gregtech/api/mui/GTGuiTheme.java
  src/main/java/gregtech/api/mui/GTGuis.java
  src/main/java/gregtech/api/mui/factory/CoverGuiFactory.java
  src/main/java/gregtech/api/mui/factory/MetaItemGuiFactory.java
  src/main/java/gregtech/api/mui/factory/MetaTileEntityGuiFactory.java
  src/main/java/gregtech/api/mui/widget/GhostCircuitSlotWidget.java
  src/main/java/gregtech/common/covers/CoverStorage.java
  src/main/java/gregtech/common/items/behaviors/IntCircuitBehaviour.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/steam/multiblockpart/MetaTileEntitySteamItemBus.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCrate.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/gui/base/background_popup.png
Labels: ignore changelog

#2296 Ore Dictionary Filter Update
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/java/gregtech/api/util/oreglob/OreGlob.java
  src/main/java/gregtech/api/util/oreglob/OreGlobCompiler.java
  src/main/java/gregtech/common/covers/filter/OreDictionaryItemFilter.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/OreGlobMessages.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/OreGlobParser.java
  src/main/java/gregtech/common/gui/widget/orefilter/OreFilterTestSlot.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/gui/widget/ore_filter/button_case_sensitive.png
  src/main/resources/assets/gregtech/textures/gui/widget/ore_filter/button_match_all.png
  src/test/java/gregtech/api/util/OreGlobTest.java
Labels: type: feature

#2303 invalidate pipenet routepaths on chunk unload
  src/main/java/gregtech/api/metatileentity/NeighborCacheTileEntityBase.java
  src/main/java/gregtech/api/pipenet/PipeNet.java
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
  src/main/java/gregtech/common/pipelike/cable/net/EnergyNet.java
  src/main/java/gregtech/common/pipelike/cable/tile/TileEntityCable.java
  src/main/java/gregtech/common/pipelike/itempipe/net/ItemPipeNet.java
  src/main/java/gregtech/common/pipelike/itempipe/tile/TileEntityItemPipe.java
  src/main/java/gregtech/common/pipelike/laser/net/LaserPipeNet.java
  src/main/java/gregtech/common/pipelike/laser/tile/TileEntityLaserPipe.java
  src/main/java/gregtech/common/pipelike/optical/net/OpticalPipeNet.java
  src/main/java/gregtech/common/pipelike/optical/tile/TileEntityOpticalPipe.java
Labels: type: bug

#2258 Allow electrolyzing more hydrocarbons
  src/main/java/gregtech/api/unification/material/materials/OrganicChemistryMaterials.java
  src/main/java/gregtech/loaders/recipe/chemistry/SeparationRecipes.java
Labels: type: feature

#2310 only access worldpipenet on server
  src/main/java/gregtech/api/pipenet/WorldPipeNet.java
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
Labels: type: bug

#2270 update GHA workflows
  .github/actions/build_setup/action.yml
  .github/workflows/format_java.yml
  .github/workflows/manage_pr_labels.yml
  .github/workflows/pr_artifact.yml
  .github/workflows/pr_labels.yml
  .github/workflows/pr_testing.yml
  .github/workflows/publish.yml
  .github/workflows/publish_project.yml
  .github/workflows/test_java.yml
  .github/workflows/update_buildscript.yml
  .github/workflows/update_gradle_cache.yml
  .github/workflows/validate_gradle_wrapper.yml
Labels: ignore changelog

#2322 Fix a couple incomplete recieveCustomData calls
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiFluidHatch.java
Labels: type: bug

#2315 Add some GT items to ExtraBees alveary mutator
  src/main/java/gregtech/integration/forestry/ForestryModule.java
Labels: type: feature

#2309 Update build script version to 1702805890
  build.gradle
  gradle.properties
Labels: ignore changelog

#2325 Change order of item in Research Station JEI page
  src/main/java/gregtech/api/recipes/ui/impl/ResearchStationUI.java
Labels: type: feature

#2324 Fix large turbine recipe selection
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/LargeTurbineWorkableHandler.java
Labels: type: bug

#2327 Use locale formatting where possible in WAILA and The One Probe
  src/main/java/gregtech/integration/hwyla/provider/ConverterDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/DiodeDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/PrimitivePumpDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/RecipeLogicDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/SteamBoilerDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/TransformerDataProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/ConverterInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/CoverInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/ElectricContainerInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/LaserContainerInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/PrimitivePumpInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/RecipeLogicInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/SteamBoilerInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/TransformerInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/WorkableInfoProvider.java
Labels: type: bug

#2329 Use EU/t for digital interface
  src/main/java/gregtech/common/covers/CoverDigitalInterface.java
Labels: type: feature
