Repository GregTechCEu/GregTech, pull requests merged in 2023-11, with the labels that each got.

#2143 Fix MTEs sometimes not syncing
  src/main/java/gregtech/api/metatileentity/SyncedTileEntityBase.java
Labels: type: bug

#1887 Move syncing functionality into ISyncedTileEntity
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/RecipeLogicSteam.java
  src/main/java/gregtech/api/metatileentity/MTETrait.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/api/metatileentity/SyncedTileEntityBase.java
  src/main/java/gregtech/api/metatileentity/interfaces/IGregTechTileEntity.java
  src/main/java/gregtech/api/metatileentity/interfaces/ISyncedTileEntity.java
Labels: type: refactor

#2145 Log packet reading failures
  src/main/java/gregtech/api/metatileentity/SyncedTileEntityBase.java
Labels: type: feature

#2146 Improved Module usability
  src/main/java/gregtech/api/modules/GregTechModule.java
  src/main/java/gregtech/api/modules/IGregTechModule.java
  src/main/java/gregtech/api/modules/IModuleContainer.java
  src/main/java/gregtech/api/modules/ModuleContainer.java
  src/main/java/gregtech/modules/ModuleManager.java
Labels: type: bug

#2138 Rework maintenance hatch textures
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_maintenance_configurable.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_maintenance_configurable_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_maintenance_configurable_emissive.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_maintenance_full_auto.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_maintenance_full_auto_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_maintenance_full_auto_emissive.png.mcmeta
Labels: type: feature

#2092 make steam venting decrement snow layers
  src/main/java/gregtech/api/capability/impl/RecipeLogicSteam.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
Labels: type: feature

#2119 track missing textures for sided renderers
  src/main/java/gregtech/client/renderer/texture/cube/OrientedOverlayRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/SidedCubeRenderer.java
Labels: type: feature

#2117 Allow energy detector cover on PSS
  src/main/java/gregtech/common/covers/detector/CoverDetectorEnergy.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorEnergyAdvanced.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPowerSubstation.java
Labels: type: bug

#2060 New Chanced Output System
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/chance/BaseChanceEntry.java
  src/main/java/gregtech/api/recipes/chance/ChanceEntry.java
  src/main/java/gregtech/api/recipes/chance/boost/BoostableChanceEntry.java
  src/main/java/gregtech/api/recipes/chance/boost/ChanceBoostFunction.java
  src/main/java/gregtech/api/recipes/chance/output/BoostableChanceOutput.java
  src/main/java/gregtech/api/recipes/chance/output/ChancedOutput.java
  src/main/java/gregtech/api/recipes/chance/output/ChancedOutputList.java
  src/main/java/gregtech/api/recipes/chance/output/ChancedOutputLogic.java
  src/main/java/gregtech/api/recipes/chance/output/impl/ChancedFluidOutput.java
  src/main/java/gregtech/api/recipes/chance/output/impl/ChancedItemOutput.java
  src/main/java/gregtech/api/recipes/logic/ParallelLogic.java
  src/main/java/gregtech/common/command/CommandRecipeCheck.java
  src/main/java/gregtech/integration/crafttweaker/recipe/CTRecipe.java
  src/main/java/gregtech/integration/crafttweaker/recipe/ChancedEntry.java
  src/main/java/gregtech/integration/jei/basic/OreByProduct.java
  src/main/java/gregtech/integration/jei/basic/OreByProductCategory.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/integration/jei/recipe/RecipeMapCategory.java
  src/main/java/gregtech/integration/jei/utils/render/FluidStackTextRenderer.java
  src/main/java/gregtech/integration/jei/utils/render/ItemStackTextRenderer.java
  src/main/java/gregtech/integration/opencomputers/drivers/DriverAbstractRecipeLogic.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/test/java/gregtech/api/recipes/chance/boost/ChanceBoostTest.java
  src/test/java/gregtech/api/recipes/chance/output/ChancedOutputLogicTest.java
Labels: type: feature

#2141 localization for vein custom names and ore vein jei page
  src/main/java/gregtech/api/worldgen/config/BedrockFluidDepositDefinition.java
  src/main/java/gregtech/api/worldgen/config/OreDepositDefinition.java
  src/main/java/gregtech/integration/jei/basic/GTOreCategory.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/worldgen/fluid/nether/lava_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/nether/natural_gas_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/overworld/heavy_oil_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/overworld/light_oil_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/overworld/natural_gas_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/overworld/oil_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/overworld/raw_oil_deposit.json
  src/main/resources/assets/gregtech/worldgen/fluid/overworld/salt_water_deposit.json
  src/main/resources/assets/gregtech/worldgen/vein/end/bauxite_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/end/magnetite_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/end/naquadah_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/end/pitchblende_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/end/scheelite_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/end/sheldonite_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/nether/banded_iron_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/nether/beryllium_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/nether/certus_quartz_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/nether/manganese_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/nether/molybdenum_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/nether/monazite_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/nether/nether_quartz_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/nether/redstone_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/nether/saltpeter_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/nether/sulfur_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/nether/tetrahedrite_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/nether/topaz_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/apatite_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/basalt_sphere.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/black_granite_sphere.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/cassiterite_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/coal_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/copper_tin_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/copper_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/diamond_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/galena_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/garnet_tin_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/garnet_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/iron_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/lapis_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/lubricant_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/magnetite_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/manganese_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/marble_sphere.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/mica_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/mineral_sand_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/nickel_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/oilsands_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/olivine_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/raw_oil_sphere.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/red_granite_sphere.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/redstone_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/salts_vein.json
  src/main/resources/assets/gregtech/worldgen/vein/overworld/sapphire_vein.json
Labels: type: bug

#2149 More recipe fixes
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/loaders/recipe/handlers/OreRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/PartsRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/PipeRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/ToolRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/WireRecipeHandler.java
Labels: type: bug

#2147 Re-enable module configuration file
  src/main/java/gregtech/api/modules/GregTechModule.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/integration/IntegrationModule.java
  src/main/java/gregtech/integration/baubles/BaublesModule.java
  src/main/java/gregtech/integration/crafttweaker/CraftTweakerModule.java
  src/main/java/gregtech/integration/groovy/GroovyScriptModule.java
  src/main/java/gregtech/integration/hwyla/HWYLAModule.java
  src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java
  src/main/java/gregtech/integration/opencomputers/OpenComputersModule.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeModule.java
  src/main/java/gregtech/modules/ModuleManager.java
  src/main/java/gregtech/tools/ToolsModule.java
Labels: type: refactor

#2153 Improve packet warnings
  src/main/java/gregtech/api/metatileentity/SyncedTileEntityBase.java
Labels: ignore changelog

#2150 Allow singleblock generators to face up/down
  src/main/java/gregtech/api/metatileentity/SimpleGeneratorMetaTileEntity.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntitySingleCombustion.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntitySingleTurbine.java
Labels: type: feature

#2155 Block ME Output Hatch on DT
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDistillationTower.java
Labels: type: bug

#2158 make tool click messages display in status bar
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiMapMultiblockController.java
  src/main/java/gregtech/common/covers/CoverFluidVoiding.java
  src/main/java/gregtech/common/covers/CoverItemVoiding.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorBase.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityDiode.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityDrum.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: type: feature

#2159 Pride capes
  src/main/java/gregtech/api/terminal/TerminalRegistry.java
  src/main/java/gregtech/api/util/CapesRegistry.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/terminal/app/capeselector/CapeSelectorApp.java
  src/main/java/gregtech/common/terminal/app/capeselector/widget/CapeListWidget.java
  src/main/resources/assets/gregtech/textures/capes/acecape.png
  src/main/resources/assets/gregtech/textures/capes/agendercape.png
  src/main/resources/assets/gregtech/textures/capes/aromanticcape.png
  src/main/resources/assets/gregtech/textures/capes/bicape.png
  src/main/resources/assets/gregtech/textures/capes/debugcape.png
  src/main/resources/assets/gregtech/textures/capes/genderfluidcape.png
  src/main/resources/assets/gregtech/textures/capes/genderqueercape.png
  src/main/resources/assets/gregtech/textures/capes/intersexcape.png
  src/main/resources/assets/gregtech/textures/capes/lesbiancape.png
  src/main/resources/assets/gregtech/textures/capes/nonbinarycape.png
  src/main/resources/assets/gregtech/textures/capes/pancape.png
  src/main/resources/assets/gregtech/textures/capes/rainbowcape.png
  src/main/resources/assets/gregtech/textures/capes/transcape.png
Labels: type: feature

#2162 Fix macerator using wrong overlay at higher tiers
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/resources/assets/gregtech/textures/blocks/machines/pulverizer/overlay_top_active_emissive.png.mcmeta
Labels: type: bug

#2132 Fix LD Network issues
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/pipenet/longdist/BlockLongDistancePipe.java
  src/main/java/gregtech/api/pipenet/longdist/ILDEndpoint.java
  src/main/java/gregtech/api/pipenet/longdist/ILDNetworkPart.java
  src/main/java/gregtech/api/pipenet/longdist/LongDistanceNetwork.java
  src/main/java/gregtech/api/pipenet/longdist/LongDistancePipeType.java
  src/main/java/gregtech/api/pipenet/longdist/NetworkBuilder.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityLongDistanceEndpoint.java
  src/main/java/gregtech/common/pipelike/fluidpipe/longdistance/LDFluidPipeType.java
  src/main/java/gregtech/common/pipelike/itempipe/longdistance/LDItemPipeType.java
  src/main/java/gregtech/core/CoreModule.java
Labels: type: bug

#1814 OreGlob update
  src/main/java/gregtech/api/util/oreglob/OreGlob.java
  src/main/java/gregtech/api/util/oreglob/OreGlobCompileResult.java
  src/main/java/gregtech/api/util/oreglob/OreGlobFormattedStringVisualizer.java
  src/main/java/gregtech/api/util/oreglob/OreGlobStringVisualizer.java
  src/main/java/gregtech/api/util/oreglob/OreGlobTextBuilder.java
  src/main/java/gregtech/api/util/oreglob/OreGlobTextFormatting.java
  src/main/java/gregtech/api/util/oreglob/VisualizationHint.java
  src/main/java/gregtech/common/covers/filter/OreDictionaryItemFilter.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/ImpossibleOreGlob.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/NodeInterpreter.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/NodeOreGlob.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/NodeVisualXMLHandler.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/NodeVisualizer.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/OreGlobMessages.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/OreGlobParser.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/AnyCharNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/BranchNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/BranchType.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/EmptyNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/ErrorNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/EverythingNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/GroupNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/MatchDescription.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/MatchNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/NodeVisitor.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/OreGlobNode.java
  src/main/java/gregtech/common/covers/filter/oreglob/node/OreGlobNodes.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/test/java/gregtech/Bootstrap.java
  src/test/java/gregtech/api/util/OreGlobTest.java
Labels: type: feature

#2045 Remove silicone rubber shortcuts
  src/main/java/gregtech/api/unification/material/materials/OrganicChemistryMaterials.java
  src/main/java/gregtech/loaders/recipe/chemistry/ReactorRecipes.java
Labels: type: feature

#2078 Quantum Chest Voiding + Quantum Storage Improvements
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/java/gregtech/api/util/TextFormattingUtil.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/gui/widget/button_fluid_void.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_item_void.png
  src/test/java/gregtech/common/metatileentities/storage/QuantumChestTest.java
  src/test/java/gregtech/common/metatileentities/storage/QuantumTankTest.java
Labels: type: feature

#2101 Add Latching Mode to Advanced Fluid/Item Detectors
  src/main/java/gregtech/common/covers/detector/CoverDetectorEnergyAdvanced.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorFluidAdvanced.java
  src/main/java/gregtech/common/covers/detector/CoverDetectorItemAdvanced.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2157 Update build script version to 1699743071
  build.gradle
Labels: ignore changelog

#2126 Add steam boiler production to top/waila
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java
  src/main/java/gregtech/integration/hwyla/HWYLAModule.java
  src/main/java/gregtech/integration/hwyla/provider/RecipeLogicDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/SteamBoilerDataProvider.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeModule.java
  src/main/java/gregtech/integration/theoneprobe/provider/RecipeLogicInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/SteamBoilerInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1310 Allow Taping crates to keep inventory
  src/main/java/gregtech/api/block/machines/MachineItemBlock.java
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCrate.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/metaitems/basic_tape.json
  src/main/resources/assets/gregtech/textures/items/metaitems/basic_tape.png
Labels: type: feature

#2163 Reservoir Hatch
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityReservoirHatch.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_water.png
Labels: type: feature

#2133 Add missing hard recipe config recipes
  src/main/java/gregtech/api/items/OreDictNames.java
  src/main/java/gregtech/api/unification/material/info/MaterialFlags.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/HigherDegreeMaterials.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/loaders/MaterialInfoLoader.java
  src/main/java/gregtech/loaders/WoodTypeEntry.java
  src/main/java/gregtech/loaders/recipe/VanillaOverrideRecipes.java
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
  src/main/java/gregtech/loaders/recipe/WoodRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/handlers/PartsRecipeHandler.java
Labels: type: feature

#2172 Fix Quantum Chest Export Slot Checking
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
  src/test/java/gregtech/common/metatileentities/storage/QuantumChestTest.java
Labels: type: bug

#2173 Creative energy improvements
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeEnergy.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2166 Allow opening covers on the grid with empty hand
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/common/ToolEventHandlers.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityDrum.java
Labels: type: feature

#2077 Add alarms to GTCEu
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityAlarm.java
  src/main/java/gregtech/core/sound/GTSoundEvents.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/sounds.json
  src/main/resources/assets/gregtech/sounds/alarm.ogg
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_alarm.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_alarm_active.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_alarm_active_emissive.png
Labels: type: feature

#2165 Rewrite TankWidget clicking behavior
  src/main/java/gregtech/api/gui/widgets/TankWidget.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2174 Fix framebox transmutation
  src/main/java/gregtech/common/blocks/BlockFrame.java
Labels: type: bug

#2176 Fix plunger and soft mallet durability off-by-one issues
  src/main/java/gregtech/common/items/ToolItems.java
  src/main/java/gregtech/loaders/recipe/handlers/ToolRecipeHandler.java
Labels: type: bug

#2164 Circuit tweaks
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/loaders/recipe/CircuitRecipes.java
Labels: type: feature

#2178 Rebalance some early game fluid pipes
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/OrganicChemistryMaterials.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
Labels: type: refactor

#2177 Minecart wheels
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/loaders/MaterialInfoLoader.java
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/VanillaOverrideRecipes.java
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/metaitems/minecart_wheels.iron.json
  src/main/resources/assets/gregtech/models/item/metaitems/minecart_wheels.steel.json
  src/main/resources/assets/gregtech/textures/items/metaitems/minecart_wheels.iron.png
  src/main/resources/assets/gregtech/textures/items/metaitems/minecart_wheels.steel.png
Labels: type: feature

#2168 Don't initialize I/O if Multiblock tank is not formed
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityMultiblockTank.java
Labels: type: bug

#2180 Update&fix Chinese localization
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#2181 Fix grid highlight applying too aggressively
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: ignore changelog

#2167 Fix Fluid Jetpacks being caught on one fluid type
  src/main/java/gregtech/common/EventHandlers.java
  src/main/java/gregtech/common/items/armor/PowerlessJetpack.java
Labels: type: bug

#2179 Arrows for fluid pipe restrictors
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
  src/main/java/gregtech/client/ClientProxy.java
  src/main/java/gregtech/client/renderer/pipe/PipeRenderer.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/pipelike/laser/net/LaserNetHandler.java
  src/main/java/gregtech/common/pipelike/laser/tile/TileEntityLaserPipe.java
  src/main/java/gregtech/common/pipelike/optical/net/OpticalNetHandler.java
  src/main/java/gregtech/common/pipelike/optical/tile/TileEntityOpticalPipe.java
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_dl.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_down.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_dr.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_left.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_lr.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_nd.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_nl.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_nr.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_nu.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_rd.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_right.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_ud.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_ul.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_up.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/blocked/pipe_blocked_ur.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/pipe_blocked.png
Labels: type: feature

#2128 Extended multiblock rotation
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapPrimitiveMultiblockController.java
  src/main/java/gregtech/api/pattern/BlockPattern.java
  src/main/java/gregtech/api/pattern/PatternMatchContext.java
  src/main/java/gregtech/api/terminal/gui/widgets/MachineSceneWidget.java
  src/main/java/gregtech/api/util/RelativeDirection.java
  src/main/java/gregtech/client/renderer/handler/MultiblockPreviewRenderer.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/ToolEventHandlers.java
  src/main/java/gregtech/common/items/behaviors/monitorplugin/AdvancedMonitorPluginBehavior.java
  src/main/java/gregtech/common/items/behaviors/monitorplugin/FakeGuiPluginBehavior.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveWaterPump.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDataBank.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDistillationTower.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityHPCA.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityNetworkSwitch.java
  src/main/java/gregtech/common/metatileentities/multi/electric/centralmonitor/MetaTileEntityCentralMonitor.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityDataAccessHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiblockPart.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityOpticalDataHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/hpca/MetaTileEntityHPCAComponent.java
  src/main/java/gregtech/common/metatileentities/primitive/MetaTileEntityCharcoalPileIgniter.java
  src/main/java/gregtech/common/terminal/app/multiblockhelper/MachineBuilderWidget.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/casings/pipe/grate_steel_front/back.png
  src/main/resources/assets/gregtech/textures/blocks/casings/pipe/grate_steel_front/bottom.png
  src/main/resources/assets/gregtech/textures/blocks/casings/pipe/grate_steel_front/front.png
  src/main/resources/assets/gregtech/textures/blocks/casings/pipe/grate_steel_front/left.png
  src/main/resources/assets/gregtech/textures/blocks/casings/pipe/grate_steel_front/right.png
  src/main/resources/assets/gregtech/textures/blocks/casings/pipe/grate_steel_front/top.png
Labels: type: feature

#2183 Reduce Small and Tiny Dust Usages
  src/main/java/gregtech/integration/jei/basic/OreByProduct.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/WoodRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/DistillationRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/NaquadahRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/PetrochemRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/ReactorRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/SeparationRecipes.java
  src/main/java/gregtech/loaders/recipe/handlers/MaterialRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/OreRecipeHandler.java
Labels: type: feature

#2184 Rework vacuum freezer recipes
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/HigherDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/properties/BlastProperty.java
  src/main/java/gregtech/integration/crafttweaker/material/CTMaterialBuilder.java
  src/main/java/gregtech/integration/crafttweaker/material/MaterialPropertyExpansion.java
  src/main/java/gregtech/integration/groovy/GroovyMaterialBuilderExpansion.java
  src/main/java/gregtech/loaders/recipe/handlers/MaterialRecipeHandler.java
Labels: type: feature

#2186 fix ME hatch packet reading
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityAEHostablePart.java
Labels: type: bug

#2187 Fix grid highlight again
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: ignore changelog

#2188 Fix assembly line part sorter when flipped
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
Labels: ignore changelog

#2189 fix LD pipe missing texture warning
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/client/renderer/texture/cube/LDPipeOverlayRenderer.java
Labels: ignore changelog

#2190 Actually fix assline part sorter when flipped
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
Labels: ignore changelog

#2191 Add argon plasma fuel recipe
  src/main/java/gregtech/loaders/recipe/FuelRecipes.java
Labels: type: feature

#2196 Allow spray paint to change UI color (with cfg)
  src/main/java/gregtech/api/gui/IUIHolder.java
  src/main/java/gregtech/api/gui/ModularUI.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/common/ConfigHolder.java
Labels: type: feature

#2195 9 slot arc furnace at EV
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMacerator.java
  src/main/java/gregtech/common/metatileentities/electric/SimpleMachineMetaTileEntityResizable.java
  src/test/java/gregtech/api/recipes/logic/ParallelLogicTest.java
Labels: type: feature

#2193 Better vanilla block rotation
  src/main/java/gregtech/common/ToolEventHandlers.java
  src/main/java/gregtech/common/items/tool/BlockRotatingBehavior.java
  src/main/java/gregtech/common/items/tool/rotation/CustomBlockRotations.java
  src/main/java/gregtech/common/items/tool/rotation/ICustomRotationBehavior.java
  src/main/java/gregtech/tools/ToolsModule.java
Labels: type: feature

#2194 Fix AoE issues
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
  src/main/java/gregtech/common/EventHandlers.java
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: type: bug

#2175 Refactor World Accelerator
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityWorldAccelerator.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: refactor

#2197 Very Important PR
  src/main/java/gregtech/common/CommonProxy.java
Labels: ignore changelog

#2169 Add Pick Block support to Super Tanks
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: type: feature

#2073 GTParticle/bloom effect refactor and cleanup
  src/main/java/gregtech/api/block/VariantActiveBlock.java
  src/main/java/gregtech/api/cover/Cover.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/api/terminal/gui/widgets/AnimaWidgetGroup.java
  src/main/java/gregtech/api/terminal/os/menu/TerminalMenuWidget.java
  src/main/java/gregtech/api/util/interpolate/Eases.java
  src/main/java/gregtech/api/util/interpolate/IEase.java
  src/main/java/gregtech/asm/hooks/CTMHooks.java
  src/main/java/gregtech/asm/hooks/CTMModHooks.java
  src/main/java/gregtech/asm/hooks/LittleTilesHooks.java
  src/main/java/gregtech/client/event/ClientEventHandler.java
  src/main/java/gregtech/client/model/ActiveVariantBlockBakedModel.java
  src/main/java/gregtech/client/model/EmissiveOreBakedModel.java
  src/main/java/gregtech/client/model/customtexture/CustomTextureModel.java
  src/main/java/gregtech/client/model/lamp/LampBakedModel.java
  src/main/java/gregtech/client/particle/GTBloomParticle.java
  src/main/java/gregtech/client/particle/GTLaserBeamParticle.java
  src/main/java/gregtech/client/particle/GTNameTagParticle.java
  src/main/java/gregtech/client/particle/GTOverheatParticle.java
  src/main/java/gregtech/client/particle/GTParticle.java
  src/main/java/gregtech/client/particle/GTParticleManager.java
  src/main/java/gregtech/client/particle/GTTexturedParticle.java
  src/main/java/gregtech/client/particle/GTTexturedShaderParticle.java
  src/main/java/gregtech/client/particle/IGTParticleHandler.java
  src/main/java/gregtech/client/renderer/ICustomRenderFast.java
  src/main/java/gregtech/client/renderer/IRenderSetup.java
  src/main/java/gregtech/client/renderer/pipe/LaserPipeRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/OrientedOverlayRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/SidedCubeRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/SimpleOrientedCubeRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/SimpleOverlayRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/SimpleSidedCubeRenderer.java
  src/main/java/gregtech/client/renderer/texture/custom/FireboxActiveRenderer.java
  src/main/java/gregtech/client/shader/postprocessing/BloomEffect.java
  src/main/java/gregtech/client/shader/postprocessing/BloomType.java
  src/main/java/gregtech/client/shader/postprocessing/IPostRender.java
  src/main/java/gregtech/client/utils/BloomEffectUtil.java
  src/main/java/gregtech/client/utils/EffectRenderContext.java
  src/main/java/gregtech/client/utils/IBloomEffect.java
  src/main/java/gregtech/client/utils/RenderUtil.java
  src/main/java/gregtech/common/blocks/BlockLamp.java
  src/main/java/gregtech/common/blocks/BlockLampBorderless.java
  src/main/java/gregtech/common/blocks/BlockOre.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
  src/main/java/gregtech/common/pipelike/cable/tile/TileEntityCable.java
  src/main/java/gregtech/common/pipelike/laser/BlockLaserPipe.java
  src/main/java/gregtech/common/terminal/app/appstore/AppCardWidget.java
  src/main/java/gregtech/common/terminal/app/appstore/AppPageWidget.java
  src/main/java/gregtech/common/terminal/app/guide/widget/GuidePageWidget.java
  src/main/java/gregtech/common/terminal/app/guideeditor/widget/GuidePageEditorWidget.java
Labels: type: refactor

#2139 Limit multiblock recipe tier by energy hatches
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/EnergyContainerList.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/PrimitiveRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/RecipeLogicEnergy.java
  src/main/java/gregtech/api/capability/impl/RecipeLogicSteam.java
  src/main/java/gregtech/api/capability/impl/SteamMultiblockRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockDisplayText.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCrackingUnit.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityElectricBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiSmelter.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPyrolyseOven.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityResearchStation.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeCombustionEngine.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/test/java/gregtech/api/capability/impl/AbstractRecipeLogicTest.java
Labels: type: feature

#2198 Only load the module config file once
  src/main/java/gregtech/modules/ModuleManager.java
Labels: ignore changelog

#2200 Remove dangling 2.7 deprecation
  src/main/java/gregtech/integration/RecipeCompatUtil.java
Labels: ignore changelog

#2202 Fix fluid tooltips overriding previous ones
  src/main/java/gregtech/api/util/FluidTooltipUtil.java
Labels: type: bug

#2205 Reservoir hatch fixes
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityReservoirHatch.java
Labels: type: bug

#2203 Fix GT Water/Lava materials storing the wrong object
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/UnknownCompositionMaterials.java
  src/main/java/gregtech/api/util/FluidTooltipUtil.java
Labels: type: bug

#2204 Set the Assembly Line particles config option true to default
  src/main/java/gregtech/common/ConfigHolder.java
Labels: type: feature

#2206 Fix mobs being able to spawn on warning signs
  src/main/java/gregtech/common/blocks/BlockWarningSign.java
  src/main/java/gregtech/common/blocks/BlockWarningSign1.java
Labels: type: bug

#2211 stop clearing fluid sprite locations after registration
  src/main/java/gregtech/api/fluids/GTFluidRegistration.java
Labels: type: bug

#2213 Fix cover ticking issues
  src/main/java/gregtech/api/cover/Cover.java
  src/main/java/gregtech/api/cover/CoverHolder.java
  src/main/java/gregtech/api/pipenet/tile/PipeCoverableImplementation.java
Labels: type: bug

#2208 Update ru_ru lang for 2.8.0
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: type: translation

#2214 Fix HPCA allocation logic
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityHPCA.java
Labels: type: bug

#2215 Add groovy shortcuts for common fluid calls
  src/main/java/gregtech/integration/groovy/GroovyMaterialBuilderExpansion.java
Labels: type: feature

#2221 Fix Multiblock tanks
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityMultiblockTank.java
Labels: type: bug

#2222 Fix fluid property with no fluid
  src/main/java/gregtech/api/fluids/store/FluidStorage.java
Labels: type: bug

#2218 Fix data access hatch render when facing up/down
  src/main/java/gregtech/client/renderer/texture/cube/SimpleOrientedCubeRenderer.java
Labels: type: bug

#2212 Fix crashes when other mods add fluids of same name
  src/main/java/gregtech/api/fluids/FluidBuilder.java
  src/main/java/gregtech/api/fluids/GTFluidRegistration.java
Labels: type: bug

#2216 Repair the fluid registry for addons
  src/main/java/gregtech/api/fluids/GTFluidRegistration.java
Labels: type: bug
