Repository GregTechCEu/GregTech, pull requests merged in 2023-08, with the labels that each got.

#2026 Update build script version to 1690847429
  build.gradle
  settings.gradle
Labels: ignore changelog

#2027 Shortcut method for CT material registry getter
  src/main/java/gregtech/integration/crafttweaker/material/CTMaterialRegistry.java
Labels: type: bug

#2012 allow recycling recipes to generate from assembler
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/RecyclingHandler.java
  src/main/java/gregtech/api/recipes/builders/AssemblerRecipeBuilder.java
  src/main/java/gregtech/loaders/recipe/ComponentRecipes.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
Labels: type: refactor

#2005 fix issues with fluid colors and textures
  src/main/java/gregtech/api/fluids/MetaFluids.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/OrganicChemistryMaterials.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/UnknownCompositionMaterials.java
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.diesel.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.epichlorohydrin.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.lightly_hydrocracked_heavy_fuel.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.lightly_hydrocracked_heavy_fuel.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.lightly_hydrocracked_light_fuel.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.lightly_hydrocracked_light_fuel.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.lightly_hydrocracked_naphtha.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.lightly_hydrocracked_naphtha.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.lightly_steamcracked_heavy_fuel.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.lightly_steamcracked_light_fuel.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.lightly_steamcracked_naphtha.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.lightly_steamcracked_naphtha.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.lubricant.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.naphtha.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.oil.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.oil_light.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.oil_medium.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.severely_hydrocracked_heavy_fuel.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.severely_hydrocracked_heavy_fuel.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.severely_hydrocracked_light_fuel.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.severely_hydrocracked_light_fuel.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.severely_hydrocracked_naphtha.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.severely_hydrocracked_naphtha.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.severely_steamcracked_heavy_fuel.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.severely_steamcracked_light_fuel.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.severely_steamcracked_naphtha.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.severely_steamcracked_naphtha.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.sulfuric_gas.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.sulfuric_heavy_fuel.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.sulfuric_light_fuel.png
  src/main/resources/assets/gregtech/textures/blocks/fluids/fluid.titanium_tetrachloride.png
Labels: type: bug, type: feature

#2032 Fix non-consumable items in assembler recycling
  src/main/java/gregtech/api/recipes/RecyclingHandler.java
Labels: ignore changelog

#2031 Update build script version to 1690966774
  build.gradle
Labels: ignore changelog

#2034 fix QuantumChestItemHandler
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
Labels: type: bug

#2035 slightly better fluid vein version handling
  src/main/java/gregtech/api/worldgen/bedrockFluids/BedrockFluidVeinSaveData.java
Labels: type: bug

#2016 Faster markDirty implementation for saving
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/api/metatileentity/TieredMetaTileEntity.java
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityDiode.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityHull.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCrate.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityDrum.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: type: refactor

#2033 Include Steam Grinder/Smelter for TOP/HWYLA changes
  src/main/java/gregtech/integration/hwyla/provider/RecipeLogicDataProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/RecipeLogicInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: bug, ignore changelog

#2037 Fix reinforced stone hardness, resistance, sound type
  src/main/java/gregtech/common/blocks/foam/BlockPetrifiedFoam.java
Labels: type: bug

#2030 Recipe chart app fix
  src/main/java/gregtech/common/terminal/app/recipechart/FluidStackHelper.java
  src/main/java/gregtech/common/terminal/app/recipechart/IngredientHelper.java
  src/main/java/gregtech/common/terminal/app/recipechart/ItemStackHelper.java
  src/main/java/gregtech/common/terminal/app/recipechart/widget/RGNode.java
  src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java
  src/main/java/gregtech/integration/jei/utils/ModularUIGuiHandler.java
Labels: type: bug

#1991 Fix ME Hatches Parallel and Voiding or Dupeing
  src/main/java/gregtech/api/capability/impl/FluidTankList.java
  src/main/java/gregtech/common/gui/widget/appeng/AEConfigWidget.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEOutputBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEOutputHatch.java
Labels: type: bug

#2022 Fix groovyscript server crash
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
  src/main/java/gregtech/api/capability/impl/miner/MultiblockMinerLogic.java
  src/main/java/gregtech/api/cover/ICoverable.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityCokeOven.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityLargeBoiler.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityMultiblockTank.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveWaterPump.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityActiveTransformer.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCrackingUnit.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDataBank.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDistillationTower.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityElectricBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityHPCA.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityImplosionCompressor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeChemicalReactor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiSmelter.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityNetworkSwitch.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPowerSubstation.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPyrolyseOven.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityResearchStation.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityVacuumFreezer.java
  src/main/java/gregtech/common/metatileentities/multi/electric/centralmonitor/MetaTileEntityCentralMonitor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeCombustionEngine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
  src/main/java/gregtech/common/metatileentities/multi/steam/MetaTileEntitySteamGrinder.java
  src/main/java/gregtech/common/metatileentities/multi/steam/MetaTileEntitySteamOven.java
  src/main/java/gregtech/common/metatileentities/primitive/MetaTileEntityCharcoalPileIgniter.java
Labels: type: bug

#2028 Ld pipe crash fix
  src/main/java/gregtech/api/pipenet/longdist/LongDistanceNetwork.java
Labels: type: bug

#2038 fix crafting station division by zero
  src/main/java/gregtech/common/gui/widget/craftingstation/CraftingSlotWidget.java
Labels: type: bug

#1934 Allow material fluid name overrides
  src/main/java/gregtech/api/fluids/MaterialFluid.java
Labels: type: feature

#2049 Update groovyscript to 0.6.0 in dependencies.gradle
  dependencies.gradle
Labels: ignore changelog
