Repository GregTechCEu/GregTech, pull requests merged in 2023-06, with the labels that each got.

#1817 Add label, allow CI jobs to run on buildscript updater
  .github/workflows/update_buildscript.yml
Labels: ignore changelog

#1819 try another workaround for tests to run
  .github/workflows/update_buildscript.yml
Labels: ignore changelog

#1821 (updater) try placing secret in a different place
  .github/workflows/update_buildscript.yml
Labels: ignore changelog

#1822 Update build script version to 1685514775
  build.gradle
  gradle.properties
Labels: ignore changelog

#1816 Remove some deprecations, mark others for removal
  src/main/java/gregtech/GregTechVersion.java
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/block/DelayedStateBlock.java
  src/main/java/gregtech/api/capability/FeCompat.java
  src/main/java/gregtech/api/items/metaitem/MetaItem.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/builders/IntCircuitRecipeBuilder.java
  src/main/java/gregtech/api/unification/OreDictUnifier.java
  src/main/java/gregtech/api/unification/stack/WildcardAwareHashMap.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/OreDictExprFilter.java
  src/main/java/gregtech/client/renderer/texture/cube/OrientedOverlayRenderer.java
  src/main/java/gregtech/client/renderer/texture/cube/SidedCubeRenderer.java
  src/main/java/gregtech/common/covers/CoverBehaviors.java
Labels: type: refactor

#1695 Re-implement FluidTankList & OverlayedFluidHandler
  src/main/java/gregtech/api/capability/IFilter.java
  src/main/java/gregtech/api/capability/IFilteredFluidContainer.java
  src/main/java/gregtech/api/capability/IMultipleTankHandler.java
  src/main/java/gregtech/api/capability/IPropertyFluidFilter.java
  src/main/java/gregtech/api/capability/IThermalFluidHandlerItemStack.java
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/CommonFluidFilters.java
  src/main/java/gregtech/api/capability/impl/FilteredFluidHandler.java
  src/main/java/gregtech/api/capability/impl/FluidTankList.java
  src/main/java/gregtech/api/capability/impl/GTFluidHandlerItemStack.java
  src/main/java/gregtech/api/capability/impl/GTSimpleFluidHandlerItemStack.java
  src/main/java/gregtech/api/capability/impl/MultiFluidFilter.java
  src/main/java/gregtech/api/capability/impl/NotifiableFluidTankFromList.java
  src/main/java/gregtech/api/capability/impl/PropertyFluidFilter.java
  src/main/java/gregtech/api/capability/impl/SimpleThermalFluidHandlerItemStack.java
  src/main/java/gregtech/api/capability/impl/SingleFluidFilter.java
  src/main/java/gregtech/api/capability/impl/ThermalFluidHandlerItemStack.java
  src/main/java/gregtech/api/cover/CoverBehavior.java
  src/main/java/gregtech/api/items/metaitem/FilteredFluidStats.java
  src/main/java/gregtech/api/items/metaitem/MetaItem.java
  src/main/java/gregtech/api/items/metaitem/ThermalFluidStats.java
  src/main/java/gregtech/api/metatileentity/SteamMetaTileEntity.java
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/api/recipes/logic/ParallelLogic.java
  src/main/java/gregtech/api/unification/material/properties/FluidPipeProperties.java
  src/main/java/gregtech/api/util/GTTransferUtils.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/OverlayedFluidHandler.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/armor/PowerlessJetpack.java
  src/main/java/gregtech/common/items/behaviors/FoamSprayerBehavior.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityMultiblockTank.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiFluidHatch.java
  src/main/java/gregtech/common/metatileentities/steam/SteamMiner.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamLavaBoiler.java
  src/main/java/gregtech/common/metatileentities/steam/multiblockpart/MetaTileEntitySteamHatch.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityDrum.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
  src/main/java/gregtech/common/pipelike/fluidpipe/tile/TileEntityFluidPipeTickable.java
  src/main/java/gregtech/core/CoreModule.java
  src/test/java/gregtech/Bootstrap.java
  src/test/java/gregtech/api/capability/impl/FluidTankListTest.java
Labels: type: refactor

#1825 Fix invalid MultiblockShapeInfo with non-square multiblocks
  src/main/java/gregtech/api/pattern/MultiblockShapeInfo.java
Labels: type: bug

#1827 Fix non GT tile entities in manual multiblock previews
  src/main/java/gregtech/api/pattern/MultiblockShapeInfo.java
  src/main/java/gregtech/integration/jei/multiblock/MultiblockInfoRecipeWrapper.java
Labels: type: bug

#1828 Update build script version to 1685741895
  build.gradle
Labels: ignore changelog

#1829 Fix RecipeMap#onRecipeBuild generics
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: type: bug

#1834 Fix materials with one component having incorrect formulas
  src/main/java/gregtech/api/unification/material/Material.java
Labels: type: bug

#1836 Fix settings.gradle issue
  settings.gradle
Labels: ignore changelog

#1835 Update build script version to 1685933053
  build.gradle
  gradle.properties
Labels: ignore changelog

#1837 Update build script version to 1685933053
  build.gradle
Labels: ignore changelog

#1840 Update build script version to 1686205143
  build.gradle
Labels: ignore changelog

#1812 Recipe Categories
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/java/gregtech/api/gui/widgets/RecipeProgressWidget.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/category/GTRecipeCategory.java
  src/main/java/gregtech/api/recipes/category/RecipeCategories.java
  src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java
  src/main/java/gregtech/integration/jei/recipe/RecipeMapCategory.java
  src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/RecyclingRecipes.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/gui/icon/arc_furnace_recycling.png
  src/main/resources/assets/gregtech/textures/gui/icon/extractor_recycling.png
  src/main/resources/assets/gregtech/textures/gui/icon/macerator_recycling.png
  src/test/java/gregtech/api/capability/impl/AbstractRecipeLogicTest.java
  src/test/java/gregtech/api/recipes/RecipeMapTest.java
  src/test/java/gregtech/api/recipes/logic/IParallelableRecipeLogicTest.java
Labels: type: feature

#1842 Fix infinite bus collapsing
  src/main/java/gregtech/api/util/GTHashMaps.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
Labels: type: bug

#1769 Allow renaming machines placed in the world
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
Labels: type: feature

#1844 Remove unneeded RecipePropertyStorage logging
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/recipes/recipeproperties/EmptyRecipePropertyStorage.java
  src/main/java/gregtech/api/recipes/recipeproperties/RecipePropertyStorage.java
Labels: type: feature

#1830 Assembly Line Research and Ordered Inputs
  src/main/java/gregtech/api/capability/IDataAccessHatch.java
  src/main/java/gregtech/api/items/metaitem/stats/IDataItem.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockAbility.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/builders/AssemblyLineRecipeBuilder.java
  src/main/java/gregtech/api/recipes/machines/IResearchRecipeMap.java
  src/main/java/gregtech/api/recipes/machines/IScannerRecipeMap.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapAssemblyLine.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapScanner.java
  src/main/java/gregtech/api/recipes/recipeproperties/ResearchProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/ResearchPropertyData.java
  src/main/java/gregtech/api/util/AssemblyLineManager.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/behaviors/DataItemBehavior.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityDataAccessHatch.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/integration/jei/recipe/RecipeMapCategory.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_data_hatch.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_data_hatch_creative.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_data_hatch_creative_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_data_hatch_creative_emissive.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_data_hatch_emissive.png
Labels: type: feature

#1846 add GTUtility#gregtechId
  src/main/java/gregtech/api/capability/GregtechCapabilities.java
  src/main/java/gregtech/api/cover/CoverBehaviorUIFactory.java
  src/main/java/gregtech/api/fluids/MetaFluids.java
  src/main/java/gregtech/api/gui/resources/AdoptableTextureArea.java
  src/main/java/gregtech/api/gui/resources/ResourceHelper.java
  src/main/java/gregtech/api/gui/resources/SizedTextureArea.java
  src/main/java/gregtech/api/gui/resources/TextureArea.java
  src/main/java/gregtech/api/items/gui/PlayerInventoryUIFactory.java
  src/main/java/gregtech/api/items/metaitem/MetaItem.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityUIFactory.java
  src/main/java/gregtech/api/modules/IModuleManager.java
  src/main/java/gregtech/api/unification/material/info/MaterialIconType.java
  src/main/java/gregtech/api/util/CapesRegistry.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/worldgen/generator/GTWorldGenCapability.java
  src/main/java/gregtech/client/event/FluidVisualHandler.java
  src/main/java/gregtech/client/model/ActiveVariantBlockBakedModel.java
  src/main/java/gregtech/client/model/OreBakedModel.java
  src/main/java/gregtech/client/model/lamp/LampBakedModel.java
  src/main/java/gregtech/client/model/lamp/LampModelType.java
  src/main/java/gregtech/client/model/modelfactories/MaterialBlockModelLoader.java
  src/main/java/gregtech/client/renderer/handler/CCLBlockRenderer.java
  src/main/java/gregtech/client/renderer/handler/GTBoatRenderer.java
  src/main/java/gregtech/client/renderer/handler/MetaTileEntityRenderer.java
  src/main/java/gregtech/client/renderer/handler/PortalRenderer.java
  src/main/java/gregtech/client/renderer/pipe/CableRenderer.java
  src/main/java/gregtech/client/renderer/pipe/FluidPipeRenderer.java
  src/main/java/gregtech/client/renderer/pipe/ItemPipeRenderer.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/client/renderer/texture/custom/CrateRenderer.java
  src/main/java/gregtech/client/renderer/texture/custom/LargeTurbineRenderer.java
  src/main/java/gregtech/common/MetaEntities.java
  src/main/java/gregtech/common/blocks/BlockSurfaceRock.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/covers/CoverBehaviors.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/behaviors/MultiblockBuilderBehavior.java
  src/main/java/gregtech/common/items/behaviors/NanoSaberBehavior.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeEnergy.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityLockedSafe.java
  src/main/java/gregtech/common/terminal/app/guide/MultiBlockGuideApp.java
  src/main/java/gregtech/common/terminal/app/guide/SimpleMachineGuideApp.java
  src/main/java/gregtech/core/advancement/internal/AdvancementTrigger.java
  src/main/java/gregtech/integration/IntegrationSubmodule.java
  src/main/java/gregtech/integration/jei/recipe/FacadeRegistryPlugin.java
  src/main/java/gregtech/integration/jei/recipe/IntCircuitCategory.java
  src/main/java/gregtech/modules/BaseGregTechModule.java
  src/main/java/gregtech/tools/enchants/EnchantmentEnderDamage.java
  src/main/java/gregtech/tools/enchants/EnchantmentHardHammer.java
  src/test/java/gregtech/api/capability/impl/AbstractRecipeLogicTest.java
  src/test/java/gregtech/api/capability/impl/MultiblockRecipeLogicTest.java
  src/test/java/gregtech/api/recipes/logic/IParallelableRecipeLogicTest.java
  src/test/java/gregtech/api/recipes/logic/ParallelLogicTest.java
  src/test/java/gregtech/common/metatileentities/converter/ConverterTraitTest.java
Labels: type: refactor

#1838 Fix ItemStack count GUI overlap in Crafting Station
  src/main/java/gregtech/common/gui/widget/craftingstation/ItemListSlotWidget.java
Labels: type: bug

#1849 Remove Tin fluid block
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
Labels: type: refactor

#1848 Fix tooltip in App Store terminal App
  src/main/java/gregtech/common/terminal/app/appstore/AppPageWidget.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: bug

#1845 Fix clean multiblocks config with the PA
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/multiblock/DummyCleanroom.java
  src/main/java/gregtech/api/metatileentity/multiblock/ICleanroomProvider.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityCleaningMaintenanceHatch.java
Labels: type: bug

#1850 fix AL not running recipes without research properties
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
Labels: ignore changelog

#1857 Fix behavior of OreProperty#setOreByProducts
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/properties/OreProperty.java
Labels: type: refactor

#1856 fix fluid hatches not notifying multiblocks
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiblockNotifiablePart.java
Labels: type: bug

#1858 Optical cables and Data Bank
  README.md
  src/main/java/gregtech/api/capability/GregtechTileCapabilities.java
  src/main/java/gregtech/api/capability/IDataAccessHatch.java
  src/main/java/gregtech/api/capability/IOpticalDataAccessHatch.java
  src/main/java/gregtech/api/capability/SimpleCapabilityManager.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockAbility.java
  src/main/java/gregtech/api/pipenet/PipeNet.java
  src/main/java/gregtech/client/ClientProxy.java
  src/main/java/gregtech/client/renderer/pipe/OpticalPipeRenderer.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/blocks/BlockComputerCasing.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDataBank.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityAutoMaintenanceHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityDataAccessHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityOpticalDataHatch.java
  src/main/java/gregtech/common/pipelike/optical/BlockOpticalPipe.java
  src/main/java/gregtech/common/pipelike/optical/ItemBlockOpticalPipe.java
  src/main/java/gregtech/common/pipelike/optical/OpticalPipeProperties.java
  src/main/java/gregtech/common/pipelike/optical/OpticalPipeType.java
  src/main/java/gregtech/common/pipelike/optical/net/OpticalNetHandler.java
  src/main/java/gregtech/common/pipelike/optical/net/OpticalNetWalker.java
  src/main/java/gregtech/common/pipelike/optical/net/OpticalPipeNet.java
  src/main/java/gregtech/common/pipelike/optical/net/WorldOpticalPipeNet.java
  src/main/java/gregtech/common/pipelike/optical/tile/TileEntityOpticalPipe.java
  src/main/java/gregtech/common/pipelike/optical/tile/TileEntityOpticalPipeTickable.java
  src/main/java/gregtech/core/sound/GTSoundEvents.java
  src/main/java/gregtech/loaders/recipe/ComponentRecipes.java
  src/main/resources/assets/gregtech/blockstates/computer_casing.json
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/sounds.json
  src/main/resources/assets/gregtech/sounds/computation.ogg
  src/main/resources/assets/gregtech/textures/blocks/casings/computer/computer_casing/back.png
  src/main/resources/assets/gregtech/textures/blocks/casings/computer/computer_casing/bottom.png
  src/main/resources/assets/gregtech/textures/blocks/casings/computer/computer_casing/front.png
  src/main/resources/assets/gregtech/textures/blocks/casings/computer/computer_casing/side.png
  src/main/resources/assets/gregtech/textures/blocks/casings/computer/computer_casing/top.png
  src/main/resources/assets/gregtech/textures/blocks/casings/computer/computer_heat_vent_side.png
  src/main/resources/assets/gregtech/textures/blocks/casings/computer/computer_heat_vent_top_bot.png
  src/main/resources/assets/gregtech/textures/blocks/casings/computer/high_power_casing.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/data_bank/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/data_bank/overlay_front.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/multiblock/data_bank/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/data_bank/overlay_front_active.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/multiblock/data_bank/overlay_front_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/data_bank/overlay_front_active_emissive.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/multiblock/data_bank/overlay_front_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock/data_bank/overlay_front_emissive.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_data_hatch_optical.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_data_hatch_optical.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_data_hatch_optical_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/machine/overlay_data_hatch_optical_emissive.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/pipe/pipe_optical_in.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/pipe_optical_side.png
Labels: type: feature

#1860 Smooth progress bars
  src/main/java/gregtech/api/gui/resources/AdoptableTextureArea.java
  src/main/java/gregtech/api/gui/resources/TextureArea.java
  src/main/java/gregtech/api/gui/widgets/ProgressWidget.java
  src/main/java/gregtech/common/ConfigHolder.java
Labels: type: feature

#1867 polarizer voltage tweaks
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/loaders/recipe/handlers/PolarizingRecipeHandler.java
Labels: type: feature

#1862 Improved optical cable rendering
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/client/renderer/pipe/OpticalPipeRenderer.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
  src/main/java/gregtech/common/pipelike/optical/net/OpticalNetHandler.java
  src/main/java/gregtech/common/pipelike/optical/tile/TileEntityOpticalPipe.java
  src/main/resources/assets/gregtech/blockstates/optical_pipe_normal.json
  src/main/resources/assets/gregtech/textures/blocks/pipe/pipe_optical_side_overlay.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/pipe_optical_side_overlay_active.png
  src/main/resources/assets/gregtech/textures/blocks/pipe/pipe_optical_side_overlay_active.png.mcmeta
Labels: ignore changelog

#1863 Optical cable improvements
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/pipelike/optical/BlockOpticalPipe.java
  src/main/java/gregtech/common/pipelike/optical/net/OpticalNetHandler.java
  src/main/java/gregtech/common/pipelike/optical/net/OpticalNetWalker.java
  src/main/java/gregtech/common/pipelike/optical/net/OpticalPipeNet.java
  src/main/java/gregtech/common/pipelike/optical/tile/TileEntityOpticalPipe.java
  src/main/java/gregtech/common/pipelike/optical/tile/TileEntityOpticalPipeTickable.java
Labels: ignore changelog

#1875 Fix crash with TOP in live environment
  src/main/java/gregtech/GregTechMod.java
Labels: ignore changelog

#1876 fix missing recipe category copy in RecipeBuilder
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
Labels: ignore changelog

#1877 Remove IFuelable
  src/main/java/gregtech/api/capability/GregtechCapabilities.java
  src/main/java/gregtech/api/capability/IFuelable.java
  src/main/java/gregtech/api/capability/SimpleCapabilityManager.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamCoalBoiler.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamLavaBoiler.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeModule.java
  src/main/java/gregtech/integration/theoneprobe/provider/FuelableInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/lang/ja_jp.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: refactor

#1861 Fix custom MaterialIconSet not being registered for model
  src/main/java/gregtech/api/unification/material/info/MaterialIconSet.java
Labels: type: bug

#1874 Malfunction sounds
  src/main/java/gregtech/api/metatileentity/multiblock/IMaintenance.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCrackingUnit.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDistillationTower.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityElectricBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityImplosionCompressor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeChemicalReactor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiSmelter.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPyrolyseOven.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityVacuumFreezer.java
  src/main/java/gregtech/core/sound/GTSoundEvents.java
  src/main/resources/assets/gregtech/sounds.json
  src/main/resources/assets/gregtech/sounds/breakdown_electric.ogg
  src/main/resources/assets/gregtech/sounds/breakdown_mechanical.ogg
Labels: type: feature

#1878 HWYLA compat
  dependencies.gradle
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/integration/hwyla/HWYLAClient.java
  src/main/java/gregtech/integration/hwyla/HWYLAModule.java
  src/main/java/gregtech/integration/hwyla/provider/BlockOreDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/CapabilityDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/ControllableDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/ConverterDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/DiodeDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/ElectricContainerDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/LampDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/MaintenanceDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/MultiRecipeMapDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/MultiblockDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/PrimitivePumpDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/RecipeLogicDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/TransformerDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/WorkableDataProvider.java
  src/main/java/gregtech/integration/hwyla/renderer/RendererOffsetString.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeModule.java
  src/main/java/gregtech/integration/theoneprobe/provider/BlockOreInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/CoverInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/DiodeInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/TransformerInfoProvider.java
  src/main/java/gregtech/modules/GregTechModules.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/lang/ja_jp.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: feature

#1884 Change multiblock jei category icon
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/java/gregtech/integration/jei/multiblock/MultiblockInfoCategory.java
  src/main/resources/assets/gregtech/terminal/guide/tutorials/en_us/guide_widget_api/api_3_image.json
  src/main/resources/assets/gregtech/textures/gui/icon/coke_oven.png
  src/main/resources/assets/gregtech/textures/gui/icon/multiblock_category.png
Labels: type: feature

#1767 Improve Multiblock GUI
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/api/metatileentity/WorkableTieredMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/multiblock/FuelMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/TextFormattingUtil.java
  src/main/java/gregtech/common/items/behaviors/TricorderBehavior.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityBatteryBuffer.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityElectricBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/LargeTurbineWorkableHandler.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeCombustionEngine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java
  src/main/java/gregtech/common/pipelike/cable/tile/TileEntityCable.java
  src/main/java/gregtech/common/pipelike/fluidpipe/tile/TileEntityFluidPipeTickable.java
  src/main/java/gregtech/common/terminal/app/prospector/widget/WidgetProspectingMap.java
  src/main/java/gregtech/integration/theoneprobe/provider/CoverInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#1886 Allow LCR to accept any coil
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeChemicalReactor.java
Labels: type: feature

#1885 Improve and fix GTRecipeHandler#removeAllRecipes
  src/main/java/gregtech/api/recipes/GTRecipeHandler.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: type: bug

#1883 Improve TE Networking Performance
  src/main/java/gregtech/api/metatileentity/SyncedTileEntityBase.java
Labels: type: feature

#1888 Ignore nbt on lapotron inputs
  src/main/java/gregtech/loaders/recipe/BatteryRecipes.java
  src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
Labels: type: bug

#1870 Remove Robot Arm Multiplier Stepping Down to Item Amount
  src/main/java/gregtech/common/covers/CoverRoboticArm.java
Labels: type: refactor

#1890 Fix method name reobf issue with Battery Data
  src/main/java/gregtech/api/metatileentity/multiblock/IBatteryData.java
  src/main/java/gregtech/common/blocks/BlockBatteryPart.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPowerSubstation.java
  src/test/java/gregtech/common/metatileentities/multiblock/PowerSubstationTest.java
Labels: ignore changelog

#1891 Prevent merging electric tools in anvil
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: type: bug

#1892 Fix central monitor screen being rotatable with wrench
  src/main/java/gregtech/common/metatileentities/multi/electric/centralmonitor/MetaTileEntityMonitorScreen.java
Labels: type: bug
