Repository GregTechCEu/GregTech, pull requests merged in 2024-04, with the labels that each got.

#2438 cleanup stacktrace logging for recipe errors
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/builders/AssemblyLineRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/BlastRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/CircuitAssemblerRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/ComputationRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/FusionRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/ImplosionRecipeBuilder.java
  src/main/java/gregtech/api/recipes/ingredients/nbtmatch/ListNBTCondition.java
  src/main/java/gregtech/api/recipes/ingredients/nbtmatch/NBTCondition.java
  src/main/java/gregtech/api/recipes/recipeproperties/IRecipePropertyStorage.java
  src/main/java/gregtech/api/recipes/recipeproperties/RecipePropertyStorage.java
Labels: type: refactor

#2440 fix MTE block opacity
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/block/machines/MachineItemBlock.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCrate.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityDrum.java
Labels: type: bug

#2441 minor allocation optimization for GTUtility#canSeeSunClearly
  src/main/java/gregtech/api/util/GTUtility.java
Labels: type: feature

#2437 Fix potential MetaTileEntity NPE when calling a server side method on client
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
Labels: type: bug

#2435 Add stairsRecipeName
  src/main/java/gregtech/loaders/WoodTypeEntry.java
  src/main/java/gregtech/loaders/recipe/WoodRecipeLoader.java
Labels: type: feature

#2318 Improve the Quantum Storage Renderer
  src/main/java/gregtech/api/gui/resources/TextTexture.java
  src/main/java/gregtech/client/renderer/handler/MetaTileEntityTESR.java
  src/main/java/gregtech/client/renderer/texture/custom/QuantumStorageRenderer.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeTank.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: type: refactor

#2331 adjust recipe input expected cache size dynamically
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/persistence/PersistentData.java
  src/main/java/gregtech/api/recipes/GTRecipeInputCache.java
Labels: type: feature

#2425 GroovyScript 1.0.0
  dependencies.gradle
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/integration/groovy/GroovyExpansions.java
  src/main/java/gregtech/integration/groovy/GroovyMaterialBuilderExpansion.java
  src/main/java/gregtech/integration/groovy/GroovyScriptModule.java
  src/main/java/gregtech/integration/groovy/MaterialExpansion.java
  src/main/java/gregtech/integration/groovy/MaterialPropertyExpansion.java
  src/main/java/gregtech/integration/groovy/PropertyContainer.java
  src/main/java/gregtech/integration/groovy/VirtualizedRecipeMap.java
Labels: type: feature, integration: GrS

#2452 fix primitive multiblocks allowing automation through their controller
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapPrimitiveMultiblockController.java
Labels: type: bug

#2451 Waila/Hwyla Provider Fixes
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/util/GTLog.java
  src/main/java/gregtech/api/util/input/KeyBind.java
  src/main/java/gregtech/integration/forestry/bees/GTBeeDefinition.java
  src/main/java/gregtech/integration/groovy/GroovyScriptModule.java
  src/main/java/gregtech/integration/hwyla/provider/BlockOreDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/ControllableDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/ConverterDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/DiodeDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/ElectricContainerDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/LampDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/MaintenanceDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/MultiRecipeMapDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/MultiblockDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/PrimitivePumpDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/RecipeLogicDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/SteamBoilerDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/TransformerDataProvider.java
  src/main/java/gregtech/integration/hwyla/provider/WorkableDataProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: bug

#2446 Fix blocks not being able to choose preferred meta values in previews
  src/main/java/gregtech/integration/jei/multiblock/MultiblockInfoRecipeWrapper.java
Labels: type: bug

#2444 Fix display of sifter byproducts for materials with no exquisite
  src/main/java/gregtech/integration/jei/basic/OreByProduct.java
  src/main/java/gregtech/integration/jei/basic/OreByProductCategory.java
Labels: type: bug

#2453 Fix possible NPE from MultiblockDisplayText
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockDisplayText.java
Labels: type: bug

#2443 fix NPE with null fluids in quantum tanks
  src/main/java/gregtech/client/renderer/texture/custom/QuantumStorageRenderer.java
Labels: type: bug
