Repository GregTechCEu/GregTech, pull requests merged in 2024-11, with the labels that each got.

#2654 Small access restriction change in order to create a fluid hatch subclass
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityFluidHatch.java
Labels: type: refactor

#2656 Cleanup and remove some CCL library code usage
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/client/ClientProxy.java
  src/main/java/gregtech/client/model/modelfactories/BakedModelHandler.java
  src/main/java/gregtech/client/renderer/ICCLBlockRenderer.java
  src/main/java/gregtech/client/renderer/ICubeRenderer.java
  src/main/java/gregtech/client/renderer/handler/CCLBlockRenderer.java
  src/main/java/gregtech/client/renderer/handler/MetaTileEntityRenderer.java
  src/main/java/gregtech/client/renderer/pipe/CableRenderer.java
  src/main/java/gregtech/client/renderer/pipe/PipeRenderer.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/client/renderer/texture/custom/ClipboardRenderer.java
  src/main/java/gregtech/client/renderer/texture/custom/CrateRenderer.java
  src/main/java/gregtech/client/renderer/texture/custom/DrumRenderer.java
  src/main/java/gregtech/client/renderer/texture/custom/LargeTurbineRenderer.java
  src/main/java/gregtech/client/renderer/texture/custom/QuantumStorageRenderer.java
  src/main/java/gregtech/client/texture/IconRegistrar.java
  src/main/java/gregtech/client/utils/RenderUtil.java
Labels: type: refactor

#2655 fix laser hatch recipes
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
Labels: type: bug

#2647 Fix Issues with Switching Modes on MultiMapMultiblockController
  src/main/java/gregtech/api/metatileentity/multiblock/MultiMapMultiblockController.java
Labels: type: bug

#2657 Fix stackoverflow & update GroovyScript
  dependencies.gradle
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/integration/groovy/GrSRecipeHelper.java
  src/main/java/gregtech/integration/groovy/GroovyExpansions.java
Labels: type: bug, integration: GrS

#2652 Removed the no smelting flag from Galena
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
Labels: type: bug

#2648 Fix Issues with Transporting Some Items to Some Inventories
  src/main/java/gregtech/api/util/GTTransferUtils.java
Labels: type: bug

#2650 Let recipe builders skip map build actions
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
Labels: type: feature

#2649 Fix Voiding and Incorrect Input Consumption in Parallel Recipes
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/util/OverlayedItemHandler.java
  src/test/java/gregtech/api/recipes/logic/IParallelableRecipeLogicTest.java
Labels: type: bug

#2630 Add methods to change a material's composition
  src/main/java/gregtech/api/unification/material/Material.java
Labels: type: feature

#2608 Fix Stocking Buses running recipes while offline
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityAEHostablePart.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingHatch.java
Labels: type: bug
