Repository GregTechCEu/GregTech, pull requests merged in 2024-07, with the labels that each got.

#2506 GroovyScript 1.1.0
  dependencies.gradle
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/core/unification/material/internal/MaterialRegistryManager.java
  src/main/java/gregtech/integration/groovy/GroovyMaterialBuilderExpansion.java
  src/main/java/gregtech/integration/groovy/GroovyScriptModule.java
  src/main/java/gregtech/integration/groovy/PropertyContainer.java
  src/main/java/gregtech/integration/groovy/VirtualizedRecipeMap.java
Labels: type: feature, integration: GrS

#2503 Update build script version to 1720106721
  build.gradle
Labels: ignore changelog

#2514 Fix liquid and gas registry key functions overlapping
  src/main/java/gregtech/api/fluids/FluidBuilder.java
  src/main/java/gregtech/api/fluids/GTFluidRegistration.java
  src/main/java/gregtech/api/fluids/store/FluidStorage.java
  src/main/java/gregtech/api/fluids/store/FluidStorageImpl.java
  src/main/java/gregtech/api/fluids/store/FluidStorageKey.java
  src/main/java/gregtech/api/fluids/store/FluidStorageKeys.java
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/properties/FluidProperty.java
  src/main/java/gregtech/integration/crafttweaker/material/MaterialExpansion.java
  src/main/java/gregtech/integration/crafttweaker/material/MaterialPropertyExpansion.java
  src/main/java/gregtech/integration/groovy/MaterialExpansion.java
  src/main/java/gregtech/integration/groovy/MaterialPropertyExpansion.java
Labels: type: bug

#2388 Split assembler and circuit assembler textures
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/resources/assets/gregtech/textures/blocks/machines/circuit_assembler/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/machines/circuit_assembler/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/circuit_assembler/overlay_front_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/circuit_assembler/overlay_front_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/circuit_assembler/overlay_front_paused.png
  src/main/resources/assets/gregtech/textures/blocks/machines/circuit_assembler/overlay_front_paused_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/circuit_assembler/overlay_top.png
  src/main/resources/assets/gregtech/textures/blocks/machines/circuit_assembler/overlay_top_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/circuit_assembler/overlay_top_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/circuit_assembler/overlay_top_emissive.png
Labels: type: feature

#2516 bump GHA versions
  .github/actions/build_setup/action.yml
  .github/workflows/publish_project.yml
  .github/workflows/update_buildscript.yml
  .github/workflows/validate_gradle_wrapper.yml
Labels: ignore changelog

#2519 Fix failing builds due to Vintagium
  dependencies.gradle
  src/api/java/me/jellysquid/mods/sodium/client/render/chunk/passes/BlockRenderPass.java
  src/api/java/me/jellysquid/mods/sodium/client/render/chunk/passes/BlockRenderPassManager.java
  src/api/java/me/jellysquid/mods/sodium/client/util/BufferSizeUtil.java
  src/api/java/me/jellysquid/mods/sodium/client/util/EnumUtil.java
  src/main/java/gregtech/mixins/vintagium/BlockRenderManagerMixin.java
  src/main/java/gregtech/mixins/vintagium/BlockRenderPassMixin.java
Labels: status: high priority, ignore changelog

#2520 Fix Mixin Warnings About `maxShiftBy`
  src/main/resources/mixins.gregtech.minecraft.json
Labels: ignore changelog

#2521 fix failing builds due to Vintagium
  dependencies.gradle
  src/api/java/me/jellysquid/mods/sodium/client/render/chunk/passes/BlockRenderPass.java
  src/api/java/me/jellysquid/mods/sodium/client/util/BufferSizeUtil.java
  src/api/java/me/jellysquid/mods/sodium/client/util/EnumUtil.java
Labels: ignore changelog

#2524 Improvement to DT hatch logic
  src/main/java/gregtech/api/capability/IDistillationTower.java
  src/main/java/gregtech/api/capability/impl/DistillationTowerLogicHandler.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDistillationTower.java
Labels: type: refactor

#2523 Update ru_RU lang for 2.8.9
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: type: translation

#2522 Update Gradle and related files
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ignore changelog

#2526 Fix the lighter behaviour
  src/main/java/gregtech/common/items/behaviors/LighterBehaviour.java
Labels: type: bug

#2512 Fix EUt usage of HPCA with custom higher tier Components
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityHPCA.java
  src/test/java/gregtech/common/metatileentities/multiblock/hpca/HPCATest.java
Labels: type: bug

#2528 bump GRS and CT versions in gradle
  dependencies.gradle
Labels: ignore changelog

#2529 Fix Miner Pipe Deleting TileEntities
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
Labels: type: bug

#2527 Make drums no longer require a Material
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityDrum.java
Labels: type: feature

#2534 Update and Fix ja_jp.lang for 2.8.10
  src/main/resources/assets/gregtech/lang/ja_jp.lang
Labels: type: translation

#2531 fix crash with Forestry integration
  src/main/java/gregtech/api/unification/OreDictUnifier.java
  src/main/java/gregtech/integration/forestry/mutation/MaterialMutationCondition.java
Labels: type: bug

#2515 fix MTE data fixer registry conflicts
  src/main/java/gregtech/datafix/GTDataFixers.java
  src/main/java/gregtech/datafix/migration/lib/MTERegistriesMigrator.java
  src/main/java/gregtech/integration/groovy/GroovyScriptModule.java
Labels: ignore changelog

#2518 Adjust EV coil recipe & texture
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/loaders/recipe/chemistry/AssemblerRecipeLoader.java
  src/main/resources/assets/gregtech/textures/items/metaitems/voltage_coil.ev.png
Labels: type: feature

#2538 Add Overload to `where()` in FactoryBlockPattern
  src/main/java/gregtech/api/pattern/FactoryBlockPattern.java
Labels: type: refactor

#2544 Update to MUI 2.5.0-RC1
  dependencies.gradle
  src/main/java/gregtech/api/cover/CoverWithUI.java
  src/main/java/gregtech/api/items/gui/ItemUIFactory.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/mui/GTGuis.java
  src/main/java/gregtech/api/mui/widget/GhostCircuitSlotWidget.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverEnderFluidLink.java
  src/main/java/gregtech/common/covers/CoverFluidFilter.java
  src/main/java/gregtech/common/covers/CoverFluidRegulator.java
  src/main/java/gregtech/common/covers/CoverFluidVoiding.java
  src/main/java/gregtech/common/covers/CoverFluidVoidingAdvanced.java
  src/main/java/gregtech/common/covers/CoverItemFilter.java
  src/main/java/gregtech/common/covers/CoverItemVoiding.java
  src/main/java/gregtech/common/covers/CoverItemVoidingAdvanced.java
  src/main/java/gregtech/common/covers/CoverMachineController.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/covers/CoverRoboticArm.java
  src/main/java/gregtech/common/covers/CoverStorage.java
  src/main/java/gregtech/common/covers/filter/BaseFilter.java
  src/main/java/gregtech/common/covers/filter/BaseFilterContainer.java
  src/main/java/gregtech/common/covers/filter/IFilter.java
  src/main/java/gregtech/common/covers/filter/OreDictionaryItemFilter.java
  src/main/java/gregtech/common/covers/filter/SimpleFluidFilter.java
  src/main/java/gregtech/common/covers/filter/SimpleItemFilter.java
  src/main/java/gregtech/common/covers/filter/SmartItemFilter.java
  src/main/java/gregtech/common/items/behaviors/IntCircuitBehaviour.java
  src/main/java/gregtech/common/items/behaviors/filter/BaseFilterUIManager.java
  src/main/java/gregtech/common/items/behaviors/filter/OreDictFilterUIManager.java
  src/main/java/gregtech/common/items/behaviors/filter/SimpleFilterUIManager.java
  src/main/java/gregtech/common/items/behaviors/filter/SimpleFluidFilterUIManager.java
  src/main/java/gregtech/common/items/behaviors/filter/SmartFilterUIManager.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/steam/multiblockpart/MetaTileEntitySteamItemBus.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCrate.java
Labels: type: refactor

#2545 fix most gases using the wrong translation key
  src/main/java/gregtech/api/fluids/store/FluidStorageKeys.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
Labels: type: bug

#2432 Recipe logic and Overclocking changes
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/ComputationRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/EUToFEProvider.java
  src/main/java/gregtech/api/capability/impl/FuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/HeatingCoilRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/PrimitiveRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/RecipeLogicEnergy.java
  src/main/java/gregtech/api/capability/impl/RecipeLogicSteam.java
  src/main/java/gregtech/api/capability/impl/SteamMultiWorkable.java
  src/main/java/gregtech/api/capability/impl/SteamMultiblockRecipeLogic.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/RecipeMapBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/builders/UniversalDistillationRecipeBuilder.java
  src/main/java/gregtech/api/recipes/logic/OCParams.java
  src/main/java/gregtech/api/recipes/logic/OCResult.java
  src/main/java/gregtech/api/recipes/logic/OverclockingLogic.java
  src/main/java/gregtech/api/recipes/logic/ParallelLogic.java
  src/main/java/gregtech/api/recipes/ui/RecipeMapUI.java
  src/main/java/gregtech/api/recipes/ui/impl/AssemblyLineUI.java
  src/main/java/gregtech/api/recipes/ui/impl/CokeOvenUI.java
  src/main/java/gregtech/api/recipes/ui/impl/CrackerUnitUI.java
  src/main/java/gregtech/api/recipes/ui/impl/DistillationTowerUI.java
  src/main/java/gregtech/api/recipes/ui/impl/FormingPressUI.java
  src/main/java/gregtech/api/recipes/ui/impl/ResearchStationUI.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCrackingUnit.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDistillationTower.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiSmelter.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPyrolyseOven.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityResearchStation.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/LargeTurbineWorkableHandler.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeCombustionEngine.java
  src/main/java/gregtech/integration/crafttweaker/recipe/CTRecipe.java
  src/main/java/gregtech/integration/hwyla/provider/RecipeLogicDataProvider.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/integration/theoneprobe/provider/RecipeLogicInfoProvider.java
  src/main/java/gregtech/loaders/recipe/FuelRecipes.java
  src/test/java/gregtech/api/capability/impl/AbstractRecipeLogicTest.java
  src/test/java/gregtech/api/capability/impl/MultiblockRecipeLogicTest.java
  src/test/java/gregtech/api/recipes/logic/IParallelableRecipeLogicTest.java
  src/test/java/gregtech/api/recipes/logic/OverclockingTest.java
  src/test/java/gregtech/api/recipes/logic/ParallelLogicTest.java
Labels: type: feature

#2547 MTE registries datafixer for BQu
  src/main/java/gregtech/api/util/Mods.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/datafix/command/CommandDataFix.java
  src/main/java/gregtech/integration/bq/BQuDataFixer.java
  src/main/java/gregtech/integration/bq/CommandBQuDataFix.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2366 Titanium Tweaks
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/MaterialFlagAddition.java
  src/main/java/gregtech/api/unification/material/materials/UnknownCompositionMaterials.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/ChemistryRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/ReactorRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/TitaniumRecipes.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2289 SimpleMachineMetaTileEntity makes it easy to change the logo
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
Labels: type: feature
