Repository GregTechCEu/GregTech, pull requests merged in 2024-06, with the labels that each got.

#2485 Fix the large turbine rotor texture
  src/main/resources/assets/gregtech/textures/blocks/multiblock/large_turbine/rotor_spinning.png
Labels: type: bug

#2458 Small QoL Bee Update
  src/main/java/gregtech/integration/forestry/mutation/MaterialMutationCondition.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2487 Fix excessive packets & re-renders with AEHostable parts
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityAEHostablePart.java
Labels: type: bug

#2477 Allow dynamic hatch placement on Distillation Tower
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDistillationTower.java
Labels: type: feature

#2484 Add a faster recipe for drilling fluid with distilled water
  src/main/java/gregtech/loaders/recipe/chemistry/MixerRecipes.java
Labels: type: feature

#2489 Fix input busses saying "Item Auto-Output Enabled" instead of "Item Auto-Input Enabled"
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2449 fix pyrolyse speed
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPyrolyseOven.java
Labels: type: bug

#2475 Brute-force Fix of RAM Usage Problem When Using Alfheim
  src/main/java/gregtech/api/util/Mods.java
  src/main/java/gregtech/api/util/world/DummyWorld.java
Labels: type: bug

#2488 Clean up AEHostable part fix
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityAEHostablePart.java
Labels: type: bug

#2480 Various Cleanroom Improvements
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/block/ICleanroomFilter.java
  src/main/java/gregtech/api/capability/impl/CleanroomLogic.java
  src/main/java/gregtech/common/blocks/BlockCleanroomCasing.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2486 Updating bees using the new Mutation Condition
  src/main/java/gregtech/integration/forestry/bees/GTBeeDefinition.java
Labels: type: feature

#2479 Allow MTEs / recipe map workables to directly control their JEI categories
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/api/recipes/category/ICategoryOverride.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamCoalBoiler.java
  src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java
Labels: type: feature

#1063 Rounds energy displayed by TOP
  src/main/java/gregtech/integration/theoneprobe/provider/ElectricContainerInfoProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/LaserContainerInfoProvider.java
Labels: type: feature

#2496 Allow recipe logic to set EU/t and speed discounts
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/test/java/gregtech/api/capability/impl/AbstractRecipeLogicTest.java
Labels: type: feature

#2192 Convert from ASM to Mixins
  addon.gradle
  dependencies.gradle
  gradle.properties
  src/api/java/com/creativemd/littletiles/client/render/cache/LayeredRenderBoxCache.java
  src/api/java/com/creativemd/littletiles/client/render/tile/LittleRenderBox.java
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/damagesources/DamageSources.java
  src/main/java/gregtech/api/items/metaitem/MusicDiscStats.java
  src/main/java/gregtech/api/util/Mods.java
  src/main/java/gregtech/asm/GregTechLoadingPlugin.java
  src/main/java/gregtech/asm/GregTechTransformer.java
  src/main/java/gregtech/client/utils/BloomEffectVintagiumUtil.java
  src/main/java/gregtech/mixins/GregTechLateMixinLoadingPlugin.java
  src/main/java/gregtech/mixins/ccl/CCLDescriptionMixin.java
  src/main/java/gregtech/mixins/ctm/AbstractCTMBakedModelMixin.java
  src/main/java/gregtech/mixins/ctm/CTMRenderInLayerMixin.java
  src/main/java/gregtech/mixins/forge/ModelLoaderRegistryMixin.java
  src/main/java/gregtech/mixins/forge/SpecialArmorPropertiesMixin.java
  src/main/java/gregtech/mixins/jei/JEITooltipMixin.java
  src/main/java/gregtech/mixins/littletiles/LittleTilesRenderMangerMixin.java
  src/main/java/gregtech/mixins/minecraft/BlockConcretePowderMixin.java
  src/main/java/gregtech/mixins/minecraft/BlockMixin.java
  src/main/java/gregtech/mixins/minecraft/DamageSourceMixin.java
  src/main/java/gregtech/mixins/minecraft/EnchantmentCanApplyMixin.java
  src/main/java/gregtech/mixins/minecraft/EntityRendererMixin.java
  src/main/java/gregtech/mixins/minecraft/LayerArmorBaseMixin.java
  src/main/java/gregtech/mixins/minecraft/LayerCustomHeadMixin.java
  src/main/java/gregtech/mixins/minecraft/MinecraftMixin.java
  src/main/java/gregtech/mixins/minecraft/RecipeRepairItemMixin.java
  src/main/java/gregtech/mixins/minecraft/RegionRenderCacheBuilderMixin.java
  src/main/java/gregtech/mixins/minecraft/RenderChunkMixin.java
  src/main/java/gregtech/mixins/minecraft/RenderGlobalMixin.java
  src/main/java/gregtech/mixins/minecraft/RenderItemMixin.java
  src/main/java/gregtech/mixins/theoneprobe/TheOneProbeMixin.java
  src/main/java/gregtech/mixins/vintagium/BlockRenderManagerMixin.java
  src/main/java/gregtech/mixins/vintagium/BlockRenderPassMixin.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/mixins.gregtech.ccl.json
  src/main/resources/mixins.gregtech.ctm.json
  src/main/resources/mixins.gregtech.forge.json
  src/main/resources/mixins.gregtech.jei.json
  src/main/resources/mixins.gregtech.littletiles.json
  src/main/resources/mixins.gregtech.minecraft.json
  src/main/resources/mixins.gregtech.theoneprobe.json
  src/main/resources/mixins.gregtech.vintagium.json
Labels: type: feature

#2509 Glass tube recycling
  src/main/java/gregtech/common/items/MetaItem1.java
Labels: type: feature

#2495 Improve assembly line laser render
  src/main/java/gregtech/client/particle/GTLaserBeamParticle.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
Labels: type: feature

#2491 Dynamically change the direction of the arrow in "Manual IO Mode" to reflect the direction of the "IO Mode"
  src/main/java/gregtech/api/mui/GTGuiTextures.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/resources/assets/gregtech/textures/gui/overlay/manual_io_overlay_in.png
  src/main/resources/assets/gregtech/textures/gui/overlay/manual_io_overlay_out.png
Labels: type: refactor

#2428 Support Creative Mode Pick Block
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
Labels: type: feature

#2511 Add Polybenzimidazole Block Conversion Recipes
  src/main/java/gregtech/api/unification/material/materials/OrganicChemistryMaterials.java
Labels: type: feature
