Repository GregTechCEu/GregTech, pull requests merged in 2024-02, with the labels that each got.

#2371 Clean up MetaTileEntities class formatting
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
Labels: ignore changelog

#2370 Set Hardness and Resistance to LDP Blocks
  src/main/java/gregtech/api/pipenet/longdist/BlockLongDistancePipe.java
Labels: type: bug

#2365 Fix hasEnoughPower() check in ARL
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/PrimitiveRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/RecipeLogicSteam.java
  src/main/java/gregtech/api/capability/impl/SteamMultiblockRecipeLogic.java
Labels: type: bug

#2358 Use drain/extract for Recipe#matches
  src/main/java/gregtech/api/recipes/Recipe.java
Labels: type: refactor

#2375 Fix part sharing tooltip missing on some parts
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityComputationHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityDataAccessHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityObjectHolder.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityOpticalDataHatch.java
Labels: type: bug

#2376 re-enable sharing for laser hatches
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityLaserHatch.java
Labels: type: bug

#2381 Config and API for tick acceleration blocking
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityWorldAccelerator.java
Labels: type: feature

#2386 fix #2382
  src/main/java/gregtech/integration/jei/basic/MaterialTree.java
Labels: ignore changelog

#2380 Update build script version to 1707682661
  build.gradle
Labels: ignore changelog

#2379 Use GTCEu maven
  dependencies.gradle
  gradle.properties
Labels: ignore changelog

#2390 Fix parallel overclocks using the wrong voltage for multiblocks
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
Labels: type: bug

#2391 Temporary hotfix for research ID lookup
  src/main/java/gregtech/api/recipes/machines/RecipeMapAssemblyLine.java
Labels: type: bug

#2383 use chestWood oredict for ULV and LV item buses
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
Labels: type: feature
