Repository GregTechCEu/GregTech, pull requests merged in 2024-01, with the labels that each got.

#2312 MUI cover skeleton and Machine Controller Cover port
  src/main/java/gregtech/api/cover/Cover.java
  src/main/java/gregtech/api/cover/CoverWithUI.java
  src/main/java/gregtech/api/cover/CoverableView.java
  src/main/java/gregtech/api/items/behavior/CoverItemBehavior.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/mui/GTGuiTextures.java
  src/main/java/gregtech/api/mui/GTGuiTheme.java
  src/main/java/gregtech/api/pipenet/tile/PipeCoverableImplementation.java
  src/main/java/gregtech/common/covers/CoverMachineController.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/gui/widget/button_cross.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_redstone_off.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_redstone_on.png
Labels: type: feature

#2307 Update ru_ru.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: type: translation

#2323 Improve Lighter Opening
  src/main/java/gregtech/common/items/behaviors/LighterBehaviour.java
Labels: type: feature

#2337 Fix some JEI plugin issues
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java
Labels: integration: JEI, type: bug

#2339 Fix treated wood stick saw recipe
  src/main/java/gregtech/loaders/recipe/WoodRecipeLoader.java
Labels: type: bug

#2338 Various Fission Reactor fixes
  src/main/java/gregtech/api/nuclear/fission/FissionReactor.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/MaterialFlagAddition.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityFissionReactor.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityCoolantExportHatch.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2334 update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#2341 Update build script version to 1704659416
  build.gradle
  gradle.properties
  settings.gradle
Labels: ignore changelog

#2320 prevent potential ThreadLocal memory leaks
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/pipenet/block/BlockPipe.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
  src/main/java/gregtech/asm/hooks/CTMHooks.java
  src/main/java/gregtech/client/renderer/handler/MetaTileEntityRenderer.java
  src/main/java/gregtech/client/renderer/pipe/PipeRenderer.java
Labels: type: bug

#2317 move creative tabs out of GregTechAPI
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/block/VariantBlock.java
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/block/machines/MachineItemBlock.java
  src/main/java/gregtech/api/creativetab/BaseCreativeTab.java
  src/main/java/gregtech/api/items/armor/ArmorMetaItem.java
  src/main/java/gregtech/api/items/materialitem/MetaPrefixItem.java
  src/main/java/gregtech/api/items/metaitem/MetaItem.java
  src/main/java/gregtech/api/items/toolitem/ItemGTAxe.java
  src/main/java/gregtech/api/items/toolitem/ItemGTHoe.java
  src/main/java/gregtech/api/items/toolitem/ItemGTSword.java
  src/main/java/gregtech/api/items/toolitem/ItemGTTool.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/pipenet/longdist/BlockLongDistancePipe.java
  src/main/java/gregtech/common/blocks/BlockAsphalt.java
  src/main/java/gregtech/common/blocks/BlockCompressed.java
  src/main/java/gregtech/common/blocks/BlockFrame.java
  src/main/java/gregtech/common/blocks/BlockGregStairs.java
  src/main/java/gregtech/common/blocks/BlockLamp.java
  src/main/java/gregtech/common/blocks/BlockOre.java
  src/main/java/gregtech/common/blocks/BlockWarningSign.java
  src/main/java/gregtech/common/blocks/BlockWarningSign1.java
  src/main/java/gregtech/common/blocks/StoneVariantBlock.java
  src/main/java/gregtech/common/blocks/wood/BlockGregFence.java
  src/main/java/gregtech/common/blocks/wood/BlockGregFenceGate.java
  src/main/java/gregtech/common/blocks/wood/BlockGregWoodSlab.java
  src/main/java/gregtech/common/blocks/wood/BlockRubberLeaves.java
  src/main/java/gregtech/common/blocks/wood/BlockRubberLog.java
  src/main/java/gregtech/common/blocks/wood/BlockRubberSapling.java
  src/main/java/gregtech/common/creativetab/GTCreativeTabs.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/pipelike/cable/BlockCable.java
  src/main/java/gregtech/common/pipelike/fluidpipe/BlockFluidPipe.java
  src/main/java/gregtech/common/pipelike/itempipe/BlockItemPipe.java
  src/main/java/gregtech/common/pipelike/laser/BlockLaserPipe.java
  src/main/java/gregtech/common/pipelike/optical/BlockOpticalPipe.java
Labels: type: refactor

#2259 Make translation key of MetaItems modifiable
  src/main/java/gregtech/api/items/metaitem/MetaItem.java
Labels: type: refactor

#2344 Update build script version to 1705076830
  build.gradle
Labels: ignore changelog

#2311 Overload AbstractRecipeLogic functions
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/LargeTurbineWorkableHandler.java
Labels: type: refactor

#2343 Fix erroring material handlers when liquids don't exist
  src/main/java/gregtech/api/unification/material/properties/FluidProperty.java
  src/main/java/gregtech/loaders/recipe/handlers/MaterialRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/PartsRecipeHandler.java
Labels: type: bug

#2349 Fix reservoir hatch issues
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityReservoirHatch.java
Labels: type: bug

#2346 Fix LCE/ECE obstruction check
  src/main/java/gregtech/api/util/RelativeDirection.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeCombustionEngine.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityRotorHolder.java
Labels: type: bug

#2350 Fix electric tool damage config innacuracy
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
Labels: type: bug

#2352 Fix Issues with Fusion Reactor Overclocking
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
Labels: type: bug

#2353 Separate PSS average IO into in and out
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPowerSubstation.java
  src/main/java/gregtech/integration/opencomputers/drivers/specific/DriverPowerSubstation.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2319 fix gt tile entities not rendering in AE2 pattern outputs
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/util/ModCompatibility.java
  src/main/java/gregtech/client/ClientProxy.java
  src/main/java/gregtech/client/renderer/handler/CCLBlockRenderer.java
  src/main/java/gregtech/client/renderer/handler/FacadeRenderer.java
  src/main/java/gregtech/client/renderer/handler/MetaTileEntityRenderer.java
  src/main/java/gregtech/client/renderer/pipe/PipeRenderer.java
  src/main/java/gregtech/client/utils/ItemRenderCompat.java
Labels: type: bug

#2359 Fix Player Unable to Climb Frames on Certain Pipes
  src/main/java/gregtech/common/pipelike/cable/BlockCable.java
  src/main/java/gregtech/common/pipelike/fluidpipe/BlockFluidPipe.java
Labels: type: bug

#2360 Fix recipe properties offsetting info text too much
  src/main/java/gregtech/api/recipes/recipeproperties/CleanroomProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/PrimitiveProperty.java
Labels: type: bug

#2364 Fix central monitor jei page
  src/main/java/gregtech/client/utils/RenderUtil.java
Labels: type: bug

#2361 Fix unlocalized name of GT fluids in drums
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityDrum.java
Labels: type: bug

#2356 Add OpenComputers functions for maintenance problems
  src/main/java/gregtech/integration/opencomputers/drivers/DriverRecipeMapMultiblockController.java
  src/main/java/gregtech/integration/opencomputers/drivers/specific/DriverPowerSubstation.java
Labels: type: feature

#2314 Add Powderbarrel and ITNT
  src/main/java/gregtech/client/renderer/handler/GTExplosiveRenderer.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/EventHandlers.java
  src/main/java/gregtech/common/MetaEntities.java
  src/main/java/gregtech/common/blocks/MetaBlocks.java
  src/main/java/gregtech/common/blocks/explosive/BlockGTExplosive.java
  src/main/java/gregtech/common/blocks/explosive/BlockITNT.java
  src/main/java/gregtech/common/blocks/explosive/BlockPowderbarrel.java
  src/main/java/gregtech/common/blocks/material/GTBlockMaterials.java
  src/main/java/gregtech/common/entities/EntityGTExplosive.java
  src/main/java/gregtech/common/entities/ITNTEntity.java
  src/main/java/gregtech/common/entities/PowderbarrelEntity.java
  src/main/java/gregtech/common/items/behaviors/LighterBehaviour.java
  src/main/java/gregtech/integration/forestry/bees/GTBeeDefinition.java
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/ReactorRecipes.java
  src/main/java/gregtech/loaders/recipe/handlers/MaterialRecipeHandler.java
  src/main/resources/assets/gregtech/blockstates/itnt.json
  src/main/resources/assets/gregtech/blockstates/powderbarrel.json
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/misc/itnt.png
  src/main/resources/assets/gregtech/textures/blocks/misc/powderbarrel.png
  src/main/resources/gregtech_at.cfg
Labels: type: feature

#2362 Update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation
