Repository GregTechCEu/GregTech, pull requests merged in 2024-09, with the labels that each got.

#2540 Give MTEs a owner on placement
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/api/pattern/BlockPattern.java
  src/main/java/gregtech/common/items/behaviors/TricorderBehavior.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2611 Add OCing past MAX and fix multi Laser and Substation Hatch support
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/multiblock/FuelMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockDisplayText.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/integration/hwyla/provider/RecipeLogicDataProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/RecipeLogicInfoProvider.java
  src/test/java/gregtech/api/util/TierByVoltageTest.java
Labels: type: feature

#2614 unbind framebuffer object after use in renderFullImageInFBO
  src/main/java/gregtech/client/shader/Shaders.java
Labels: type: bug

#2587 Fix MTE Initial Sync sending the wrong data
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntityHolder.java
  src/main/java/gregtech/api/metatileentity/interfaces/IGregTechTileEntity.java
Labels: type: bug

#2613 Fix Issues with Filter Label and MTE Owner Overloads
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/common/covers/CoverFluidFilter.java
  src/main/java/gregtech/common/covers/CoverItemFilter.java
Labels: type: bug

#2621 Remove mui0 null returns
  src/main/java/gregtech/common/metatileentities/converter/MetaTileEntityConverter.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityDiode.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityHull.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMagicEnergyAbsorber.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityTransformer.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityWorldAccelerator.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityCokeOvenHatch.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveWaterPump.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityTankValve.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityAutoMaintenanceHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityComputationHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityEnergyHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityLaserHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityOpticalDataHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/hpca/MetaTileEntityHPCAComponent.java
  src/main/java/gregtech/common/metatileentities/primitive/MetaTileEntityCharcoalPileIgniter.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityDrum.java
  src/main/java/gregtech/common/pipelike/fluidpipe/longdistance/MetaTileEntityLDFluidEndpoint.java
  src/main/java/gregtech/common/pipelike/itempipe/longdistance/MetaTileEntityLDItemEndpoint.java
Labels: type: refactor

#2602 Update ru_ru.lang and Initial Ukranian langluage
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/uk_UA.lang
Labels: type: translation

#2593 Update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#2616 Add a config option for the magnet's attraction delay
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/items/behaviors/ItemMagnetBehavior.java
Labels: type: feature

#2585 Attempt to fix tools from addon materials
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
Labels: type: bug

#2618 Port the GT5u ME hatch wirecutter behavior
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityAEHostablePart.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEOutputBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEOutputHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingHatch.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2607 clean up recipe property storage
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/block/IHeatingCoilBlockStats.java
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/ComputationRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/FuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/HeatingCoilRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/PrimitiveRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/RecipeLogicEnergy.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/AssemblyLineRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/BlastRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/ComputationRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/FusionRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/ImplosionRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/PrimitiveRecipeBuilder.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapAssemblyLine.java
  src/main/java/gregtech/api/recipes/properties/RecipeProperty.java
  src/main/java/gregtech/api/recipes/properties/RecipePropertyRegistry.java
  src/main/java/gregtech/api/recipes/properties/RecipePropertyStorage.java
  src/main/java/gregtech/api/recipes/properties/RecipePropertyStorageImpl.java
  src/main/java/gregtech/api/recipes/properties/impl/CleanroomProperty.java
  src/main/java/gregtech/api/recipes/properties/impl/ComputationProperty.java
  src/main/java/gregtech/api/recipes/properties/impl/DimensionProperty.java
  src/main/java/gregtech/api/recipes/properties/impl/FusionEUToStartProperty.java
  src/main/java/gregtech/api/recipes/properties/impl/ImplosionExplosiveProperty.java
  src/main/java/gregtech/api/recipes/properties/impl/PrimitiveProperty.java
  src/main/java/gregtech/api/recipes/properties/impl/ResearchProperty.java
  src/main/java/gregtech/api/recipes/properties/impl/ResearchPropertyData.java
  src/main/java/gregtech/api/recipes/properties/impl/ScanProperty.java
  src/main/java/gregtech/api/recipes/properties/impl/TemperatureProperty.java
  src/main/java/gregtech/api/recipes/properties/impl/TotalComputationProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/DefaultProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/EmptyRecipePropertyStorage.java
  src/main/java/gregtech/api/recipes/recipeproperties/IRecipePropertyStorage.java
  src/main/java/gregtech/api/recipes/recipeproperties/RecipePropertyStorage.java
  src/main/java/gregtech/api/recipes/ui/RecipeMapUI.java
  src/main/java/gregtech/api/util/AssemblyLineManager.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityAssemblyLine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCrackingUnit.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityElectricBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiSmelter.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPyrolyseOven.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/integration/crafttweaker/recipe/CTRecipe.java
  src/main/java/gregtech/integration/crafttweaker/recipe/CTRecipeBuilder.java
  src/main/java/gregtech/integration/groovy/GroovyExpansions.java
  src/main/java/gregtech/integration/jei/basic/MaterialTreeCategory.java
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/java/gregtech/integration/jei/recipe/RecipeMapCategory.java
  src/main/java/gregtech/loaders/recipe/handlers/MaterialRecipeHandler.java
  src/test/java/gregtech/api/recipes/recipeproperties/RecipePropertyStorageTest.java
Labels: type: refactor

#2625 fix recipes having null cleanrooms
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
Labels: ignore changelog

#2617 tierByVoltage optimizations
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/util/GTUtility.java
Labels: type: feature

#2615 move MAX+ tiers into VOCN and VOCNF arrays
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockDisplayText.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeEnergy.java
  src/main/java/gregtech/integration/hwyla/provider/RecipeLogicDataProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/RecipeLogicInfoProvider.java
Labels: ignore changelog

#2626 fix tierByVoltage MAX tier off by one
  src/main/java/gregtech/api/util/GTUtility.java
Labels: ignore changelog

#2623 Fix hover texture not being applied to button theme
  src/main/java/gregtech/api/mui/GTGuiTheme.java
Labels: type: bug

#2627 Update PropertyContainer.java
  src/main/java/gregtech/integration/groovy/PropertyContainer.java
Labels: type: bug
