Repository GregTechCEu/GregTech, pull requests merged in 2024-10, with the labels that each got.

#2597 Comma-tize the TOP/WAILA/HWYLA energy container display
  src/main/java/gregtech/integration/hwyla/provider/ElectricContainerDataProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/ElectricContainerInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/lang/ja_jp.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: feature

#2595 Display the maximum input and output rates, and average I/O in ATs.
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityActiveTransformer.java
  src/main/java/gregtech/integration/hwyla/HWYLAModule.java
  src/main/java/gregtech/integration/hwyla/provider/ActiveTransformerDataProvider.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeModule.java
  src/main/java/gregtech/integration/theoneprobe/provider/ActiveTransformerInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2596 Add the power I/O of battery buffers to TOP/WAILA/HWYLA
  src/main/java/gregtech/integration/hwyla/HWYLAModule.java
  src/main/java/gregtech/integration/hwyla/provider/BatteryBufferDataProvider.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeModule.java
  src/main/java/gregtech/integration/theoneprobe/provider/BatteryBufferInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2631 Add `writeCustomData()` overload
  src/main/java/gregtech/api/metatileentity/interfaces/ISyncedTileEntity.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
Labels: type: refactor

#2636 Fix and Improve Steam Boiler
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java
  src/main/java/gregtech/integration/theoneprobe/provider/SteamBoilerInfoProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: refactor

#2637 Add Missing Annotations
  src/main/java/gregtech/common/metatileentities/steam/SteamMiner.java
  src/main/java/gregtech/common/pipelike/itempipe/BlockItemPipe.java
  src/main/java/gregtech/common/pipelike/laser/BlockLaserPipe.java
  src/main/java/gregtech/common/pipelike/optical/BlockOpticalPipe.java
Labels: type: bug

#2638 More Tweaker Information in JEI Recipe Display
  src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature, integration: GrS

#2619 Fix Cover Transfers Between Non-Tickable and Tickable Pipes
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
Labels: type: bug

#1963 Implement Quantum Storage Controller Network
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/capability/IDualHandler.java
  src/main/java/gregtech/api/capability/IQuantumController.java
  src/main/java/gregtech/api/capability/IQuantumStorage.java
  src/main/java/gregtech/api/gui/widgets/ClickButtonWidget.java
  src/main/java/gregtech/client/renderer/handler/BlockPosHighlightRenderer.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/client/renderer/texture/custom/QuantumStorageRenderer.java
  src/main/java/gregtech/common/items/behaviors/TricorderBehavior.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityEnergyHatch.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeEnergy.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeTank.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumExtender.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumProxy.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumStorage.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumStorageController.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeModule.java
  src/main/java/gregtech/integration/theoneprobe/provider/QuantumStorageProvider.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/controller_active.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/controller_active.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/controller_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/controller_active_emissive.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/controller_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/controller_front_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/controller_front_active_emissive.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/controller_front_inactive.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/controller_inactive.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/extender.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/extender_active.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/extender_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/extender_active_emissive.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/proxy_active.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/proxy_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/proxy_active_emissive.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/proxy_inactive.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/quantum_casing.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/quantum_indicator_connected.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/quantum_indicator_connected_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/quantum_indicator_disconnected.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/quantum_indicator_powered.png
  src/main/resources/assets/gregtech/textures/blocks/casings/quantum/quantum_indicator_powered_emissive.png
Labels: type: feature
