Repository GregTechCEu/GregTech, pull requests merged in 2024-03, with the labels that each got.

#2396 fix quantum tank not always fully reading custom data
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
Labels: type: bug

#2401 Fix NPE from facing being null when drawing grid overlays
  src/main/java/gregtech/common/ToolEventHandlers.java
Labels: type: bug

#2402 Drain Tricorder energy only when in survival
  src/main/java/gregtech/common/items/behaviors/TricorderBehavior.java
Labels: type: bug

#2367 Advanced Stocking Input Bus + Advanced Stocking Input Hatch
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/gui/GuiTextures.java
  src/main/java/gregtech/api/metatileentity/multiblock/IMultiblockPart.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/client/renderer/texture/Textures.java
  src/main/java/gregtech/common/gui/widget/appeng/AEConfigWidget.java
  src/main/java/gregtech/common/gui/widget/appeng/AEFluidConfigWidget.java
  src/main/java/gregtech/common/gui/widget/appeng/AEItemConfigWidget.java
  src/main/java/gregtech/common/gui/widget/appeng/slot/AEConfigSlot.java
  src/main/java/gregtech/common/gui/widget/appeng/slot/AEFluidConfigSlot.java
  src/main/java/gregtech/common/gui/widget/appeng/slot/AEItemConfigSlot.java
  src/main/java/gregtech/common/gui/widget/appeng/slot/AmountSetSlot.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/IConfigurableSlot.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityAEHostablePart.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEOutputBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEOutputHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/slot/ExportOnlyAEFluidList.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/slot/ExportOnlyAEFluidSlot.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/slot/ExportOnlyAEItemList.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/slot/ExportOnlyAEItemSlot.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/slot/ExportOnlyAESlot.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/slot/IConfigurableSlot.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/stack/WrappedItemStack.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/blocks/overlay/appeng/me_input_bus.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/appeng/me_input_bus_active.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/appeng/me_input_hatch.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/appeng/me_input_hatch_active.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/appeng/me_output_bus.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/appeng/me_output_bus_active.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/appeng/me_output_hatch.png
  src/main/resources/assets/gregtech/textures/blocks/overlay/appeng/me_output_hatch_active.png
  src/main/resources/assets/gregtech/textures/gui/base/slot_dark.png
  src/main/resources/assets/gregtech/textures/gui/widget/arrow_double.png
  src/main/resources/assets/gregtech/textures/gui/widget/button_me_auto_pull.png
Labels: type: feature

#2404 Electric Wirecutter
  src/main/java/gregtech/common/items/ToolItems.java
  src/main/java/gregtech/loaders/recipe/handlers/ToolRecipeHandler.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/material_sets/dull/tool_head_wirecutter.json
  src/main/resources/assets/gregtech/models/item/tools/wire_cutter_hv.json
  src/main/resources/assets/gregtech/models/item/tools/wire_cutter_iv.json
  src/main/resources/assets/gregtech/models/item/tools/wire_cutter_lv.json
  src/main/resources/assets/gregtech/textures/items/tools/handle_electric_wire_cutter_hv.png
  src/main/resources/assets/gregtech/textures/items/tools/handle_electric_wire_cutter_iv.png
  src/main/resources/assets/gregtech/textures/items/tools/handle_electric_wire_cutter_lv.png
  src/main/resources/assets/gregtech/textures/items/tools/wire_cutter_electric.png
Labels: type: feature

#2405 Allow PSS to display on CM
  src/main/java/gregtech/common/covers/CoverDigitalInterface.java
  src/main/java/gregtech/common/metatileentities/multi/electric/centralmonitor/MetaTileEntityMonitorScreen.java
Labels: type: bug

#2411 Fix server crashes with alarms
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityAlarm.java
Labels: type: bug

#2415 fix pipe capability retrieval logic
  src/main/java/gregtech/api/pipenet/tile/TileEntityPipeBase.java
Labels: type: bug

#2416 fix solar panels not outputting to cables
  src/main/java/gregtech/common/covers/CoverSolarPanel.java
Labels: type: bug

#2389 Update GroovyScript & improve material API for groovy
  dependencies.gradle
  src/main/java/gregtech/api/unification/material/properties/BlastProperty.java
  src/main/java/gregtech/integration/crafttweaker/material/CTMaterialHelpers.java
  src/main/java/gregtech/integration/groovy/GroovyExpansions.java
  src/main/java/gregtech/integration/groovy/GroovyMaterialBuilderExpansion.java
  src/main/java/gregtech/integration/groovy/GroovyRecipeBuilderExpansion.java
  src/main/java/gregtech/integration/groovy/GroovyScriptModule.java
Labels: type: feature, integration: GrS

#2423 allow SMD diodes in low tier diode block recipes
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
Labels: type: feature

#2424 check for a valid MTE before rendering
  src/main/java/gregtech/client/renderer/handler/MetaTileEntityRenderer.java
Labels: type: bug

#2427 Fix link to GT IMPACT in readme
  README.md
Labels: ignore changelog

#2417 Fix fluid drilling rig display units
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
Labels: type: bug

#2413 Update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#2414 Generify DimensionProperty
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/builders/GasCollectorRecipeBuilder.java
  src/main/java/gregtech/api/recipes/recipeproperties/DimensionProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/GasCollectorDimensionProperty.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityGasCollector.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: refactor

#2419 Allow Data Stick to copy-paste ME bus settings
  src/main/java/gregtech/api/capability/IDataStickIntractable.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingHatch.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2426 Fix LCE/ECE from parallelizing too much
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
Labels: type: bug

#2278 allow multiple build actions per recipemap
  src/main/java/gregtech/api/recipes/RecipeBuildAction.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/RecipeMapBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
Labels: type: feature

#2431 add ItemStack inputNBT method
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
Labels: type: feature

#2434 Reduce allocations in RecipeBuilder
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
Labels: type: feature
