Repository GregTechCEu/GregTech, pull requests merged in 2024-08, with the labels that each got.

#2546 Fix Spray Can offhand tooltip applying to Solvent
  src/main/java/gregtech/common/items/behaviors/ColorSprayBehaviour.java
Labels: type: bug

#2560 Add addElement() to material event class
  src/main/java/gregtech/integration/groovy/GroovyScriptModule.java
Labels: type: bug, integration: GrS

#2558 Fix Output Bus not Notifying in Certain Conditions
  src/main/java/gregtech/api/items/itemhandlers/GTItemStackHandler.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
Labels: type: bug

#2555 Override getItem in BlockMachine.class
  src/main/java/gregtech/api/block/machines/BlockMachine.java
Labels: type: feature

#2561 Improve material element api
  src/main/java/gregtech/api/unification/Element.java
  src/main/java/gregtech/api/unification/Elements.java
  src/main/java/gregtech/integration/groovy/GroovyExpansions.java
  src/test/java/gregtech/api/unification/ElementsTest.java
Labels: type: refactor

#2562 fission: natural uranium and plutonium
  src/main/java/gregtech/api/items/materialitem/MetaPrefixItem.java
  src/main/java/gregtech/api/unification/Element.java
  src/main/java/gregtech/api/unification/Elements.java
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/MaterialFlagAddition.java
  src/main/java/gregtech/integration/forestry/ForestryModule.java
  src/main/java/gregtech/integration/forestry/bees/GTBeeDefinition.java
  src/main/java/gregtech/integration/forestry/recipes/CombRecipes.java
  src/main/java/gregtech/loaders/recipe/FusionLoader.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/MixerRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/NuclearRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/SeparationRecipes.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/lang/ja_jp.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: feature

#2552 Update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#2566 Fix PA & Cleanroom Sync Issues
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
Labels: type: bug

#2577 Fix the no distinct buses button
  src/main/resources/assets/gregtech/textures/gui/widget/button_no_distinct_buses.png
Labels: type: feature

#2563 fission: hafnium and zirconium
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/MaterialFlagAddition.java
  src/main/java/gregtech/loaders/recipe/chemistry/MixerRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/NuclearRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/TitaniumRecipes.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/worldgen/vein/end/naquadah_vein.json
Labels: type: feature

#2581 remove usages of NonNullList
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/miner/MinerLogic.java
  src/main/java/gregtech/api/cover/CoverBase.java
  src/main/java/gregtech/api/gui/impl/FakeModularGuiContainer.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SimpleMachineMetaTileEntity.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/unification/OreDictUnifier.java
  src/main/java/gregtech/api/util/BlockUtility.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/gui/impl/FakeModularUIContainerClipboard.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityFisher.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityMiner.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityObjectHolder.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityPassthroughHatchItem.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityRotorHolder.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityAEHostablePart.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/hpca/MetaTileEntityHPCAComponent.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java
  src/main/java/gregtech/common/metatileentities/storage/CraftingRecipeLogic.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityBuffer.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCrate.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
Labels: type: refactor

#2579 Add Missing Side Only Annotations
  src/main/java/gregtech/api/recipes/recipeproperties/CleanroomProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/ComputationProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/DefaultProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/DimensionProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/FusionEUToStartProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/ImplosionExplosiveProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/PrimitiveProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/ResearchProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/ScanProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/TemperatureProperty.java
  src/main/java/gregtech/api/recipes/recipeproperties/TotalComputationProperty.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
  src/main/java/gregtech/common/metatileentities/converter/MetaTileEntityConverter.java
  src/main/java/gregtech/common/metatileentities/multi/electric/centralmonitor/MetaTileEntityMonitorScreen.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiblockPart.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityBuffer.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeEnergy.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumTank.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
  src/main/java/gregtech/common/pipelike/fluidpipe/longdistance/MetaTileEntityLDFluidEndpoint.java
  src/main/java/gregtech/common/pipelike/itempipe/longdistance/MetaTileEntityLDItemEndpoint.java
Labels: ignore changelog

#2570 Fix Legacy Filter NBT Reading
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverFluidFilter.java
  src/main/java/gregtech/common/covers/CoverItemFilter.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/covers/filter/BaseFilterContainer.java
  src/main/java/gregtech/common/covers/filter/readers/SimpleItemFilterReader.java
Labels: type: bug

#2532 Update build script version to 1723428048
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: ignore changelog

#2576 Fission Reactor's ShapeInfo support for Relative Directions
  src/main/java/gregtech/api/pattern/BlockPattern.java
  src/main/java/gregtech/api/pattern/FactoryBlockPattern.java
  src/main/java/gregtech/api/pattern/MultiblockShapeInfo.java
  src/main/java/gregtech/api/util/RelativeDirection.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityElectricBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityHPCA.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeChemicalReactor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityResearchStation.java
Labels: type: refactor

#2589 Fix incorrect pipe material
  src/main/java/gregtech/loaders/recipe/CraftingComponent.java
Labels: type: bug

#2584 fix duplicate assembly line research entries
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapAssemblyLine.java
  src/main/java/gregtech/common/items/behaviors/DataItemBehavior.java
Labels: type: bug
