Repository GregTechCEu/GregTech, pull requests merged in 2024-05, with the labels that each got.

#2467 Remove NuclearCraft ASM
  src/main/java/gregtech/asm/GregTechTransformer.java
  src/main/java/gregtech/asm/visitors/NuclearCraftRecipeHelperVisitor.java
Labels: ignore changelog

#2445 Update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#2469 Allow polarizing block -> magnetic block
  src/main/java/gregtech/loaders/recipe/handlers/PolarizingRecipeHandler.java
Labels: type: feature

#2470 Fusion bloom fix & other bloom effect API modifications
  src/main/java/gregtech/client/event/ClientEventHandler.java
  src/main/java/gregtech/client/particle/GTOverheatParticle.java
  src/main/java/gregtech/client/utils/BloomEffectUtil.java
  src/main/java/gregtech/client/utils/EffectRenderContext.java
  src/main/java/gregtech/client/utils/IBloomEffect.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
Labels: type: bug

#2463 Inital Vintagium Support
  .gitignore
  dependencies.gradle
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/util/Mods.java
  src/main/java/gregtech/asm/GregTechTransformer.java
  src/main/java/gregtech/asm/visitors/VintagiumManagerVistor.java
  src/main/java/gregtech/asm/visitors/VintagiumPassManagerVisitor.java
  src/main/java/gregtech/client/utils/BloomEffectVintagiumUtil.java
Labels: type: feature

#2456 Fix Ore Dict Ingredients When Changing OreDicts with CT & GS
  src/main/java/gregtech/api/recipes/ingredients/GTRecipeOreInput.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/integration/groovy/GroovyScriptModule.java
  src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java
Labels: type: bug
