Repository GregTechCEu/GregTech, pull requests merged in 2025-06, with the labels that each got.

#2826 Fix CCL NPE caused from an improper texture loading order
  src/main/java/gregtech/client/ClientProxy.java
Labels: type: bug

#2820 Make all material property setters return themselves to allow method chaining
  src/main/java/gregtech/api/capability/IPropertyFluidFilter.java
  src/main/java/gregtech/api/capability/impl/PropertyFluidFilter.java
  src/main/java/gregtech/api/unification/material/properties/BlastProperty.java
  src/main/java/gregtech/api/unification/material/properties/DustProperty.java
  src/main/java/gregtech/api/unification/material/properties/ExtraToolProperty.java
  src/main/java/gregtech/api/unification/material/properties/FluidPipeProperties.java
  src/main/java/gregtech/api/unification/material/properties/FluidProperty.java
  src/main/java/gregtech/api/unification/material/properties/IngotProperty.java
  src/main/java/gregtech/api/unification/material/properties/ItemPipeProperties.java
  src/main/java/gregtech/api/unification/material/properties/OreProperty.java
  src/main/java/gregtech/api/unification/material/properties/RotorProperty.java
  src/main/java/gregtech/api/unification/material/properties/ToolProperty.java
  src/main/java/gregtech/api/unification/material/properties/WireProperties.java
Labels: type: refactor

#2807 Translated using Weblate (Russian) for 1.12.2
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/uk_ua.lang
Labels: type: translation

#2827 Fix inverted condition in OC check
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
Labels: ignore changelog

#2823 Fix Packet Data Memory Leak
  src/main/java/gregtech/api/metatileentity/SyncedTileEntityBase.java
  src/main/java/gregtech/api/network/PacketDataList.java
Labels: type: bug

#2838 Fix Alfheim lighting engine ram usage workaround with Alfheim 1.6
  src/api/java/dev/redstudio/alfheim/lighting/LightingEngine.java
  src/main/java/gregtech/api/util/world/DummyWorld.java
Labels: type: bug
