Repository GregTechCEu/GregTech, pull requests merged in 2025-03, with the labels that each got.

#2746 fix banded_iron translate in ru_ru
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: type: translation

#2747 switch to XoShiRo256++ random
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/util/XSTR.java
  src/main/java/gregtech/api/util/random/SplitMix64Random.java
  src/main/java/gregtech/api/util/random/Util.java
  src/main/java/gregtech/api/util/random/XoRoShiRo128PlusRandom.java
  src/main/java/gregtech/api/util/random/XoShiRo256PlusPlusRandom.java
  src/main/java/gregtech/api/util/random/package-info.java
  src/main/java/gregtech/api/worldgen/bedrockFluids/BedrockFluidVeinHandler.java
  src/main/java/gregtech/api/worldgen/generator/CachedGridEntry.java
Labels: type: refactor

#2741 remove 2.9 deprecated code
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/block/IWalkingSpeedBonus.java
  src/main/java/gregtech/api/block/VariantBlock.java
  src/main/java/gregtech/api/gui/widgets/TankWidget.java
  src/main/java/gregtech/api/metatileentity/MTETrait.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SteamMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/material/properties/FluidProperty.java
  src/main/java/gregtech/api/util/AssemblyLineManager.java
  src/main/java/gregtech/api/util/interpolate/Eases.java
  src/main/java/gregtech/api/util/oreglob/OreGlob.java
  src/main/java/gregtech/client/shader/Shaders.java
  src/main/java/gregtech/client/utils/BloomEffectUtil.java
  src/main/java/gregtech/common/EventHandlers.java
  src/main/java/gregtech/common/covers/CoverBehaviors.java
  src/main/java/gregtech/common/covers/CoverCraftingTable.java
  src/main/java/gregtech/common/covers/CoverStorage.java
  src/main/java/gregtech/common/covers/filter/OreDictionaryItemFilter.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/OreGlobMessages.java
  src/main/java/gregtech/common/covers/filter/oreglob/impl/OreGlobParser.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
  src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java
  src/main/java/gregtech/integration/IntegrationUtil.java
Labels: ignore changelog

#2745 cleanup keybind code
  src/main/java/gregtech/api/util/input/KeyBind.java
  src/main/java/gregtech/client/ClientProxy.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/core/network/packets/PacketKeysPressed.java
Labels: type: refactor

#2744 fix deprecation warnings in tests
  src/test/java/gregtech/api/capability/impl/AbstractRecipeLogicTest.java
  src/test/java/gregtech/api/capability/impl/MultiblockRecipeLogicTest.java
  src/test/java/gregtech/api/recipes/RecipeMapTest.java
  src/test/java/gregtech/api/recipes/logic/IParallelableRecipeLogicTest.java
  src/test/java/gregtech/api/recipes/logic/ParallelLogicTest.java
Labels: ignore changelog

#2726 Place ore prospector waypoints at vein height
  src/main/java/gregtech/common/gui/widget/prospector/widget/WidgetProspectingMap.java
Labels: type: feature

#2749 Update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#2750 Miscellaneous fixes
  src/main/java/gregtech/api/items/OreDictNames.java
  src/main/java/gregtech/api/recipes/builders/UniversalDistillationRecipeBuilder.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEStockingHatch.java
  src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
Labels: type: bug

#2420 Rework Multiblock Abilities
  src/main/java/gregtech/api/capability/DualHandler.java
  src/main/java/gregtech/api/capability/IDualHandler.java
  src/main/java/gregtech/api/capability/IMultipleTankHandler.java
  src/main/java/gregtech/api/capability/INotifiableHandler.java
  src/main/java/gregtech/api/capability/IQuantumController.java
  src/main/java/gregtech/api/capability/impl/DistillationTowerLogicHandler.java
  src/main/java/gregtech/api/capability/impl/FluidTankList.java
  src/main/java/gregtech/api/capability/impl/ItemHandlerList.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/multiblock/AbilityInstances.java
  src/main/java/gregtech/api/metatileentity/multiblock/IMultiblockAbilityPart.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockAbility.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/api/recipes/Recipe.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/api/util/OverlayedFluidHandler.java
  src/main/java/gregtech/common/items/behaviors/TricorderBehavior.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityDiode.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityHull.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityRockBreaker.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPumpHatch.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityTankValve.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityAutoMaintenanceHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityComputationHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityDataAccessHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityEnergyHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityFluidHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityLaserHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMachineHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiFluidHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiblockNotifiablePart.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityObjectHolder.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityOpticalDataHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityPassthroughHatchFluid.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityPassthroughHatchItem.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityReservoirHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityRotorHolder.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEInputHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEOutputBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityMEOutputHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/hpca/MetaTileEntityHPCAComponent.java
  src/main/java/gregtech/common/metatileentities/steam/multiblockpart/MetaTileEntitySteamHatch.java
  src/main/java/gregtech/common/metatileentities/steam/multiblockpart/MetaTileEntitySteamItemBus.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumExtender.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumProxy.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumStorageController.java
  src/test/java/gregtech/api/capability/impl/FluidTankListTest.java
Labels: type: refactor
