Repository GregTechCEu/GregTech, pull requests merged in 2025-09, with the labels that each got.

#2853 Allow giving mtes custom soundtypes
  src/main/java/gregtech/api/block/IStateSoundType.java
  src/main/java/gregtech/api/block/VariantBlock.java
  src/main/java/gregtech/api/block/machines/BlockMachine.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/common/blocks/BlockMetalCasing.java
  src/main/java/gregtech/common/blocks/BlockSteamCasing.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityCokeOven.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityCokeOvenHatch.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityMultiblockTank.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPrimitiveWaterPump.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPumpHatch.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityTankValve.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCrate.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityDrum.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
Labels: type: feature

#2863 Fix an empty tooltip on GT fluid slots that have no fluid
  src/main/java/gregtech/api/mui/sync/GTFluidSyncHandler.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityFluidHatch.java
  src/main/java/gregtech/common/mui/widget/GTFluidSlot.java
Labels: type: bug, type: refactor

#2778 Block breaker improvements
  dependencies.gradle
  src/main/java/gregtech/api/util/GregFakePlayer.java
  src/main/java/gregtech/api/util/Mods.java
  src/main/java/gregtech/api/util/function/TriPredicate.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityBlockBreaker.java
  src/main/java/gregtech/integration/ftb/utility/FTBChunksHelper.java
Labels: type: bug, type: feature
