Repository GregTechCEu/GregTech, pull requests merged in 2025-01, with the labels that each got.

#2691 Remove fluid input text from Distillation Towers GUIs since it's been broken for six years.
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityDistillationTower.java
Labels: type: bug

#2653 Update lang files for ru_ru and uk_ua
  src/main/resources/assets/gregtech/lang/ru_ru.lang
  src/main/resources/assets/gregtech/lang/uk_ua.lang
Labels: type: translation

#2679 Allow diode blocks to be toggled
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityDiode.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2620 Add terrain resist tooltips to multiblocks
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/TieredMetaTileEntity.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityBlockBreaker.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityFisher.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityPump.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityLongDistanceEndpoint.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2622 Update MUI2 dep to RC2
  dependencies.gradle
  src/main/java/gregtech/api/cover/CoverWithUI.java
  src/main/java/gregtech/api/mui/GTGuiTextures.java
  src/main/java/gregtech/api/mui/GTGuiTheme.java
  src/main/java/gregtech/api/mui/GTGuis.java
  src/main/java/gregtech/api/mui/StateOverlay.java
  src/main/java/gregtech/api/mui/UnboxFix.java
  src/main/java/gregtech/api/mui/sync/FixedFluidSlotSH.java
  src/main/java/gregtech/api/mui/sync/GTFluidSyncHandler.java
  src/main/java/gregtech/api/mui/widget/GhostCircuitSlotWidget.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverFluidFilter.java
  src/main/java/gregtech/common/covers/CoverFluidRegulator.java
  src/main/java/gregtech/common/covers/CoverFluidVoiding.java
  src/main/java/gregtech/common/covers/CoverFluidVoidingAdvanced.java
  src/main/java/gregtech/common/covers/CoverItemFilter.java
  src/main/java/gregtech/common/covers/CoverItemVoiding.java
  src/main/java/gregtech/common/covers/CoverItemVoidingAdvanced.java
  src/main/java/gregtech/common/covers/CoverMachineController.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/covers/CoverRoboticArm.java
  src/main/java/gregtech/common/covers/ender/CoverAbstractEnderLink.java
  src/main/java/gregtech/common/covers/ender/CoverEnderFluidLink.java
  src/main/java/gregtech/common/covers/filter/BaseFilter.java
  src/main/java/gregtech/common/covers/filter/BaseFilterContainer.java
  src/main/java/gregtech/common/covers/filter/OreDictionaryItemFilter.java
  src/main/java/gregtech/common/covers/filter/SimpleFluidFilter.java
  src/main/java/gregtech/common/covers/filter/SimpleItemFilter.java
  src/main/java/gregtech/common/covers/filter/SmartItemFilter.java
  src/main/java/gregtech/common/items/behaviors/IntCircuitBehaviour.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityFluidHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiFluidHatch.java
  src/main/java/gregtech/common/mui/widget/GTFluidSlot.java
  src/main/java/gregtech/common/mui/widget/HighlightedTextField.java
  src/main/java/gregtech/common/mui/widget/InteractableText.java
  src/main/java/gregtech/common/mui/widget/orefilter/OreFilterTestSlot.java
  src/main/java/gregtech/mixins/GregTechLateMixinLoadingPlugin.java
  src/main/java/gregtech/mixins/jei/IngredientGridMixin.java
  src/main/java/gregtech/mixins/mui2/ClientEventHandlerMixin.java
  src/main/java/gregtech/mixins/mui2/ItemSlotSHMixin.java
  src/main/java/gregtech/mixins/mui2/PanelSyncHandlerMixin.java
  src/main/java/gregtech/mixins/mui2/PanelSyncManagerMixin.java
  src/main/java/gregtech/mixins/mui2/StyledTextMixin.java
  src/main/java/gregtech/mixins/mui2/TextWidgetMixin.java
  src/main/java/gregtech/mixins/mui2/ToggleButtonMixin.java
  src/main/java/gregtech/mixins/mui2/TooltipMixin.java
  src/main/resources/mixins.gregtech.jei.json
  src/main/resources/mixins.gregtech.mui2.json
Labels: type: refactor

#2675 Add an easier way for MTEs to be added to creative tabs
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
Labels: type: refactor

#2695 fix voltage translation in ru-ru.lang
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: type: translation

#2696 Fix Ghost Circuit Scrolling Twice
  src/main/java/gregtech/api/mui/widget/GhostCircuitSlotWidget.java
Labels: type: bug

#2685 Fix creative tanks only outputting up to 1kL at a time
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeTank.java
Labels: type: bug

#2504 Port passthrough hatches to MUI2 and allow them to be togged
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityPassthroughHatchFluid.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityPassthroughHatchItem.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2680 Extra tooltips for machines
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityBatteryBuffer.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMachineHatch.java
Labels: type: feature

#2697 Fix superconductor trainslation in ru_ru
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: type: translation

#2698 Improve Logging for Unread Packet Data
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/cover/CoverSaveHandler.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SyncedTileEntityBase.java
  src/main/java/gregtech/api/metatileentity/interfaces/ISyncedTileEntity.java
  src/main/java/gregtech/common/covers/ender/CoverAbstractEnderLink.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityFluidHatch.java
Labels: type: refactor

#2659 fix colored steel recipes
  src/main/java/gregtech/api/unification/material/materials/HigherDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/loaders/recipe/BatteryRecipes.java
  src/main/java/gregtech/loaders/recipe/CraftingComponent.java
  src/main/java/gregtech/loaders/recipe/chemistry/ChemicalBathRecipes.java
  src/main/java/gregtech/loaders/recipe/chemistry/MixerRecipes.java
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.ev.vanadium/1.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.ev.vanadium/2.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.ev.vanadium/3.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.ev.vanadium/4.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.ev.vanadium/5.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.ev.vanadium/6.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.ev.vanadium/7.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.ev.vanadium/8.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.hull.ev.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.hull.luv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.luv.vanadium/1.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.luv.vanadium/2.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.luv.vanadium/3.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.luv.vanadium/4.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.luv.vanadium/5.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.luv.vanadium/6.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.luv.vanadium/7.png
  src/main/resources/assets/gregtech/textures/items/metaitems/battery.luv.vanadium/8.png
Labels: type: bug

#2493 Toolbelt
  src/main/java/gregtech/api/items/IDyeableItem.java
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/api/items/toolitem/ItemGTHoe.java
  src/main/java/gregtech/api/items/toolitem/ItemGTToolbelt.java
  src/main/java/gregtech/api/items/toolitem/ToolHelper.java
  src/main/java/gregtech/api/items/toolitem/aoe/AoESymmetrical.java
  src/main/java/gregtech/api/items/toolitem/behavior/IToolBehavior.java
  src/main/java/gregtech/api/mui/GTGuiTextures.java
  src/main/java/gregtech/asm/GregTechTransformer.java
  src/main/java/gregtech/client/ClientProxy.java
  src/main/java/gregtech/client/renderer/handler/ToolbeltRenderer.java
  src/main/java/gregtech/client/utils/ToolChargeBarRenderer.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/common/ToolEventHandlers.java
  src/main/java/gregtech/common/crafting/DyeableRecipes.java
  src/main/java/gregtech/common/crafting/GTShapedOreRecipe.java
  src/main/java/gregtech/common/crafting/GTShapelessOreRecipe.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/common/items/ToolItems.java
  src/main/java/gregtech/common/items/behaviors/ColorSprayBehaviour.java
  src/main/java/gregtech/common/items/tool/GrassPathBehavior.java
  src/main/java/gregtech/common/items/tool/HarvestCropsBehavior.java
  src/main/java/gregtech/common/items/tool/HoeGroundBehavior.java
  src/main/java/gregtech/common/items/tool/OpenGUIBehavior.java
  src/main/java/gregtech/common/items/tool/TorchPlaceBehavior.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java
  src/main/java/gregtech/core/CoreModule.java
  src/main/java/gregtech/core/network/packets/PacketToolbeltSelectionChange.java
  src/main/java/gregtech/core/sound/GTSoundEvents.java
  src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java
  src/main/java/gregtech/loaders/recipe/GTRecipeManager.java
  src/main/java/gregtech/loaders/recipe/handlers/ToolRecipeHandler.java
  src/main/java/gregtech/mixins/forge/GuiIngameForgeMixin.java
  src/main/java/gregtech/mixins/forge/OreIngredientMixin.java
  src/main/java/gregtech/mixins/jei/BasicRecipeTransferHandlerServerMixin.java
  src/main/java/gregtech/mixins/jei/StackHelperMixin.java
  src/main/java/gregtech/mixins/minecraft/ContainerMixin.java
  src/main/java/gregtech/mixins/minecraft/MinecraftMixin.java
  src/main/java/gregtech/mixins/minecraft/RecipeRepairItemMixin.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/tools/toolbelt.json
  src/main/resources/assets/gregtech/sounds.json
  src/main/resources/assets/gregtech/sounds/click.ogg
  src/main/resources/assets/gregtech/textures/items/tools/toolbelt_belt.png
  src/main/resources/assets/gregtech/textures/items/tools/toolbelt_loops.png
  src/main/resources/gregtech_at.cfg
  src/main/resources/mixins.gregtech.forge.json
  src/main/resources/mixins.gregtech.jei.json
  src/main/resources/mixins.gregtech.minecraft.json
Labels: type: feature

#2703 Fix Issues from Unread Packet Data
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/cover/CoverSaveHandler.java
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
Labels: type: bug, ignore changelog

#2624 Port many blocks to MUI2
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityBatteryBuffer.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityBlockBreaker.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityFisher.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityPumpHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMachineHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityObjectHolder.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityReservoirHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityRotorHolder.java
  src/main/java/gregtech/common/metatileentities/steam/multiblockpart/MetaTileEntitySteamHatch.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityBuffer.java
Labels: type: refactor

#2707 Show required energy in Quantum controller when out of power
  src/main/java/gregtech/integration/hwyla/HWYLAModule.java
  src/main/java/gregtech/integration/hwyla/provider/QuantumStorageProvider.java
  src/main/java/gregtech/integration/theoneprobe/provider/QuantumStorageProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature
