Repository GregTechCEu/GregTech, pull requests merged in 2025-05, with the labels that each got.

#2665 Add more fluid solidifier molds
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/common/items/MetaItems.java
  src/main/java/gregtech/loaders/recipe/CraftingRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/handlers/PartsRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/PipeRecipeHandler.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.baguette.json
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.bolt.json
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.bread.json
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.bun.json
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.pipe.huge.json
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.pipe.large.json
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.pipe.normal.json
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.pipe.small.json
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.pipe.tiny.json
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.ring.json
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.rod.json
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.rod_long.json
  src/main/resources/assets/gregtech/models/item/metaitems/shape.mold.round.json
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.baguette.png
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.bolt.png
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.bread.png
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.bun.png
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.pipe.huge.png
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.pipe.large.png
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.pipe.normal.png
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.pipe.small.png
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.pipe.tiny.png
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.ring.png
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.rod.png
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.rod_long.png
  src/main/resources/assets/gregtech/textures/items/metaitems/shape.mold.round.png
Labels: type: feature

#2783 Fix saving/loading of the machine owner UUID to NBT
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
Labels: type: bug

#2784 Add oredicts to cobble variants of stone types
  src/main/java/gregtech/loaders/OreDictionaryLoader.java
Labels: type: feature

#2782 Update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#2780 [Fix] Only register mte or pipe block/items when necessary
  src/main/java/gregtech/common/CommonProxy.java
Labels: type: bug

#2789 Fix Crafting Station Connected Inventory Desync
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
Labels: type: bug, ignore changelog

#2787 Add the network status of ME parts to TOP/WAILA/HWYLA
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/appeng/MetaTileEntityAEHostablePart.java
  src/main/java/gregtech/integration/hwyla/HWYLAModule.java
  src/main/java/gregtech/integration/hwyla/provider/AEMultiblockHatchProvider.java
  src/main/java/gregtech/integration/theoneprobe/TheOneProbeModule.java
  src/main/java/gregtech/integration/theoneprobe/provider/AEMultiblockHatchProvider.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2796 disable buildscript update checks in CI
  .github/workflows/format_java.yml
  .github/workflows/nuclear_test_release.yml
  .github/workflows/publish_project.yml
  .github/workflows/test_java.yml
  .github/workflows/update_gradle_cache.yml
Labels: ignore changelog

#2793 MTE ID Reallocation
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntityRegistration.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityTransformer.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityAutoMaintenanceHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityCleaningMaintenanceHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityEnergyHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityFluidHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiFluidHatch.java
  src/main/java/gregtech/datafix/GTDataFixers.java
  src/main/java/gregtech/datafix/GTDataVersion.java
  src/main/java/gregtech/datafix/impl/V2PostMTEReallocFixer.java
  src/main/java/gregtech/datafix/migration/lib/MTEDataMigrator.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2791 Display Throughput in energy hatch tooltips
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityEnergyHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityLaserHatch.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2799 Remove Muffler Inventory and Recovery Mechanics
  src/main/java/gregtech/api/capability/IMufflerHatch.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockWithDisplayBase.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2801 fix IV energy hatch recycling
  src/main/java/gregtech/loaders/MaterialInfoLoader.java
Labels: type: bug

#2800 Handle MC formatting codes in small digit conversion
  src/main/java/gregtech/api/util/SmallDigits.java
Labels: type: bug

#2779 Fix another recipe conflict
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
Labels: type: bug

#2771 Proper Reloading of OreDict Ing Cache on Servers
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/integration/groovy/GroovyScriptModule.java
Labels: type: bug

#2802 move recycling data generation up to base RecipeBuilder
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecipeMaps.java
  src/main/java/gregtech/api/recipes/builders/AssemblerRecipeBuilder.java
  src/main/java/gregtech/loaders/recipe/handlers/WireRecipeHandler.java
Labels: type: feature

#2798 Deprecate the Phosphate material
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/MaterialFlagAddition.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/integration/forestry/recipes/CombRecipes.java
  src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/chemistry/SeparationRecipes.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2781 Consistency
  src/main/java/gregtech/loaders/recipe/CircuitRecipes.java
Labels: type: bug

#2804 remove EBF pyrometallurgy and associated materials
  src/main/java/gregtech/api/unification/material/Materials.java
  src/main/java/gregtech/api/unification/material/materials/ElementMaterials.java
  src/main/java/gregtech/api/unification/material/materials/FirstDegreeMaterials.java
  src/main/java/gregtech/api/unification/material/materials/MaterialFlagAddition.java
  src/main/java/gregtech/api/unification/material/materials/SecondDegreeMaterials.java
  src/main/java/gregtech/loaders/recipe/MachineRecipeLoader.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2809 Move recycling code out of OreDictUnifier
  src/main/java/gregtech/api/GregTechAPI.java
  src/main/java/gregtech/api/items/metaitem/MetaItem.java
  src/main/java/gregtech/api/recipes/ModHandler.java
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/RecyclingHandler.java
  src/main/java/gregtech/api/unification/OreDictUnifier.java
  src/main/java/gregtech/api/unification/RecyclingManager.java
  src/main/java/gregtech/api/unification/stack/ItemMaterialInfo.java
  src/main/java/gregtech/api/unification/stack/RecyclingData.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/common/CommonProxy.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/java/gregtech/loaders/MaterialInfoLoader.java
  src/main/java/gregtech/loaders/OreDictionaryLoader.java
  src/main/java/gregtech/loaders/recipe/RecyclingRecipes.java
  src/main/java/gregtech/loaders/recipe/WoodRecipeLoader.java
Labels: type: refactor

#2797 Rearrange GT JEI categories
  src/main/java/gregtech/api/recipes/RecipeMap.java
  src/main/java/gregtech/api/recipes/RecipeMapBuilder.java
  src/main/java/gregtech/api/recipes/category/GTRecipeCategory.java
  src/main/java/gregtech/api/recipes/category/RecipeCategories.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapResearchStation.java
  src/main/java/gregtech/api/recipes/machines/RecipeMapScanner.java
  src/main/java/gregtech/common/ConfigHolder.java
  src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java
  src/main/java/gregtech/integration/jei/basic/BasicRecipeCategory.java
  src/main/java/gregtech/integration/jei/basic/GTFluidVeinCategory.java
  src/main/java/gregtech/integration/jei/basic/GTOreCategory.java
  src/main/java/gregtech/integration/jei/basic/MaterialTreeCategory.java
  src/main/java/gregtech/integration/jei/basic/OreByProductCategory.java
  src/main/java/gregtech/integration/jei/multiblock/MultiblockInfoCategory.java
  src/main/java/gregtech/integration/jei/recipe/IntCircuitCategory.java
  src/main/java/gregtech/mixins/jei/ModRegistryMixin.java
  src/main/resources/mixins.gregtech.jei.json
Labels: type: feature

#2753 improve power substation power bank code
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPowerSubstation.java
  src/test/java/gregtech/common/metatileentities/multiblock/PowerSubstationTest.java
Labels: type: refactor

#2785 Fix various grs hand command issue
  src/main/java/gregtech/integration/RecipeCompatUtil.java
  src/main/java/gregtech/integration/groovy/GrSRecipeHelper.java
  src/main/java/gregtech/integration/groovy/GroovyHandCommand.java
Labels: type: refactor

#2803 Add a tooltip to the LCR saying it can process normal CR recipes.
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeChemicalReactor.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2812 Fix JEI Highlight for Custom MUI2 Widgets
  src/main/java/gregtech/client/utils/RenderUtil.java
  src/main/java/gregtech/common/mui/widget/GTFluidSlot.java
  src/main/java/gregtech/common/mui/widget/workbench/CraftingInputSlot.java
Labels: type: bug
