Repository GregTechCEu/GregTech, pull requests merged in 2025-02, with the labels that each got.

#2708 Fix Power Substation JEI preview
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPowerSubstation.java
Labels: type: bug

#2706 Fix the cleanroom multiblock overriding the cleanroom provider set by cleaning hatches.
  src/main/java/gregtech/api/metatileentity/WorkableTieredMetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/multiblock/DummyCleanroom.java
  src/main/java/gregtech/api/metatileentity/multiblock/ICleanroomProvider.java
  src/main/java/gregtech/api/metatileentity/multiblock/ICleanroomReceiver.java
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapMultiblockController.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityCleaningMaintenanceHatch.java
Labels: type: bug

#2702 Update to MUI2 RC3
  dependencies.gradle
  src/main/java/gregtech/GregTechMod.java
  src/main/java/gregtech/api/mui/GTGuis.java
  src/main/java/gregtech/api/mui/LocaleAccessor.java
  src/main/java/gregtech/api/mui/StateOverlay.java
  src/main/java/gregtech/api/mui/UnboxFix.java
  src/main/java/gregtech/api/mui/sync/GTFluidSyncHandler.java
  src/main/java/gregtech/common/covers/CoverConveyor.java
  src/main/java/gregtech/common/covers/CoverPump.java
  src/main/java/gregtech/common/covers/ender/CoverAbstractEnderLink.java
  src/main/java/gregtech/common/covers/filter/BaseFilterContainer.java
  src/main/java/gregtech/mixins/minecraft/L18nMixin.java
  src/main/java/gregtech/mixins/minecraft/LocaleMixin.java
  src/main/java/gregtech/mixins/mui2/ClientEventHandlerMixin.java
  src/main/java/gregtech/mixins/mui2/ItemSlotSHMixin.java
  src/main/java/gregtech/mixins/mui2/LangKeyMixin.java
  src/main/java/gregtech/mixins/mui2/PanelSyncHandlerMixin.java
  src/main/java/gregtech/mixins/mui2/PanelSyncManagerMixin.java
  src/main/java/gregtech/mixins/mui2/StyledTextMixin.java
  src/main/java/gregtech/mixins/mui2/TextWidgetMixin.java
  src/main/java/gregtech/mixins/mui2/ToggleButtonMixin.java
  src/main/java/gregtech/mixins/mui2/TooltipMixin.java
  src/main/resources/mixins.gregtech.minecraft.json
  src/main/resources/mixins.gregtech.mui2.json
Labels: type: refactor

#2660 Implement Bucket Behavior to Cells
  src/main/java/gregtech/api/items/metaitem/stats/IItemBehaviour.java
  src/main/java/gregtech/api/items/metaitem/stats/ItemFluidContainer.java
  src/main/java/gregtech/common/items/MetaItem1.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: feature

#2629 Optimize JEI multiblock preview allocations
  src/main/java/gregtech/client/renderer/scene/ISceneRenderHook.java
  src/main/java/gregtech/client/renderer/scene/WorldSceneRenderer.java
  src/main/java/gregtech/common/items/behaviors/monitorplugin/AdvancedMonitorPluginBehavior.java
  src/main/java/gregtech/integration/jei/multiblock/MultiblockInfoRecipeWrapper.java
Labels: type: bug

#2705 Improve Logging (again) for Unread Packet Data
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/api/metatileentity/SyncedTileEntityBase.java
  src/main/java/gregtech/api/metatileentity/interfaces/ISyncedTileEntity.java
Labels: type: refactor, ignore changelog

#2710 Prevent Grid from rendering when holding a cover when block takes no …
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntityClipboard.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
Labels: type: bug

#2668 Fix Catalysts in Dichlorobenzidine and Diaminobenzidine
  src/main/java/gregtech/loaders/recipe/chemistry/PolymerRecipes.java
Labels: type: refactor

#2628 Add block recipes for materials that has only dust and block
  src/main/java/gregtech/loaders/recipe/handlers/MaterialRecipeHandler.java
Labels: type: feature

#2666 Fix Negative EUt in TOP
  src/main/java/gregtech/api/capability/impl/AbstractRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/BoilerRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockFuelRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogic.java
  src/main/java/gregtech/api/capability/impl/RecipeLogicEnergy.java
  src/main/java/gregtech/api/metatileentity/multiblock/FuelMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/MultiblockDisplayText.java
Labels: type: bug

#2497 High-tier fixes
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityEnergyHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityFluidHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityItemBus.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityLaserHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMufflerHatch.java
  src/main/java/gregtech/common/metatileentities/multi/multiblockpart/MetaTileEntityMultiFluidHatch.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/assets/gregtech/textures/items/metaitems/conveyor.module.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/conveyor.module.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/electric.motor.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/electric.motor.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/electric.piston.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/electric.piston.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/electric.pump.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/electric.pump.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/emitter.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/emitter.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/field.generator.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/field.generator.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/robot.arm.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/robot.arm.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/sensor.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/sensor.uxv.png
Labels: type: feature

#2718 Fix Filter Popup Panels deleting cached panel
  src/main/java/gregtech/api/mui/GTGuis.java
  src/main/java/gregtech/common/covers/ender/CoverAbstractEnderLink.java
  src/main/java/gregtech/common/covers/filter/OreDictionaryItemFilter.java
  src/main/java/gregtech/common/covers/filter/SimpleFluidFilter.java
  src/main/java/gregtech/common/covers/filter/SimpleItemFilter.java
  src/main/java/gregtech/common/covers/filter/SmartItemFilter.java
Labels: type: bug, ignore changelog

#2721 Prevent NPE from querying toolbelt before capability initialization
  src/main/java/gregtech/api/items/toolitem/ItemGTToolbelt.java
Labels: type: refactor, ignore changelog

#2724 Make different amp diodes easier to add
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
  src/main/java/gregtech/common/metatileentities/electric/MetaTileEntityDiode.java
Labels: type: feature

#2723 Make research EU/t long to be consistent with recipes using long
  src/main/java/gregtech/api/recipes/builders/AssemblyLineRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/ResearchRecipeBuilder.java
  src/main/java/gregtech/api/util/AssemblyLineManager.java
Labels: type: refactor

#2725 Update zh_cn.lang
  src/main/resources/assets/gregtech/lang/zh_cn.lang
Labels: type: translation

#2727 Un-hardcode toolbelt localization
  src/main/java/gregtech/api/items/toolitem/ItemGTToolbelt.java
  src/main/resources/assets/gregtech/lang/en_us.lang
Labels: type: refactor, ignore changelog

#2455 Port/Rework Crafting Station to MUI2 + Misc Fixes
  dependencies.gradle
  src/main/java/gregtech/api/capability/GregtechDataCodes.java
  src/main/java/gregtech/api/capability/IQuantumController.java
  src/main/java/gregtech/api/capability/impl/ItemHandlerList.java
  src/main/java/gregtech/api/gui/widgets/CraftingStationInputWidgetGroup.java
  src/main/java/gregtech/api/items/itemhandlers/GTItemStackHandler.java
  src/main/java/gregtech/api/items/toolitem/ItemGTToolbelt.java
  src/main/java/gregtech/api/mui/GTGuiTextures.java
  src/main/java/gregtech/api/mui/GregTechGuiTransferHandler.java
  src/main/java/gregtech/api/mui/InputAccessor.java
  src/main/java/gregtech/api/mui/sync/PagedWidgetSyncHandler.java
  src/main/java/gregtech/api/storage/ICraftingStorage.java
  src/main/java/gregtech/api/util/ItemStackHashStrategy.java
  src/main/java/gregtech/api/util/TextFormattingUtil.java
  src/main/java/gregtech/client/utils/RenderUtil.java
  src/main/java/gregtech/common/gui/widget/craftingstation/CraftingSlotWidget.java
  src/main/java/gregtech/common/gui/widget/craftingstation/ItemListGridWidget.java
  src/main/java/gregtech/common/gui/widget/craftingstation/ItemListSlotWidget.java
  src/main/java/gregtech/common/gui/widget/craftingstation/MemorizedRecipeWidget.java
  src/main/java/gregtech/common/inventory/handlers/ToolItemStackHandler.java
  src/main/java/gregtech/common/metatileentities/storage/CachedRecipeData.java
  src/main/java/gregtech/common/metatileentities/storage/CraftingRecipeLogic.java
  src/main/java/gregtech/common/metatileentities/storage/CraftingRecipeMemory.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCrate.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeChest.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityCreativeTank.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityQuantumStorageController.java
  src/main/java/gregtech/common/metatileentities/storage/MetaTileEntityWorkbench.java
  src/main/java/gregtech/common/mui/widget/workbench/CraftingInputSlot.java
  src/main/java/gregtech/common/mui/widget/workbench/CraftingOutputSlot.java
  src/main/java/gregtech/common/mui/widget/workbench/RecipeMemorySlot.java
  src/main/java/gregtech/integration/jei/JustEnoughItemsModule.java
  src/main/java/gregtech/mixins/jei/DragManagerAccessor.java
  src/main/java/gregtech/mixins/jei/GhostDragAccessor.java
  src/main/java/gregtech/mixins/minecraft/RecipeRepairItemMixin.java
  src/main/java/gregtech/mixins/mui2/InputMixin.java
  src/main/java/gregtech/mixins/mui2/ModularPanelMixin.java
  src/main/resources/assets/gregtech/lang/en_us.lang
  src/main/resources/mixins.gregtech.jei.json
  src/main/resources/mixins.gregtech.mui2.json
Labels: type: feature

#2731 Check item and capability before attempting to extract/insert
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
Labels: type: feature

#2734 Rework MUI2 Multi Syncing
  src/main/java/gregtech/api/metatileentity/multiblock/RecipeMapSteamMultiblockController.java
  src/main/java/gregtech/api/metatileentity/multiblock/ui/CustomKeyFunction.java
  src/main/java/gregtech/api/metatileentity/multiblock/ui/MultiblockUIBuilder.java
  src/main/java/gregtech/api/metatileentity/multiblock/ui/MultiblockUIFactory.java
  src/main/java/gregtech/api/metatileentity/multiblock/ui/UISyncer.java
  src/main/java/gregtech/api/mui/drawables/HoverableKey.java
  src/main/java/gregtech/api/mui/serialize/DrawableSerializer.java
  src/main/java/gregtech/api/mui/serialize/FormatSerializer.java
  src/main/java/gregtech/api/mui/serialize/JsonHandler.java
  src/main/java/gregtech/api/mui/serialize/KeySerializer.java
  src/main/java/gregtech/api/util/GTLambdaUtils.java
  src/main/java/gregtech/api/util/JsonUtils.java
  src/main/java/gregtech/api/util/KeyUtil.java
  src/main/java/gregtech/common/metatileentities/multi/MetaTileEntityLargeBoiler.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityActiveTransformer.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCleanroom.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityCrackingUnit.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityElectricBlastFurnace.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFluidDrill.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityHPCA.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityLargeMiner.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityMultiSmelter.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityNetworkSwitch.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPowerSubstation.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityProcessingArray.java
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityPyrolyseOven.java
  src/main/java/gregtech/common/metatileentities/multi/electric/centralmonitor/MetaTileEntityCentralMonitor.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeCombustionEngine.java
  src/main/java/gregtech/common/metatileentities/multi/electric/generator/MetaTileEntityLargeTurbine.java
Labels: ignore changelog

#2735 add API for GT Modules to subscribe to the Ore and Terrain Gen buses
  src/main/java/gregtech/api/modules/IGregTechModule.java
  src/main/java/gregtech/modules/ModuleManager.java
Labels: type: feature

#2736 General improvements to GT Module Code
  src/main/java/gregtech/api/modules/IGregTechModule.java
  src/main/java/gregtech/api/modules/IModuleManager.java
  src/main/java/gregtech/modules/ModuleManager.java
Labels: type: refactor

#2737 create the worldgen module
  src/main/java/gregtech/api/worldgen/generator/WorldGeneratorImpl.java
  src/main/java/gregtech/modules/GregTechModules.java
  src/main/java/gregtech/worldgen/WorldgenModule.java
Labels: type: refactor

#2738 rewrite rubber trees
  src/main/java/gregtech/api/worldgen/generator/WorldGeneratorImpl.java
  src/main/java/gregtech/common/blocks/wood/BlockRubberSapling.java
  src/main/java/gregtech/common/worldgen/WorldGenRubberTree.java
  src/main/java/gregtech/worldgen/WorldgenModule.java
  src/main/java/gregtech/worldgen/impl/WorldGenRubberTree.java
Labels: type: refactor

#2739 fix inconsistent voltage colors
  src/main/java/gregtech/api/GTValues.java
Labels: type: bug, ignore changelog

#2740 fix UIV and UXV textures being swapped
  src/main/resources/assets/gregtech/textures/items/metaitems/conveyor.module.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/conveyor.module.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/electric.motor.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/electric.motor.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/electric.piston.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/electric.piston.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/electric.pump.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/electric.pump.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/emitter.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/emitter.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/field.generator.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/field.generator.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/robot.arm.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/robot.arm.uxv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/sensor.uiv.png
  src/main/resources/assets/gregtech/textures/items/metaitems/sensor.uxv.png
Labels: type: bug, ignore changelog

#2743 fix malformed INITIALIZE_MTE data for PacketRecoverMTE
  src/main/java/gregtech/core/network/packets/PacketRecoverMTE.java
Labels: type: bug

#2742 remove catch throwable where possible
  src/main/java/gregtech/client/particle/GTParticleManager.java
  src/main/java/gregtech/common/covers/facade/FacadeHelper.java
  src/main/java/gregtech/common/gui/widget/monitor/WidgetCoverList.java
  src/main/java/gregtech/common/items/EnchantmentTableTweaks.java
  src/main/java/gregtech/common/worldgen/LootTableHelper.java
Labels: type: bug

#2729 Remove arbitrary restriction on casings per craft
  src/main/java/gregtech/common/ConfigHolder.java
Labels: type: refactor

#2712 Mimic Vanilla durability system
  src/main/java/gregtech/api/items/toolitem/IGTTool.java
  src/main/java/gregtech/client/utils/ToolChargeBarRenderer.java
Labels: type: feature

#2733 Fix recipe conflicts
  src/main/java/gregtech/loaders/recipe/VanillaStandardRecipes.java
Labels: type: bug

#2429 Add Material Working Tier
  src/main/java/gregtech/api/GTValues.java
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/util/GTUtility.java
  src/main/java/gregtech/loaders/recipe/handlers/MaterialRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/PartsRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/PipeRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/ToolRecipeHandler.java
  src/main/java/gregtech/loaders/recipe/handlers/WireRecipeHandler.java
  src/test/java/gregtech/api/util/VoltageScaleTest.java
Labels: type: feature

#2730 Update to MUI2 RC4
  dependencies.gradle
  src/main/java/gregtech/api/mui/LocaleAccessor.java
  src/main/java/gregtech/api/mui/widget/GhostCircuitSlotWidget.java
  src/main/java/gregtech/mixins/minecraft/L18nMixin.java
  src/main/java/gregtech/mixins/minecraft/LocaleMixin.java
  src/main/java/gregtech/mixins/mui2/InputMixin.java
  src/main/java/gregtech/mixins/mui2/LangKeyMixin.java
  src/main/java/gregtech/mixins/mui2/ModularPanelMixin.java
  src/main/resources/mixins.gregtech.minecraft.json
  src/main/resources/mixins.gregtech.mui2.json
Labels: type: refactor
