Repository GregTechCEu/GregTech, pull requests merged in 2025-04, with the labels that each got.

#2761 Add convenience methods to Material and OrePrefix for making ItemStacks
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/unification/ore/OrePrefix.java
Labels: type: feature

#2766 Fix Fusion Reactor not finding recipes
  src/main/java/gregtech/common/metatileentities/multi/electric/MetaTileEntityFusionReactor.java
Labels: type: bug, ignore changelog

#2767 Remove old comment about MTE IDs for addons
  src/main/java/gregtech/common/metatileentities/MetaTileEntities.java
Labels: ignore changelog

#2770 Remove old comment about material IDs for addons
  src/main/java/gregtech/api/unification/material/Materials.java
Labels: ignore changelog

#2765 Add convenience methods to the recipe builder
  src/main/java/gregtech/api/recipes/RecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/AssemblyLineRecipeBuilder.java
  src/main/java/gregtech/api/recipes/builders/ResearchRecipeBuilder.java
  src/main/java/gregtech/loaders/recipe/AssemblyLineLoader.java
  src/main/java/gregtech/loaders/recipe/BatteryRecipes.java
  src/main/java/gregtech/loaders/recipe/CircuitRecipes.java
  src/main/java/gregtech/loaders/recipe/ComponentRecipes.java
  src/main/java/gregtech/loaders/recipe/ComputerRecipes.java
  src/main/java/gregtech/loaders/recipe/MetaTileEntityMachineRecipeLoader.java
  src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
Labels: type: refactor

#2757 Add a method to the material builder to set the color using separate r, g, and b values instead of them being moshed together.
  src/main/java/gregtech/api/unification/material/Material.java
  src/main/java/gregtech/api/util/GTUtility.java
Labels: type: feature

#2772 Make grs setFormula method behave in the same way as ceu ones
  src/main/java/gregtech/integration/groovy/MaterialExpansion.java
Labels: type: bug

#2764 Update build script version to 1743737794
  build.gradle
  gradle.properties
Labels: ignore changelog

#2748 Properly fix potential NPE in MetaTileEntity
  src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
Labels: type: bug

#2756 Remove old ASM implementations
  gradle.properties
  src/main/java/gregtech/asm/GregTechTransformer.java
  src/main/java/gregtech/asm/hooks/ArmorHooks.java
  src/main/java/gregtech/asm/hooks/ArmorRenderHooks.java
  src/main/java/gregtech/asm/hooks/CTMModHooks.java
  src/main/java/gregtech/asm/hooks/EnchantmentHooks.java
  src/main/java/gregtech/asm/hooks/JEIHooks.java
  src/main/java/gregtech/asm/hooks/MinecraftHooks.java
  src/main/java/gregtech/asm/hooks/RecipeRepairItemHooks.java
  src/main/java/gregtech/asm/hooks/RenderChunkHooks.java
  src/main/java/gregtech/asm/hooks/RenderItemHooks.java
  src/main/java/gregtech/asm/hooks/SoundHooks.java
  src/main/java/gregtech/asm/hooks/TheOneProbeHooks.java
  src/main/java/gregtech/asm/package-info.java
  src/main/java/gregtech/asm/util/ObfMapping.java
  src/main/java/gregtech/asm/util/SafeMethodVisitor.java
  src/main/java/gregtech/asm/util/TargetClassVisitor.java
  src/main/java/gregtech/asm/visitors/AbstractCTMBakedModelVisitor.java
  src/main/java/gregtech/asm/visitors/BlockVisitor.java
  src/main/java/gregtech/asm/visitors/CCLVisitor.java
  src/main/java/gregtech/asm/visitors/ConcretePowderVisitor.java
  src/main/java/gregtech/asm/visitors/DamageSourceVisitor.java
  src/main/java/gregtech/asm/visitors/EnchantmentCanApplyVisitor.java
  src/main/java/gregtech/asm/visitors/EntityRendererVisitor.java
  src/main/java/gregtech/asm/visitors/JEIVisitor.java
  src/main/java/gregtech/asm/visitors/LayerArmorBaseVisitor.java
  src/main/java/gregtech/asm/visitors/LayerCustomHeadVisitor.java
  src/main/java/gregtech/asm/visitors/LittleTilesVisitor.java
  src/main/java/gregtech/asm/visitors/MinecraftVisitor.java
  src/main/java/gregtech/asm/visitors/ModelCTMVisitor.java
  src/main/java/gregtech/asm/visitors/ModelLoaderRegistryVisitor.java
  src/main/java/gregtech/asm/visitors/RecipeRepairItemVisitor.java
  src/main/java/gregtech/asm/visitors/RegionRenderCacheBuilderVisitor.java
  src/main/java/gregtech/asm/visitors/RenderChunkVisitor.java
  src/main/java/gregtech/asm/visitors/RenderItemVisitor.java
  src/main/java/gregtech/asm/visitors/SpecialArmorApplyVisitor.java
  src/main/java/gregtech/asm/visitors/SpecialArmorClassVisitor.java
  src/main/java/gregtech/asm/visitors/TheOneProbeVisitor.java
  src/main/java/gregtech/asm/visitors/VintagiumManagerVistor.java
  src/main/java/gregtech/asm/visitors/VintagiumPassManagerVisitor.java
  src/main/java/gregtech/asm/visitors/WorldVisitor.java
  src/main/java/gregtech/client/model/customtexture/CustomTextureBakedModel.java
  src/main/java/gregtech/client/model/customtexture/CustomTextureModel.java
  src/main/java/gregtech/client/utils/BlockHooks.java
  src/main/java/gregtech/client/utils/BloomEffectUtil.java
  src/main/java/gregtech/client/utils/CTMHooks.java
  src/main/java/gregtech/client/utils/LittleTilesHooks.java
  src/main/java/gregtech/mixins/GregTechMixinLoadingPlugin.java
  src/main/java/gregtech/mixins/ctm/AbstractCTMBakedModelMixin.java
  src/main/java/gregtech/mixins/ctm/CTMRenderInLayerMixin.java
  src/main/java/gregtech/mixins/littletiles/LittleTilesRenderMangerMixin.java
  src/main/java/gregtech/mixins/minecraft/BlockMixin.java
  src/main/java/gregtech/mixins/minecraft/RenderItemMixin.java
Labels: type: refactor

#2776 Update ru_ru lang files
  src/main/resources/assets/gregtech/lang/ru_ru.lang
Labels: type: translation
